alibaba/pouch

main.go
1. make root command of pouchd accept no args and return non-zero exit code when error；
2. make pouchd error will not output command usage.
fixes #112 
Make root command of pouchd accept no arg. Actually in fact, pouchd only accepts flags.
```
root@ubuntu:~/go/src/github.com/alibaba/pouch# ./pouchd asdfghj
Error: unknown command "asdfghj" for "pouchd"
Usage:
pouchd [flags]
Flags:
-c, --containerd string          where does containerd listened on (default "/var/run/containerd.sock")
--containerd-config string   Specify the path of Containerd binary (default "/etc/containerd/config.toml") …
```
=> fix: make pouchd accepts no args

.travis.yml
This PR adds travis CI webhook for project Pouch. Actually pouchrobot has implemented receiving webhook notifications from travis. Once test failure notification received, @pouchrobot will automatically attach CI fails comments on github pull request.
NONE
NONE
If one pr's CI fails, check whether there is a CI Failure comment attached by pouchrobot.
NONE
/cc @sunyuan3
=> feature: add travis CI webhook

daemon/containerio/discard.go, daemon/containerio/options.go
"discard" is a empty  backend, we can use it to ignore stdio. We will use
it to implement the "exec" feature.
=> feature: add discard backend for containerio

apis/server/container_bridge.go, apis/server/image_bridge.go, apis/server/router.go, apis/server/system_bridge.go, apis/server/volume_bridge.go, daemon/mgr/container.go, daemon/mgr/system.go, pkg/httputils/http_error.go
This PR adds more details for status code in http response.
Handling an error from daemon, usually api side in server should construct error with status code according to HTTP. In the original implementation, we just get an error and warp with a StatusInternalServerError(500) which seems to be a little bit coarse-grained. 
So I defined a struct as below:
```
// HTTPError represents an HTTP error which contains potential status code.
// For API layer, daemon side should return error message and using correct status code
// to construct response when an error happens in handling requests.
type HTTPError struct {
message    string
statusCode int
}
```
If one place returns err with status code known, the …
=> fix: make server http response include correct status code

apis/server/image_bridge.go, cli/pull.go, ctrd/image.go, daemon/mgr/image.go
Signed-off-by: HusterWan zirenwan@gmail.com
fix json decode error when pouch pull image error
fixes #123 .
return error message through stream body when pouch pull image
excute command line:  pouch pull busybox, will print error information
pouch:
pouchd
https://golang.org/pkg/net/http/#ResponseWriter
1)  WriteHeader  can only be called once
2)  before call Write, if  not call WriteHeader before, will call WriteHeader(http.StatusOK) first
there is a goroutine to send downloading progress information to client when pouch pull image, so when goroutine call Write once, the http header code will be set 200, later call …
=> fix: pouch pull image decode exception error

cli/create.go, test/pouch_cli_create_test.go
This pr makes container create pass correct container name. And add a test case to cover this.
fixes #175 
Make function call take container name.
Execute command, and you will find that the container name is exactly correct:
```
$ pouch create --name foo busybox:latest
container's id: ff15e41d96ecbfd4e3961bf39e31554e2b8cda46cf35fe65af4b8bb8434f1521, name: foo
```
None
=> fix: make container create pass correct container name

docs/commandline/pouchd.md, main.go
I agree with @qingyunha that pouchd's root dir should be located in /var/lib or somewhere else. Since I think /etc/pouchd should store things like configuration.
Maybe in the future, we could add pouchd's configuration file in /etc/pouchd/config.json ...
fixes #172 
NONE
NONE
/cc @skoo87 @yyb196
=> fix: make pouchd's root dir located in /var/lib

cli/cli.go, cli/command.go, cli/container.go, cli/create.go, cli/exec.go, cli/image.go, cli/main.go, cli/ps.go, cli/pull.go, cli/start.go, cli/stop.go, cli/version.go, cli/volume.go, main.go, pkg/utils/tls.go
This PR refactors cli a lot. I list the change in the following:
* make all commands' setflag as the same with the format of:
```
// Init initializes PsCommand command.
func (p *PsCommand) Init(c *Cli) {
p.cli = c
p.cmd = &cobra.Command{
......
}
p.addFlags()
}
// addFlags adds flags for specific command.
func (p *PsCommand) addFlags() {
// TODO: add flags here
}
```
* Remove `Run([]string)` in Command interface and change to define a RunE function in every single command's own scope;
* Try to use `return fmt.Errorf("failed to set raw mode")`to replace below case. and print the error message at last in main. I think this simplifies code a lot.
```
fmt.Fprintf(os.Stderr, "failed to set raw mode")
return …
```
=> refactor: make cli code more consistent

cli/image.go, cli/ps.go, cli/volume.go
This PR fixes arg number allowed in command line.
`pouch ps` and `pouch images` allows no args input.
And `pouch volume create` takes no args as well.
P.S. Flags are not args.
NONE
NONE
NONE
/cc @Letty5411
=> fix: make arg number correct in command line

cli/image.go
This PR is to fix the bug, which `pouch images -q` only show the name, not ID.
#189
NONE
NONE
=> fix: pouch images -q should only show the ID

main.go
Sometimes users need to check pouchd's version without pouch client, especially on those scenarios that we cannot send socket/HTTP request.
Add `pouchd --version` or `pouchd -v` to pouchd command line.
fixes https://github.com/alibaba/pouch/issues/43
Add a flag there
```
root@ubuntu:~/go/src/github.com/alibaba/pouch# pouchd --version
0.1.0-dev
root@ubuntu:~/go/src/github.com/alibaba/pouch# pouchd -v
0.1.0-dev
```
NONE
=> feature: add pouchd -v command

cli/cli.go, cli/main.go
Without this PR, cli error will appear twice like in issue https://github.com/alibaba/pouch/issues/192:
```
#pouch start "  fbb47a  "
Error: failed to start container   fbb47a  : failed to get container info with prefix:   fbb47a  , there are 0 containers
failed to start container   fbb47a  : failed to get container info with prefix:   fbb47a  , there are 0 containers
```
This is not reasonable and weird.
fixes https://github.com/alibaba/pouch/issues/194
Make cli silenceerror true.
```
root@ubuntu:~/go/src/github.com/alibaba/pouch# pouch start "  fbb47a  "
Error: failed to start container   fbb47a …
```
=> fix: make error msg of CLI appear just once

hack/generate-swagger-models.sh
Actually it is a bug of swagger.
The commit number of swagger 0.12.0 should be :
"68ea41dcf206410c74d397d3bbff42aedff35e4d"
But the output of command `swagger version` is:
version: 0.12.0
commit: 8135eb6728e43b73489e80f94426e6d387809502
And "8135eb6728e43b73489e80f94426e6d387809502" is the commit number of swagger 0.11.0.
It's really confusing, so remove it to avoid misleading other contributors.
=> remove the commit number in generate-swagger-models.sh

ctrd/container.go, ctrd/watch.go, daemon/containerio/container_io.go, daemon/mgr/container.go, pkg/ringbuff/ringbuff.go
the pr contain two commits, one fix exec, another fix stop.
1. fix the timeout error of "pouch stop"
e.g.
pouch stop d56e78b
Error: failed to stop container d56e78: {"message":"failed to destroy container: d56e78b56a79846d77d6d5f4d16260715e30dd7ebb118dbef91f7c639485a3a9: time out"}
2. fix "pouch exec"
when pouch exec a process that not found in $PATH in container, the
pouch cli will hang forever, don't print any error. the patch will fix
it, and print error on STDOUT.
fix #187 
=> bugfix: Fix exec and stop

ctrd/image.go, pkg/utils/utils.go, pkg/utils/utils_test.go
format image size
before image size format 
```
$ sudo ./pouch images 
IMAGE ID             IMAGE NAME                                               SIZE
bbc3a0323522         docker.io/library/busybox:latest                         2699
```
with this patch
```
$ sudo ./pouch images
IMAGE ID             IMAGE NAME                                               SIZE
bbc3a0323522         docker.io/library/busybox:latest                         2.64 KB
```
=> feature: format image size

daemon/mgr/container.go, daemon/mgr/container_types.go, daemon/mgr/container_utils.go
define a "Container" structure, it represents the container instance in
pouch engine. The "Container"s are stored in memory, so we can use
"Container".Lock() to protect itself instead of the "KMutex", because
there is defects that using "KMutex"
=> refactor: refactor the container manager

ctrd/image.go, daemon/mgr/container.go, daemon/mgr/image.go, daemon/mgr/image_test.go
Add a image cache in image manager, it uses "trie" tree to implement
looking up with id's prefix.
fix #151 
=> feature: support creating container with image's id

ctrd/container.go
containerd.WithNewSpec need context with namespace key, in function
createContainer, ctx does not have such key, which will cause
containerd.WithSpec() fail
=> fix: fix error use in new spec

apis/server/container_bridge.go, apis/swagger.yml, cli/main.go, cli/rm.go, client/container.go, daemon/mgr/container.go, daemon/mgr/container_types.go, pkg/httputils/http_utils.go
"pouch rm" is used to remove a container which is stopped or created,
if a container is running, you can use "pouch rm -f" to force to remove
the container.
=> feature: add "pouch rm"

daemon/mgr/container.go
Fix: #276
before pouch exec , pouchd should check the state of container
#276
Check the state in container.mgr
pouch exec for stop or created container. It should return error
=> fix: pouch exec should check the state of container

daemon/meta/store.go
When store tries to s.Bucket("otherBucket"), the otherBucket shares the same trie data, but the lock is different. For now, store is only used to get `meta.json`. For safety reason, we should share the trielock.
NONE
NONE
NONE
The race test is hard to do in the UT. @allencloud
=> fix: store should share the same trielock

apis/server/container_bridge.go, apis/types/container_start_config.go, daemon/mgr/container.go
struct in apis/types is used for data wrap between client side and daemon side. While here ContainerStartConfig is only used in daemon side, then I think we need to remove this. When removing this struct, some codes in daemon side need updated as well.
This work is related to start API, while it is not in swagger.yml.
So I add this API in swagger.yml.
fixes one part of #256 
NONE
NONE
/cc @skoo87
=> refactor: remove container start config object

cli/pull.go, pkg/reference/reference.go, pkg/reference/reference_test.go, pkg/reference/regexp.go
The task to parse image name should be common task. 
It can be used in create/start container.
fixes #267 
Follow the image-spec to parse the image name into reference.
NONE
NONE
=> refactor: use oci v1 reference to parse image name

ctrd/container.go, ctrd/snapshot.go
this is a simple implement to manage snaphost, Now it's reuse a existed
snapshot only.
Now, when the container stopped, the snapshot will be removed, In the future, we don't remove the snapshot until the container be removed. If restart the container, can reuse its snapshot.
this is a simple PR only, avoid to create a big pr.
=> feature: let pouch manage the snapshot

cli/container.go, cli/create.go, ctrd/container.go, daemon/config/config.go, daemon/mgr/container.go, internal/generator.go, main.go
add default runtime for pouchd, runtime set in containerd's config will
be never used.
```
./pouchd --default-runtime=runc(default will be runc)
```
add platform and runtime parameter in create container, platform means
os version, runtime means oci runtime use for container.
test:
```
$ sudo ./pouch create --runtime runc docker.io/library/busybox:latest
[sudo] password for ace: 
container ID: 5884e535ced5cb0aa228d036b18a43f15ef6d975381d5423ef0462094ac09fcf, name: 5884e5 
ace@www:~/go/src/github.com/alibaba/pouch time-> 二 12月 12 13:33:24
$ sudo ./pouch start -i 5884e5
/ # exit
```
**5.Special notes for …
=> feature: support multiple runtime

cli/container.go, cli/create.go, daemon/mgr/container.go
move the runtime flag into the common function "container.config()".
=> refactor: move runtime flag into "container.config()" in cli

client/request.go
make cli to output the detail error info, when the error is notfound. 
root@ubuntu:/media/psf/Home/sk/src/github.com/alibaba/pouch# ./pouch create registry.hub.docker.com/libraryaaaaaaaaaa/busybox:latest "/bin/echo 1111"
Error: failed to create container: {"message":"failed to create container: image: registry.hub.docker.com/libraryaaaaaaaaaa/busybox:latest: not found"}
fix #310 
=> bugfix: make cli to output the detail error info, when the error is notfound.

cli/rmi.go
This PR is to use reference package to parse name before `rmi ` command.
The pros are here:
- we can do evaluate the image name before remove. 
- use `latest` tag if user doesn't specify 
None
Use existing `pkg/reference` package to parse name. 
There are several cases:
```
➜  pouch images
IMAGE ID       IMAGE NAME                                      SIZE
3b1a65e9a05f   registry.hub.docker.com/library/centos:latest   70.03 MB
➜  pouch rmi registry.hub.docker.com/library/centos
registry.hub.docker.com/library/centos:latest
➜  pouch images
IMAGE ID   IMAGE NAME   SIZE
➜  pouch rmi …
```
=> feature: use reference to parse name before rmi

cli/create.go
Fix #233
Use reference package to parse image name before we create container.
We can evaluate image name and use latest as default tag if user doesn't add the tag.
Fixes #233 
Use existing package to parse image name.
```
➜  pouch images
bbc3a0323522   registry.hub.docker.com/library/busybox:latest   703.14 KB
➜  pouch create --name foo registry.hub.docker.com/library/busybox ls
container ID: df1a6eb52ff1d53825a65e1ce6b0f4564352c339131e92bbb0f80c52758f0f83, name: foo
➜ pouch ps
Name   ID       Status    Image …
```
=> feature: Use reference parse Image name before create container

daemon/mgr/container.go
Signed-off-by: Wendell Sun <iwendellsun@gmail.com>
As title.
In container stopped hook, lookup container again, avoid container already removed. 
before:
```
container ID: d6a3c03c8a3d0cd4620fa28054653a8225c0975c5a5d85086e0ac01e0aa430f8, name: test
test
Name   ID       Status    Image                                            Runtime
test   c76149   stopped   registry.hub.docker.com/library/busybox:latest   runc
```
after:
```
container ID: d6a3c03c8a3d0cd4620fa28054653a8225c0975c5a5d85086e0ac01e0aa430f8, name: test
test
Name   ID   Status   Image   Runtime
```
=> fix: ps command display removed container

cli/ps.go, daemon/mgr/container.go
make `pouch ps` list containers ordered by its creating time instead randomly and show creation time.
```
pouch ps
Name   ID       Status    Image                              Runtime   Created
2      f93a25   created   docker.io/library/busybox:latest   runc      about 1 hour ago
1      4ddedc   created   docker.io/library/busybox:latest   runc      about 1 hour ago
pouch create --name 3 docker.io/library/busybox:latest 
container ID: bd618e450eb9f25d101211b6c306c2292b4a01402dbef7f249cc53a9fbc921d2, name: 3 
pouch ps
Name   ID       Status    Image                              Runtime   Created
3      bd618e …
```
=> fix: make 'pouch ps' list containers orderly and show creation time.

hack/make.sh
If pouchd exits and does not generate `/var/run/pouchd.sock`, it will go into an endless loop
NONE
Check pouchd process exists, if not exist then return an error
=> fix: avoid entering the endless loop

cli/pull.go
Fix #313
Allow `pull` run in non-terminal mode. 
Before this commit, `pouch pull` must run in terminal console. If you run `pull` in non-terminal mode,  pouch will panic. 
The CI uses `exec` package to run `pull` command. Basically, the stdout of `exec.Cmd` is to `/dev/null`. Therefore if you pull images in `exec.Cmd`, the result will failed. 
Why CI of request is pass? Because the `busybox` is too small. `pull` command receives and renders the json stream fail, but the `busybox` image has been downloaded successfully. That is why the CI is green right now.
Fixed #313 
I uses `terminal` package to check if the `os.Stdout` is terminal or not. …
=> feature: pull can run in non-terminal output

test/pouch_cli_start_test.go
Remove the unstable case
Yes. Someone's CI failed caused by the unstable case.
Remove the case.
I found that "stopped" status was setting by hooked.
The task already exited but the state is still running and waiting for hook. If the ["rm" action](https://github.com/alibaba/pouch/blob/master/test/pouch_cli_start_test.go#L106) and the cleanup job reads the status before the hook, the CI will fail. 
Detail in: https://travis-ci.org/alibaba/pouch/builds/318601340#L614
The detail shows us `EOF` because the goroutine has paniced caused by https://github.com/alibaba/pouch/blob/master/ctrd/container.go#L199. If the task …
=> test: remove unstable case

cli/ps.go, daemon/mgr/container.go, pkg/utils/utils.go, pkg/utils/utils_test.go
move createdTime function into pkg\utils and fix the bug that the `pouch ps` shows wrong creation time when start a container.
```
pouch ps
Name   ID       Status    Image                              Runtime   Created
foo    f3b6c4   created   docker.io/library/busybox:latest   runc      9 seconds ago
pouch create --name foo2 docker.io/library/busybox:latest
container ID: 632bc7535ec2e92ec8ad934c1a8cf2ba4490ae71764ff9ad6b2d93e45e833889, name: foo2 
pouch create --name boo docker.io/library/busybox:latest
container ID: d7b841bd3011fb206c8c889c17dba9572f40d6f564a2b142a289eb1c68262a35, name: boo 
pouch start …
```
=> refactor: move createdTime function into pkg\utils 

apis/server/container_bridge.go, apis/swagger.yml, cli/start.go
Add detachKeys in start command and add start api in swagger.yaml
Signed-off-by: mozhuli <21621232@zju.edu.cn>
=> feature: Add detachKeys in start command and add start api in swagger.yaml

apis/swagger.yml
In swagger.yml, `DELETE /containers/{id}` and `DELETE /images/{id}` miss API status code 404.
So I add this into swagger.yml.
Add I added a separated line between endpoints and defined structs.
NONE
Add 404 status code in swagger.yml .
/cc @Letty5411
=> fix: add more status code when deleting in swagger.yml

apis/swagger.yml
This PR fixes API `GET /containers/json` in swagger.yml, since this API returns an array from pouch daemon.
NONE
NONE
NONE
NONE
=> fix: make GET /containers/json return an array in swagger.yml

apis/swagger.yml
We have already implemented `force` query in `DELETE /containers/{name}`, but we misses this part. This PR tries to add this.
NONE
Add force query in `DELETE /containers/{name}`
NONE
/cc @Letty5411
=> fix: add force query in swagger.yml when container removal

apis/server/container_bridge.go, apis/server/image_bridge.go, apis/server/router.go, apis/server/system_bridge.go, apis/server/volume_bridge.go
I found that in almost every API, the data returned is not in type of json:
This PR fixes this issue, and explicitly set `rw.Header().Set("Content-Type", "application/json")`
In addition, this PR changed some variable naming to be more clear.
NONE
Encapsulate a func named by `EncodeReponse` to set json explicitly.
=> fix: make server return json in http response

cli/create.go
Without this PR, pouch could only pass arg when creating container with quoted args, like `pouch create busybox:latest "sleep 10000"`.
With this PR, we can use `pouch create busybox:latest sleep 10000` without quote. This way is compatible with moby's way.
Make cli accept multiple args.
```
root@ubuntu:~/go/src/github.com/alibaba/pouch# pouch create --name foo4 registry.hub.docker.com/library/busybox:latest sleep 123456
container ID: 8aaa6dcab51e32d8f107dd57ac8d87435443f708471773d73e660fb13f65c11e, name: foo4
root@ubuntu:~/go/src/github.com/alibaba/pouch# pouch start foo4 …
```
=> fix: make create command accept slice command

daemon/mgr/container.go
Make sure ContainerConfig and HostConfig is not nil, when post
/containers/create with body is nil, ContainerConfig and HostConfig will
be nil, it causes pouchd panic.
fix #352 
Check ContainerConfig and HostConfig is nil or not.
Send POST /containers/create with null body and pouchd doesn't panic.
=> bugfix: make sure HostConfig is not nil

apis/swagger.yml
`POST /containers/create` will return status code 404, but not because no such container.
There is one reason that no such image. I try to fix this in swagger.yml.
NONE
NONE
NONE
NONE
=> fix: make container create API 404 be image not found

ctrd/container.go, ctrd/container_types.go, ctrd/snapshot.go, ctrd/watch.go, daemon/mgr/container.go, daemon/mgr/container_types.go
Now, when create a container, will create a snapshot with container's
id. After container be stopped, the snapshot will not be removed until
the container be removed.
=> feature: move snapshot management to container's create and remove

cli/main.go, cli/run.go, test/pouch_cli_run_test.go
add `pouch run` command
fixed #351 
```
[root@docker-registry github.com]# pouch run -i --rm --name test-rm registry.hub.docker.com/library/busybox:latest
/ # exit
[root@docker-registry github.com]#
[root@docker-registry github.com]#
[root@docker-registry github.com]# pouch ps
Name   ID   Status   Image   Runtime   Created
[root@docker-registry github.com]# pouch run -i --name test-rm registry.hub.docker.com/library/busybox:latest
/ # exit
[root@docker-registry github.com]#
[root@docker-registry github.com]#
[root@docker-registry github.com]# pouch ps
Name      ID       Status    Image …
```
=> feature: add run cli command

Makefile
fix can't build pouch without libnetwork submodule.
fix #430 
fix #428 
use 'git submodule update --init' to pull libnetwork source code before
build.
make can build pouch/pouchd.
=> bugfix: fix can not build pouch

cli/pull.go
pull pull image panic:
```
[root@docker-registry github.com]# pouch pull registry.hub.docker.com/library/busybox:latest
registry.hub.docker.com/library/busybox:latest:                                   resolved       %!f(PANIC=1: unexpected format character)
index-sha256:bbc3a03235220b170ba48a157dd097dd1379299370e1ed99ce976df0355d24f0:    done           %!f(PANIC=1: unexpected format character)
manifest-sha256:91ef6c1c52b166be02645b8efee30d1ee65362024f7da41c404681561734c465: done           %!f(PANIC=1: unexpected format character)
layer-sha256:0ffadd58f2a61468f527cc4f0fc45272ee4a1a428abe014546c89de2aa6a0eb5:    done           %!f(PANIC=1: unexpected format character) …
```
=> bugfix: fix pouch pull panic : unexpected format character

ctrd/container.go, test/api_image_create_test.go
api_image_create_test fromImage not split image name and tag, so in daemon, the image ref is `registry.hub.docker.com/library/busybox:latest:latest`
=> bugfix: api_image_create_test duplicate image tag

apis/server/container_bridge.go, apis/server/image_bridge.go, apis/swagger.yml, cli/rmi.go, daemon/mgr/container.go, daemon/mgr/container_types.go, daemon/mgr/image.go
when image is being used, must use --force to delete the image
```
[root@docker-registry github.com]# pouch ps
Name    ID       Status    Image
nginx   fa3c18   stopped   docker.io/library/nginx:latest
[root@docker-registry github.com]# pouch rmi docker.io/library/nginx:latest
Error: failed to remove image: {"message":"Unable to remove the image \"docker.io/library/nginx:latest\" (must force) - container fa3c182fb492e7a630002c19ed9fcdf1f18dcb19896f9c186f2881dae67cde31 is using this image"}
[root@docker-registry github.com]# pouch rmi -f docker.io/library/nginx:latest
docker.io/library/nginx:latest
``` …
=> feature: when image is being used, must use --force to delete the image

apis/server/container_bridge.go, apis/server/network_bridge.go, apis/swagger.yml, apis/types/container_create_config.go, apis/types/network_create_config.go, apis/types/network_create_resp.go, cli/container.go, cli/network.go, client/container.go, client/network.go, daemon/mgr/container.go, daemon/mgr/network.go, network/bridge/bridge.go
This PR makes HTTP POST request body have same name rules.
For a request body, we have rule of ObjectActionConfig, like: `NetworkCreateConfig`, `ContainerCreateConfig`, `VolumeCreateConfig`, `ExecCreateConfig` and `ExecStartConfig`.
For a response struct, we have a rule of `ObjectCreateResp`, like `ContainerCreateResp`, `NetworkCreateResp`. 
However, `VolumeCreateResp` in not in the scope, since `POST /volumes/create` API returns `VolumeInfo` which is a inconsistency in Moby's API.
/cc @rudyfly @skoo87 @Letty5411 
NONE
NONE
NONE
NONE
=> fix: make request body and response have consistent name rule

.travis.yml, Makefile
Add [Codecov](https://codecov.io/) to stat unit test coverage.
fix #439 
First, add coverage statistic in each `go test` in Makefile, then add an entry in .travis.yml.
Codecov has be well integrated with travisCI.
=> test: add codecov to stat unit test coverage

.travis.yml
Fix "make: go: Command not found" error.
Yes.
make -e means that make uses host environment variable.
make -e test
None
=> fix: make: go: Command not found

ctrd/client.go, ctrd/container.go, ctrd/watch.go, daemon/mgr/container.go
…a) to execute in one goroutine
make the two operations (stop container and modify meta data) to execute in one goroutine
=> refactor: make the two operations (stop container and modify meta data) to execute in one goroutine

apis/server/container_bridge.go, apis/server/network_bridge.go, apis/server/volume_bridge.go, apis/swagger.yml, apis/types/container_config.go
We need add a validation layer in bridge level to validate the request body's validness. 
While swagger supports to add type of struct. 
For example, `Image` in `ContainerConfig` is a required field. 
* Then we can add `required: [Image]` in `ContainerConfig`'s definition.
* And we need to auto generate structs in container_config.go;
* add validation code block in container_bridge.go.
This PR just added validation function in bridge layer of daemon side. In the future, we can only add restriction condition in swagger.yml and generate validation func in apis/types/xxx.go.
More attention, we cannot list all the validation in swagger.yml, but may be majority of that. Sometimes we still need to add …
=> feature: validate request body at the beginning of bridge layer handlers

hack/build
Unify indent in hack/build script
NONE
Use 4-space as indent instead of tab
NONE
Maybe we can unify shell indent standard in pouch project.
ping @allencloud
=> fix: unify indent in hack/build script

apis/swagger.yml, apis/types/network_create_config.go, cli/network.go, network/bridge/bridge.go
Moby has a networkCreate config with:
```
// NetworkCreateRequest is the request message sent to the server for network create call.
type NetworkCreateRequest struct {
NetworkCreate
Name string
}
```
While Pouch has : 
```
type NetworkCreateConfig struct {
// Name is the name of the network.
Name string `json:"Name,omitempty"`
// network create
NetworkCreate *NetworkCreate `json:"NetworkCreate,omitempty"`
}
```
This PR fixes this.
fix #460 
NONE
NONE
/cc @rudyfly
=> fix: make network create body compatible with Moby

apis/server/container_bridge.go, daemon/mgr/container.go, test/api_container_create_test.go
HostConfig and NetworkConfig both can be nil in client's side's request, and this should be compatible with moby's API. 
While in Daemon side, when creating with ContainerCreateConfig, function Create does not allow they to be nil, then we should do some compasation in bridge layer to meet the daemon's requirement.
NONE
NONE
NONE
/cc @rudyfly
=> fix: hostconfig and networkconfig can be nil

apis/server/container_bridge.go, apis/swagger.yml, apis/types/exec_create_config.go
This PR restricts the validate type Post request config body. 
* I add ExecCreateConfig field restriction in swagger.yml;
* generate structs in apis/types, in this struct file, there are validation funcs which takes restriction into consideration:
```
func (m *ExecCreateConfig) validateCmd(formats strfmt.Registry) error {
if swag.IsZero(m.Cmd) { // not required
return nil
}
iCmdSize := int64(len(m.Cmd))
if err := validate.MinItems("Cmd", "body", iCmdSize, 1); err != nil {
return err
}
return nil
}
```
When the above two aspects has been done, codes in https://github.com/alibaba/pouch/blob/master/apis/server/container_bridge.go#L56 will work.
```
config := &types.ExecCreateConfig{}
// decode request …
```
=> feature: add ExecConfig validation rule in swagger

apis/swagger.yml, apis/types/container_config.go, apis/types/exec_start_config.go, cli/container.go, daemon/mgr/cri.go, daemon/mgr/spec_network.go, daemon/mgr/spec_process.go
Original swagger.yml in Moby's repo has incompatibility with its API, mainly on API structs like ContainerConfig.
This pr makes API structs swagger.yml generated compatible with Moby's API:
* `AttachStdout`, `AttachStderr `, `AttachStdin`, `StdinOnce `, `OpenStdin`, `ArgsEscaped`, `StopSignal ` and `tty` should not be a pointer
NONE
NONE
NONE
NONE
=> fix: polish ContainerConfig in swagger.yml

apis/server/network_bridge.go
In pouch's bridge layer, we should always return a Content-Type of json. While current code in network_bridge.go `json.NewEncoder(resp).Encode(networkCreateResp)` will not automatically return json, see https://github.com/alibaba/pouch/pull/379.
fixes #431 
NONE
NONE
NONE
=> fix: make network response return json

hack/make.sh
Print daemon log when pouchd failed to be launched.
=> test: print pouch deamon log when it fails to launch the daemon

daemon/mgr/cri.go
implement RemoveImage and ImageStatus methods for cri manager
fixes part of #420
Use [cri-tools](https://github.com/kubernetes-incubator/cri-tools) to check.
```
→ # crictl images
IMAGE                       TAG                 IMAGE ID            SIZE
docker.io/library/busybox   latest              bbc3a03235220       720kB
→ # crictl rmi docker.io/library/busybox 
FATA[0000] image status request failed: rpc error: code = Unknown desc = image: docker.io/library/busybox: not found 
→ # crictl rmi docker.io/library/busybox:latest
Deleted: docker.io/library/busybox:latest
→ # crictl images
IMAGE …
```
=> feature: implement RemoveImage and ImageStatus methods for cri manager

apis/swagger.yml, apis/types/container.go, apis/types/container_json.go
fix: correct one reference format in swagger.yml
Otherwise, the CI would report a warning message:
```
2018/01/03 10:38:50 - WARNING: definition "#/definitions/MountPoint" is not used anywhere
```
NONE
NONE
NONE
NONE
=> fix: correct one reference format in swagger.yml

daemon/mgr/cri.go
implement Version method for cri manager
NONE
Use [cri-tools](https://github.com/kubernetes-incubator/cri-tools) to check.
```
→ # crictl version
Version:  0.1.0
RuntimeName:  pouch
RuntimeVersion:  0.1.0-dev
RuntimeApiVersion:  1.24
```
=> feature: implement Version method for cri manager

apis/server/router.go, apis/server/volume_bridge.go, apis/swagger.yml, daemon/mgr/container.go, daemon/mgr/volume.go
This PR adds two API endpoints in swagger.yml:
* GET /volumes/{id}
* DELETE /volumes/{id}
And the second API implementation has been done in code base.
This PR also adds `GET /volumes/{id}` in the daemon side. 
NONE
NONE
NONE
NONE
=> feature: add Volume Inspect API in daemon side

cli/run.go, test/cli_run_test.go
As the title says
fixes https://github.com/alibaba/pouch/issues/491
```
[root@docker-registry github.com]# pouch run -e aaa=bbb registry.hub.docker.com/library/busybox:latest env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
aaa=bbb
TERM=xterm
HOME=/root
```
```
[root@docker-registry github.com]# pouch run -d -e aaa=bbb registry.hub.docker.com/library/busybox:latest env
90719b5f9a455b3314a49e72e3ecb9962f215e0f90153aa8911882acf2ba2c84
```
=> feature: pouch run in terminal default connects to container's stdout

apis/server/container_bridge.go
In the latest master, we found that `GET /containers/{id}/json` has incomplete container state in response body, since we have not returned all data via API.
This PR fixes the bug, tries to return the whole container state in daemon side.
NONE
NONE
NONE
NONE
=> fix: add complete ContainerState in Container Inspect

daemon/mgr/cri.go
We may use the following method to verify that we can get status of cri manager:
```
[root@pouch-test monster]# crictl info
{
"status": {
"conditions": [
{
"type": "RuntimeReady",
"status": true,
"reason": "",
"message": ""
},
{
"type": "NetworkReady",
"status": true,
"reason": "",
"message": ""
}
]
}
}
```
=> feature: implement Status of cri manager

apis/server/container_bridge.go, test/api_container_exec_start_test.go, test/request/request.go, test/utils.go
If user calls `/exec/execid/start` without upgrade header, the pouchd should return 200 status.
But now, the pouchd always return 101 switch protocol. This PR is to fix this bug.
fixes #494 
For the AttachConfig, the `Upgrade` field should check header from request.
I have added the test for this.
In this PR, I upgrades the `request.Hijack` function and add more comments here: 
For hijack request, the server can return 200 status or 101 switch proto. 
If http-client doesn't switch proto, the `Do` function will return error caused by `ErrPersistEOF`.
As the RFC 2616, section 4.4 …
=> bugfix: exec should return 200 if client doesn't upgrade proto

apis/server/container_bridge.go, cli/container.go, cli/create.go, cli/run.go, daemon/mgr/spec.go, daemon/mgr/spec_cgroup_memory.go
include memory, memory-swap and memory-swappiness.
=> feature: add memory option for container

apis/server/container_bridge.go, apis/server/image_bridge.go, apis/swagger.yml, apis/types/container.go, cli/image_list.go, cli/ps.go, client/container.go, daemon/mgr/container.go, daemon/mgr/container_types.go, pkg/utils/utils.go, pkg/utils/utils_test.go, test/cli_ps_test.go, test/cli_stop_test.go, test/environment/cleanup.go
1. make 'pouch ps' show running time.
2. fix a bug that the 'Created' shows wrong time when start a container.
3. add flags "quiet" and "all" in ps command because **now `pouch ps` only shows running and paused containers by default.**
4. refactor FormatTimeInterval fuction in utils.go.
NONE. It is a follow-up PR of #358.
```
→ pouch ps
Name   ID       Status          Created          Image                              Runtime
2      e42c68   Up 26 minutes   27 minutes ago   docker.io/library/busybox:latest   runc
1      a8c2ea   Up 27 minutes   28 minutes ago   docker.io/library/busybox:latest   runc
→ pouch …
```
=> feature: make 'pouch ps' show running time and add flags in ps command.

docs/test/test.md
=> doc: add more info in test.md

cli/exec.go, test/cli_exec_test.go
This PR fixed that command args are dealt incorrectly in command `pouch exec`.
What I did:
* fix command dealing for `pouch exec` and keep that dealt by `SetInterspersed`;
* add two test cases for exec command.
fixes https://github.com/alibaba/pouch/issues/537
fixes https://github.com/alibaba/pouch/issues/536
fixes https://github.com/alibaba/pouch/issues/535
Make command executed well in command line.
```
root@ubuntu:~/go/src/github.com/alibaba/pouch# pouch exec bf50a0 ls
bin
dev
etc
home
proc
root
run
sys
tmp
usr
var
root@ubuntu:~/go/src/github.com/alibaba/pouch# pouch exec bf50a0 ls /home …
```
=> fix: make exec could get multiple commands

cli/container.go, cli/create.go, cli/run.go, test/cli_create_test.go, test/cli_run_test.go
Add lxcfs flag to cli
1. start pouchd with lxcfs
```
pouchd --enable-lxcfs=true --lxcfs=/usr/bin/lxcfs --lxcfs-home="/var/lib/lxc/lxcfs/"
```
2. pouch create with lxcfs
```
./pouch create --enableLxcfs=true  docker.io/library/busybox:latest cat /proc/uptime
./pouch inspect [container ID]
```
the value of EnableLxcfs should be true.
3. pouch run with lxcfs 
```
pouch run --enableLxcfs=true  docker.io/library/busybox:latest cat /proc/uptime
```
the output should be equal to "0.0 0.0"
=> feature: add lxcfs flag to cli

docs/test/test.md
When run unit test on local host using `go test` directly, it may run into error sometimes.
=> doc: add comments about running unit test

test/cli_run_test.go
=> test: verify lxcfs with memory limit

apis/server/container_bridge.go
The `pouch inspect` should show created time, not started at
#544 
NONE
```
➜  pouch git:(bugfix_should_use_created_instead_of_started) pouch run --name test registry.hub.docker.com/library/busybox:latest sleep 3
➜  pouch git:(bugfix_should_use_created_instead_of_started) pouch inspect test
{
"Args": null,
"Config": {
"Cmd": [
"sleep",
"3"
],
"Env": [
],
"Image": "registry.hub.docker.com/library/busybox:latest",
"Shell": null
},
"Created": "2018-01-10 13:53:51",
"HostConfig": {
"Runtime": "runc", …
```
=> bugfix: use created instead of startedAt in /container/:name/json

cli/container.go, cli/container_test.go
I found that in cli/container.go, function config() was not so straight-forward. When we need to add a parameter, it is not so clear. So I refactored this function and make it well-organized. In addition, I organized more code into separated function, like `parseLabels`, `parseDeviceMappings` and so on. So that we can test them much more easily.
Then I added some unit test for these functions.
NONE
NONE
NONE
NONE
=> refactor: make container.go much more clear

apis/swagger.yml, apis/types/container_config.go, apis/types/host_config.go, cli/container.go, daemon/mgr/container.go, test/api_container_create_test.go, test/cli_create_test.go
=> refactor: mv EnableLxcfs from ContainerConfig to HostConfig

apis/server/container_bridge.go, daemon/mgr/container_types.go, daemon/mgr/container_types_test.go
encapsulate codes into function FormatStatus
=> refactor: encapsulate codes into function FormatStatus

hack/cri-test/test-cri.sh, hack/cri-test/test-utils.sh, hack/cri-test/versions
Signed-off-by:  czm4514 <1141685075@qq.com>
this PR is to add cri test for pouch.
i use the cri-tools project to add cri test for pouch. there are lots of test cases in the project.   
when you run the test-cri.sh ,
``./test-cri.sh``
you could get the information like this(the variable focus is set to "Runtime"):
```
/root/gocodes/bin/critest
1 attempt "ctr version"! Trying again in 1 seconds...
2 attempt "ctr version"! Trying again in 2 seconds...
3 attempt "ctr version"! Trying again in 3 seconds...
4 attempt "ctr version"! Trying again in 4 seconds...
Running Suite: E2ECRI Suite
===========================
Random Seed: 1515481734 - Will randomize …
```
=> test: add cri test for pouch

daemon/mgr/container_types_test.go, pkg/utils/utils.go
The time fields such as `Created` and `StartAt` in Moby are both formatted by **RFC3339Nano** which is different from Pouch.
So I change the time format in Pouch to keep consistence with Moby.
```
>> # pouch ps
Name   ID       Status          Created          Image                                            Runtime
2      961798   Up 12 minutes   13 minutes ago   registry.hub.docker.com/library/busybox:latest   runc
>> # pouch inspect 2
{
"Args": null,
"Config": {
"Cmd": [
"sh"
],
"Env": [
],
"Image": …
```
=> refactor: make time format compatible with Moby

apis/server/network_bridge.go, cli/network.go, client/network.go
add network inspect implementation on cli and client side
fixes part of #218
a)implement network inspect on cli and client side
b)initialize IPAM field on api side
```
$ pouch network create -n net1
net1: c33c2646dc8ce9162faa65d17e80582475bbe53dc70ba0dc4def4b71e44551d6
$ pouch network inspect net1
Name:         net1
Scope:        
Driver:       bridge
EnableIPV6:   false
ID:           c33c2646dc8ce9162faa65d17e80582475bbe53dc70ba0dc4def4b71e44551d6
Internal:     false
$ pouch network remove net1
Removed: net1
$ pouch network inspect net1
Error: {"message":"network net1 not found: not found"}
```
**5.Special …
=> feature: add network inspect implementation on cli and client side

daemon/mgr/cri.go, daemon/mgr/cri_test.go, daemon/mgr/cri_utils.go
We may use the following method to verify that we can list sandboxes:
```
{
"metadata": {
"attempt": 1,
},
"linux": {
}
} …
```
=> feature: implement ListPodSandbox method of cri manager

daemon/mgr/cri.go, daemon/mgr/cri_test.go, daemon/mgr/cri_utils.go
We may use the following method to verify that we can get status of sandboxes and containers:
```
{
"metadata": {
"attempt": 1,
},
"linux": {
}
} …
```
=> feature: implement ContainerStatus and PodSandboxStatus of cri manager

.travis.yml
I changed the pouch_robot address to 121.201.63.16, since I reduced the CPU and Mem resource of it.
Pouch has no travis failure report on PR for a long time. This time I change the travis webhook CI address, then the CI failure will report as usual.
This IP is consistent with the webhook of this repo's setting.
NONE
NONE
NONE
NONE
=> fix: change travis CI webhook address

apis/server/volume_bridge.go, cli/volume.go, client/volume.go, test/api_volume_delete_test.go, test/api_volume_inspect_test.go, test/cli_volume_test.go
add volume inspect on cli and client side
fixes part of #139
Firstly, you should create a volume.
Then you verify whether or not 'volume inspect' command works.
Finally, you remove that volume and try the 'volume inspect' command again to see if the error returned indicates that the volume does not exist.
```
$ pouch volume create -d local -n pouch-volume -o size=100g
Mountpoint:   
Name:         pouch-volume
Scope:        
CreatedAt:    
$ pouch volume inspect pouch-volume
Mountpoint:   /mnt/local/pouch-volume
Name:         pouch-volume
Scope:        
CreatedAt:    2018-1-17 14:09:30 …
```
=> feature: add volume inspect on cli and client side

hack/make.sh
`docker -ti` may fail due to no TTY could be allocated. And for CI, there is no need to allocate a tty when create a test container.
=> test: remove -it option when start test contaienr

hack/package/build.sh, hack/package/rpm/Dockerfile, hack/package/rpm/scripts/after-install.sh, hack/package/rpm/scripts/after-remove.sh, hack/package/rpm/scripts/after-trans.sh, hack/package/rpm/scripts/before-install.sh, hack/package/rpm/scripts/before-remove.sh, hack/package/rpm/service/lxcfs.service, hack/package/rpm/service/pouch.service
This pr added a way to build rpm package
fixes part of #67
1. Build pouch:rpm image
cd hack/package/rpm
docker build -t pouch:rpm .
2. Mount a directory which contains gpg keys, eg
$ tree rpm/keys/
rpm/keys/
├── gpg
└── secretkey
3. Run the following command, and enter your pass phrase to sign rpm package
docker run -it -v /root/rpm/:/root/rpm pouch:rpm bash -c hack/package/build.sh
4. In this example rpm package will be output in '/root/rpm/package/' directory
=> feature: build rpm package for pouch

apis/server/router.go, apis/server/volume_bridge.go, cli/volume.go, client/volume.go, test/api_volume_list_test.go, test/utils.go
Add volume list command, it returns all the volumes in pouch.
Now it just returns the name of volume.
NONE
create three volume in pouchd
```
CreatedAt:
Mountpoint:
Name:         pouch-volume-1
Scope:
Mountpoint:
Name:         pouch-volume-2
Scope:
CreatedAt:
Scope:
CreatedAt:
Mountpoint:
Name:         pouch-volume-3
```
then use list to get the volumes that are created just now.
```
Name:
pouch-volume-1
pouch-volume-2
pouch-volume-3
```
=> feature: add volume list command

daemon/mgr/container.go, daemon/mgr/spec.go, daemon/mgr/spec_cgroup_cpu.go, daemon/mgr/spec_cgroup_memory.go, daemon/mgr/spec_devices.go, daemon/mgr/spec_namespace.go, daemon/mgr/spec_network.go, daemon/mgr/spec_process.go, daemon/mgr/spec_volume.go
Wrap the container's specs, in the spec setup functions, it maybe need
some daemon manager to get/set container information, so wrapping the
containerManager/volumeManager/networkManager into the spec.
NONE
=> refactor: wrap the container's specs

test/api_container_create_test.go, test/cli_run_test.go
add tests for restartpolicy=always/none
=> test: add restart policy always and none test

apis/swagger.yml, apis/types/image_info.go, ctrd/image.go, daemon/mgr/cri.go, daemon/mgr/cri_utils.go, daemon/mgr/image.go, test/api_image_inspect_test.go
Add config to ImageInfo and user  info to CriImage.
fixes #570  
```
-> #pouch images
ac2fc418f334   registry.hub.docker.com/library/busybox:latest   710.48 KB
-> #pouch image inspect  registry.hub.docker.com/library/busybox:latest
{
"Config": {
"Cmd": [
"sh"
],
"Env": [
],
"Image": "",
"Shell": null
},
"CreatedAt": "2018-01-17T06:59:16.191892985Z",
"Digest": "sha256:ac2fc418f3348815e68e266a5aa1b60bc522581c96964912560a0baacc4f5c06",
"ID": …
```
=> feature: add config to ImageInfo and user to CriImage

cli/container.go, cli/create.go, cli/run.go, daemon/mgr/spec_namespace.go, test/cli_run_test.go
With this PR, we could specify uts, ipc and pid namespace mode of `pouch create` and `pouch run`
In terminal one: 
```
[root@pouch-test pouch]# pouch run -it docker.io/library/ubuntu:14.04 bash
root@pouch-test:/# ipcmk -Q
Message queue id: 0
root@pouch-test:/# ipcs -q
------ Message Queues --------
key        msqid      owner      perms      used-bytes   messages    
0x50b336a0 0          root       644        0            0           
root@pouch-test:/# top
```
In terminal two: run a container to share the pid & ipc namespace of container created above.
```
[root@pouch-test monster]# pouch run -it …
```
=> feature: ipc, pid, uts namespace mode of container

daemon/containerio/mem_buffer.go, daemon/containerio/options.go, daemon/mgr/container.go, daemon/mgr/container_types.go
Now we only support using http to handle container IO.
With this PR, we could use memory buffer (bytes.Buffer in golang) as another backend type to handle container IO.
=> feature: memory buffer container io backend

test/cli_run_test.go
As described in issue #569, cli_run_test.go always panic on CentOS.
After debugging, it may be related to the `PruneAllContainers` function in environment/cleanup.go.
Currently, adding remove CLI in each test could workaround this failure.
=> test: add a workaround for issue#569

daemon/mgr/container.go
=> bugfix:  can remove the exited container without flag force.

apis/swagger.yml, apis/types/resources.go
=> feature: add blkio related parameters in swagger

test/cli_create_test.go, test/cli_exec_test.go, test/cli_ps_test.go, test/cli_pull_test.go, test/cli_rmi_test.go, test/cli_run_test.go, test/cli_start_test.go, test/cli_stop_test.go, test/cli_unpause_test.go
Remove `PruneAllContainers` function in TearDownTest, as it has already been called in SetupTest.
We should not rely on this function to do all cleanup work.
And this function may be the reason why test cases panic.
fix #569 
=> test: remove cleanup on teardowntest

test/cli_create_test.go, test/cli_exec_test.go, test/cli_ps_test.go, test/cli_pull_test.go, test/cli_rmi_test.go, test/cli_run_test.go, test/cli_start_test.go, test/cli_stop_test.go
When call cleanup function in SetupTest, we could ignore the error.
As this is not the `test point`, if you really wanna test cleanup work, you could code it explicitly in Test cases.
=> test: ignore error in cleanup function

apis/swagger.yml, apis/types/image_info.go, cli/image_list.go, ctrd/image.go, ctrd/utils.go, daemon/mgr/container.go, daemon/mgr/cri_utils.go, daemon/mgr/image.go, pkg/utils/utils.go, test/cli_images_test.go
add fields `Architecture` `Os ` `RootFS` to ImageInfo and change the generation of image ID.
```
-># pouch images
9ffc1866b13a   registry.hub.docker.com/library/busybox:latest   710.74 KB
-># pouch image inspect registry.hub.docker.com/library/busybox
{
"Architecture": "amd64",
"Config": {
"Cmd": [
"sh"
],
"Env": [
],
"Image": "",
"Shell": null
},
"CreatedAt": "2018-01-24T04:29:35.590938514Z",
"ID": …
```
=> feature: add fields to ImageInfo

daemon/mgr/cri.go, hack/cri-test/test-cri.sh
For method ImageRemove and ImageStatus, if the image doesn't exist, we should return an empty response instead of an error. Hmmm...., bugfix may be more appropriate for this PR 😄 
With this PR and #617 being merged, it is ok for us to add "basic operations on container" CRI test into CI.
=> feature: return empty if the image doesn't exist in CRI mananger and add "basic operations on container" into CI

cli/container.go, cli/create.go, cli/run.go, daemon/mgr/cri_utils.go, daemon/mgr/spec.go, daemon/mgr/spec_linux.go, hack/cri-test/test-cri.sh, test/cli_create_test.go, test/cli_run_test.go, test/cli_start_test.go
```
[root@pouch-test monster]# pouch run --sysctl kernel.shm_rmid_forced=1 docker.io/library/busybox:latest
[root@pouch-test monster]# pouch exec 7ee857 cat /proc/sys/kernel/shm_rmid_forced
1
```
=> feature: sysctl configuration for both cri manager and container manager

cli/container.go, cli/create.go, cli/run.go, daemon/mgr/container.go, daemon/mgr/container_utils.go, daemon/mgr/cri.go, daemon/mgr/cri_utils.go, daemon/mgr/spec.go, daemon/mgr/spec_linux.go, hack/cri-test/test-cri.sh, test/cli_create_test.go, test/cli_run_test.go, test/cli_start_test.go
With this PR, we could enable one of the security option AppArmor.
Now we could apply AppArmor with options like:
1. "apparmor=unconfined": which means don't apply any AppArmor profile
2. "apparmor=XXX": which means apply AppArmor profile "XXX"
3. "apparmor=pouch-default": see below.
Actually in docker, we should apply default AppArmor profile "docker-default" to every container which not explicitly specify it or explicitly specify it with "docker-default". We should implement it in pouch as well.
=> feature: appArmor for both cri manager and container manager

apis/swagger.yml, daemon/mgr/network.go, test/api_network_create.go
Report error message when creating a new network with an existent name.
fixes #662 
Before creating a new network, check if the network name exists.
$ pouch network create net1
net1: b8d22aaa9db862f9f393eca9f4bdb45b12539b6352d417456bf4fd7774f3e2de
$ pouch network create net1
Error: {"message":"network net1 already exists"}
=> fix: report error when creating a new network with an existent name

cli/container.go, cli/create.go, cli/run.go, daemon/mgr/container.go
I merged #660 , while @YaoZengzeng found that there are some code needed improvement. So I submit a PR to fix this.
NONE
NONE
NONE
NONE
=> refactor: fix code issue brought by 660

test/api_image_create_test.go, test/api_image_delete_test.go, test/api_image_inspect_test.go, test/api_image_list_test.go, test/api_network_inspect_test.go, test/api_network_list_test.go, test/api_system_test.go, test/api_volume_create_test.go, test/api_volume_delete_test.go, test/api_volume_inspect_test.go, test/api_volume_list_test.go
In issue https://github.com/alibaba/pouch/issues/673, we found that some integration test fails without showing any error message, I think it is very unreasonable for us to debug and bugfix.
So, I think we need to use `CheckRespStatus(c, resp, code )` to check status code and should error if this checking failed.
However, we still have one potential issue:
```
// CheckRespStatus checks the http.Response.Status is equal to status.
func CheckRespStatus(c *check.C, resp *http.Response, status int) {
if resp.StatusCode != status {
got := types.Error{}
_ = request.DecodeBody(&got, resp.Body)
c.Assert(resp.StatusCode, check.Equals, status, check.Commentf("Error:%s", got.Message))
}
}
In the code above if we …
```
=> test: use CheckRespStatus(c, resp, code) to add comment when failure

apis/swagger.yml, apis/types/resources.go
In Pouch, we support more useful container options on isolation. This helps a lot when Pouch comes to production environment in enterprises.
Here we add 5 container options there, 1 is going to support in runC, while the other 4 is supported in the coming opensourced alios.
IntelRdtL3Cbm is coming in RunC.
ScheLatSwitch
MemoryWmarkRatio
MemoryExtra
MemoryForceEmptyCtl
are from alios, they are all about per memcg background reclaim.
For these option, we will go on to support them in alibaba/runc. And we will make effort in supporting these in upstream.
NONE
NONE
NONE …
=> feature: add alios container extra options

cli/container.go, cli/create.go, cli/run.go, daemon/mgr/cri_utils.go, daemon/mgr/spec.go, daemon/mgr/spec_linux.go, test/cli_create_test.go, test/cli_run_test.go, test/cli_start_test.go, vendor/github.com/docker/docker/LICENSE, vendor/github.com/docker/docker/NOTICE, vendor/github.com/docker/docker/daemon/caps/utils_unix.go, vendor/github.com/syndtr/gocapability/LICENSE, vendor/github.com/syndtr/gocapability/capability/capability.go, vendor/github.com/syndtr/gocapability/capability/capability_linux.go, vendor/github.com/syndtr/gocapability/capability/capability_noop.go, vendor/github.com/syndtr/gocapability/capability/enum.go, vendor/github.com/syndtr/gocapability/capability/enum_gen.go, vendor/github.com/syndtr/gocapability/capability/syscall_linux.go, vendor/vendor.json
With this PR, we could scope the capability of containers.
```
root@pouch-ubuntu:/home/monster# pouch run busybox:1.26 brctl addbr foobar
brctl: bridge foobar: Operation not permitted
root@pouch-ubuntu:/home/monster# pouch run --cap-add NET_ADMIN busybox:1.26 brctl addbr foobar
root@pouch-ubuntu:/home/monster# 
```
There are some problems with container manager's `StartExec` method, we couldn't pass the corresponding tests in cri-tools. 
I'll fix it ASAP :)
=> feature: capability for both cri manager and container manager

cli/container_test.go
add parseDeviceMappings test in cli part 
NONE
=> test: add parseDeviceMappings test in cli part

cli/container_test.go
add parseSysctl and parseNetwork unit test
NONE
=> test: add parseSysctl and parseNetwork unit test

cli/container.go, cli/create.go, cli/run.go, daemon/mgr/cri_utils.go, daemon/mgr/spec_linux.go, hack/cri-test/test-cri.sh, test/cli_create_test.go, test/cli_run_test.go, test/cli_start_test.go
If the container is in privilege mode, it will have the full access to the host.
```
root@pouch-ubuntu:/gopath/src/github.com/alibaba/pouch# pouch run busybox:1.26 brctl addbr foobar
brctl: bridge foobar: Operation not permitted
root@pouch-ubuntu:/gopath/src/github.com/alibaba/pouch# pouch run --privileged busybox:1.26 brctl addbr foobar
root@pouch-ubuntu:/gopath/src/github.com/alibaba/pouch# 
```
As the development move on, we should consider if the container is in privilege mode in more places.
=> feature: privilege mode for both cri manager and container manager

test/utils.go
make api test error show error message, since we found that in CI there is no detailed error message:
```
10:20:07 /go/src/github.com/alibaba/pouch/test/api_volume_list_test.go:26:
10:20:07     // Create a volume with the name "TestVolume1".
10:20:07     err := CreateVolume(c, "TestVolume1", "local")
10:20:07 /go/src/github.com/alibaba/pouch/test/utils.go:229:
10:20:07     c.Assert(resp.StatusCode, check.Equals, 201)
10:20:07 ... obtained int = 500
10:20:07 ... expected int = 201
```
None
None
None
@Letty5411
=> test: make api test error show error message

cli/volume.go, test/cli_volume_test.go
fix volume create --label error and add a test.
fix #706
=> fix: fix volume label error, issue#706

daemon/mgr/container_types.go, daemon/mgr/container_utils.go, daemon/mgr/cri.go, daemon/mgr/cri_utils.go, daemon/mgr/spec.go, daemon/mgr/spec_linux.go, test/cli_create_test.go, test/cli_run_test.go, test/cli_start_test.go, vendor/github.com/containerd/containerd/contrib/seccomp/seccomp.go, vendor/github.com/containerd/containerd/contrib/seccomp/seccomp_default.go, vendor/vendor.json
With this PR, we could enable one of the security option seccomp.
Now we could apply seccomp with options like:
1. "seccomp=unconfined": which means don't apply any seccomp profile
2. "seccomp=XXX": which means apply seccomp profile "XXX"
3. "seccomp=pouch-default": see below.
Actually in docker, we should apply default seccomp profile "docker-default" to every container which not explicitly specify it or explicitly specify it with "docker-default". We should implement it in pouch as well.
```
[root@pouch-test ~]# pouch run busybox:1.26 chmod 400 /
[root@pouch-test ~]# cat /root/block-chmod.json 
{
"defaultAction": "SCMP_ACT_ALLOW",
"syscalls": [
{
"names": ["chmod"],
"action": "SCMP_ACT_ERRNO"
}
]
}
[root@pouch-test …
```
=> feature: seccomp for cri manager and container manager

daemon/mgr/container.go, daemon/mgr/container_types.go, daemon/mgr/cri.go
Now the caller can't get the status (such as exitCode, exitTime, etc) of exec process which caused 
great trouble for us to pass many CRI related test cases.
With this PR, the problem described above is gone.
We may use the following method to verify that we can create and start container in sandbox:
```
{
"metadata": {
"attempt": 1,
},
"linux": {
}
}
[root@pouch-test cri-tools]# crictl …
```
=> feature: InspectExec method of Container manager to get the result of exec

cli/container.go, cli/container_test.go
This PR refactored a little bit in option parsing function. Originally, these functions pass a slice as parameter, and have no function to pass string parameter.
This PR splits a separate function with a function passing string parameter.
In the future, I think these parsing work should be moved into another package like /pouch/opts, since this work may be used in both client side and daemon side.
This work also simplifies the test code. It helps a little bit on how to write readable test code.
None
None
None
None
=> refactor: split parse function pass single parameter

pkg/collect/safe_map.go, pkg/collect/safe_map_test.go
This PR adds unit tests for pkg safe map.
And it also fixes some potential bugs in pkg safemap.
`return v.data.(string), v.ok` will panic if v.data has a type of non-string. So we need to refactor that to be 
```
if result, ok := v.data.(int64); ok {
return result, ok
}
return 0, false
```
none
none
none
=> test: add unit test cases for safe map in pkg

cli/container.go, cli/create.go, cli/run.go, daemon/mgr/container.go, daemon/mgr/cri_utils.go, daemon/mgr/spec_process.go, hack/cri-test/test-cri.sh, test/cli_create_test.go, test/cli_run_test.go, test/cli_start_test.go
Actually the user option is so complicated in docker, it could be in format as follows:
"" | "user" | "uid" | "user:group" | "uid:gid" | "user:gid" | "uid:group"
Hmmm... It is hard to implement all of them in a short time.
With this PR, you could only specify user option with "uid", but in most cases, it is enough 😄 
fixes part of #635
=> feature: user configuration for cri manager

.travis.yml
We usually have CI failure notification in pouch open source project, but I found that recently when pr fails the CI, no reports from @pouchrobot .
I found that in CI robot, we have log like 
`time="2018-02-16T22:49:52Z" level=info msg="{\"id\":342562335,\"number\":\"1701\",\"config\":{\"dist\":\"trusty\",\"sudo\":\"required\",\"language\":\"go\",\"go\":[\"1.9.1\"],\"go_import_path\":\"github.com/alibaba/pouch\",\"notifications\":{\"webhooks\":{\"urls\":[\"http://121.201.63.16:6789/ci_notifications\"],\"on_failure\":\"always\",\"on_error\":\"always\"}},\"before_install\":[\"sudo apt-get update -qq\",\"sudo apt-get install -y -qq autoconf automake\"],\"script\":[\"sudo make -e test\"],\"after_success\":[\"bash <(curl -s …
=> fix: make no quote in .travis.yml to enable CI failure notification

cli/container.go, cli/container_test.go, cli/create.go, cli/run.go, daemon/mgr/spec.go, daemon/mgr/spec_linux.go, test/cli_create_test.go
In pouch, we need to support more container isolation options, such as Intel Rdt L3 Cbm. This PR added `IntelRdtL3Cbm ` for pouchd.
This is related to https://github.com/alibaba/pouch/issues/688
None
None
In the following days, I will refactor the spec file in folder mgr. I think the structure of all spec files are a little bit casual, and we need to make it more structured.
This should be tested in AliOS 4.9, and could we make the test configure whether to run according to the type of CI system? Like travis CI, do not run this IntelRdtL3Cbm related test case, and run that in AliOS 4.9 CI system. @Letty5411
=> feature: support IntelRdtL3Cbm in pouch container

apis/swagger.yml, apis/types/resources.go, cli/container.go, cli/create.go, cli/run.go, daemon/mgr/spec.go, daemon/mgr/spec_alios.go, test/api_container_create_test.go, test/cli_create_test.go
This PR added four alios related container isolation options for pouch. These four options are:
* ScheLatSwitch
* MemoryWmarkRatio
* MemoryExtra
* MemoryForceEmptyCtl
These options are introduced in PR #685 .
This PR made these options supported in Pouch daemon. When supporting, we add these options in the `annotation` filed of spec. And we make runc to deal these options rather than pouch daemon. We make this via passing these data as specified keys, like `_MEMORY_XXX`, like:
* _MEMORY_WATER_MARK_RATIO
* _MEMORY_EXTRA
* _MEMORY_FORCE_EMPTY_CTL
* _SCHEDULE_LATENCY_SWITCH
This is related to issue #688 
None
None
None
=> feature: add container memory isolation options

apis/server/container_bridge.go, cli/container.go, daemon/mgr/container.go, daemon/mgr/network.go, network/mode/init.go
Remove endpoint when container stop and clean endpoint configure.
Add network information in get container/containers apis.
NONE
remove endpoint when container is stopping, and then clean endpoint information.
The container is running, there is a veth on p0 bridge, when container have been stopped, the veth will disapper on p0 bridge.
```bash
c6c765c103a20a21f2443074719815c375ab8c877ba2b787c31de704df7b52a6
bridge name	bridge id		STP enabled	interfaces
p0		8000.7a240a202b81	no		veth2ceb5e4
bridge name	bridge id		STP enabled	interfaces
p0		8000.000000000000	no
```
=> feature: remove endpoint when container stop

test/cli_rmi_test.go, test/utils.go
As issue #770 exists, cli_rmi_test.go may fail as following:
```
FAIL: /go/src/github.com/alibaba/pouch/test/cli_rmi_test.go:26: PouchRmiSuite.TestRmiWorks
/go/src/github.com/alibaba/pouch/test/cli_rmi_test.go:29:
command.PouchRun("rmi", busyboxImage).Assert(c, icmd.Success)
/go/src/github.com/alibaba/pouch/vendor/github.com/gotestyourself/gotestyourself/icmd/command.go:61:
t.Fatalf("at %s:%d - %s\n", filepath.Base(file), line, err.Error())
... Error: at cli_rmi_test.go:29 - 
Command:  /usr/local/bin/pouch rmi registry.hub.docker.com/library/busybox:latest
ExitCode: 1
Error:    exit status 1
Stdout:   
Stderr:   Error: failed to remove image: {"message":"Unable to remove the image \"registry.hub.docker.com/library/busybox:latest\" (must …
```
=> test: use helloworld image in image test

daemon/mgr/spec_linux.go
On a machine which does not support intel RDT, it would fail when creating a container:
```
root@ubuntu:/sys/fs/cgroup/memory/default# pouch run -d -m 20m registry.hub.docker.com/library/busybox:latest sleep 40
Error: failed to run container 11981b: {"message":"failed to create task, container id: 11981bee17b4a067ecd75d84b1598bcf6f5fa859d4ad119db40295d83de44869: OCI runtime create failed: intelRdt is specified in config, but Intel RDT feature is not supported or enabled: unknown"}
```
So the code base should not assign value when the RDT is empty.
This PR fixes this bug.
none
None
none
/cc @Letty5411
=> fix: make intel RDT compatible with legacy machines

apis/swagger.yml, apis/types/container_config.go, apis/types/host_config.go, cli/common_flags.go, cli/container.go, daemon/mgr/container_rich_mode.go, daemon/mgr/container_rich_mode_test.go, daemon/mgr/spec.go, daemon/mgr/spec_hook.go, daemon/mgr/spec_process.go
In pouch, we can start container in rich container mode by cli flag or API.
If by pouch client, we can set --rich flag to set rich container mode, and set --rich-mode to select which manner to init container, we support systemd, /sbin/init and dumb-init to init container.
If set dumb-init to init container, please install dumb-init in machines, https://github.com/Yelp/dumb-init/tree/v1.2.1
if set systemd or /sbin/init, we need to install systemd or /sbin/init in image.
Otherwise, we need to install runc modified by us to support it, referring to https://github.com/alibaba/runc/tree/v1.0.0-rc4-1.
=> feature: add rich container mode

daemon/config/config.go, main.go, pkg/kernel/kernel.go, pkg/kernel/kernel_test.go, pkg/quota/grpquota.go, pkg/quota/prjquota.go, pkg/quota/quota.go, volume/modules/local/local.go
Modify quota driver by kernel version, if kernel version >= 4.0, quota
uses prjquota, otherwise using grpquota.
Add quota config, when running pouchd, you can use quota-driver to set
the driver of quota. Currently, it supports "prjquota" and "grpquota."
fixes #798 
=> bugfix: set quota by kernel version

daemon/mgr/container.go, test/cli_run_test.go
According to issue #813, I found there would be some improvement in code:
```
} else {
// Create the host path if it doesn't exist.
_, err := os.Stat(source)
if err != nil && !os.IsNotExist(err) {
return errors.Errorf("failed to stat %q: %v", source, err)
}
err = os.MkdirAll(source, 0755)
if err != nil {
return errors.Errorf("failed to mkdir %q: %v", source, err)
}
}
```
In the code above, I found that no matter `_, err := os.Stat(source)` returns a non-nil error or nil, `err = os.MkdirAll(source, 0755)` will always be executed which is unreasonable. If `_, err := os.Stat(source)` returns a nil error, we should regard it as a successful checking and move on.
fixes #813
None
```
touch /tmp/asdfghjkl 
pouch run -d -v …
```
=> fix: ordinary binary volume binding bugs

cli/inspect.go, cli/inspect/inspector.go, cli/inspect/inspector_test.go, cli/update.go, pkg/utils/templates/templates.go, pkg/utils/templates/templates_test.go, test/cli_inspect_test.go
pouch inspect support format flag
fixes https://github.com/alibaba/pouch/issues/801
```
root@osboxes:wanziren -> pouch inspect  68d0d2
{
"Args": null,
"Config": {
"Cmd": [
"sh"
],
"Env": [
],
"Image": "registry.hub.docker.com/library/busybox:latest",
"Shell": null
},
"Created": "2018-03-07T10:08:51.916962435Z",
"HostConfig": {
"NetworkMode": "bridge",
"RestartPolicy": {
"Name": "no"
},
"Runtime": "runc",
"BlkioDeviceReadBps": null,
"BlkioDeviceReadIOps": null,
"BlkioDeviceWriteBps": null,
"BlkioDeviceWriteIOps": null,
"BlkioWeightDevice": null,
"CgroupParent": "/cgroup-parent/test",
"DeviceCgroupRules": null,
"Devices": [],
"Memory": …
```
=> feature: pouch inspect support format flag

cli/common_flags.go, cli/container.go, daemon/config/config.go, daemon/mgr/container.go, main.go, test/cli_run_test.go, test/cli_update_test.go
Signed-off-by: HusterWan zirenwan@gmail.com
add --cgroup-parent flag for pouchd , cgroup-parent is to set parent cgroup for all containers
start pouchd with cgroup-parent flag
```
pouchd --cgroup-parent test --debug
```
create a new container
```
[root@osboxes pouch]# pouch run -d -m 20m --name test-cgroupParents registry.hub.docker.com/library/busybox:latest
a8bea71cf77dcadaef5016677805af4fa6b6dd63c937ba79d34dacf6c73ee0ae
```
watch new container's cgroup parent path
```
[root@osboxes pouch]# cat /sys/fs/cgroup/memory/test/a8bea71cf77dcadaef5016677805af4fa6b6dd63c937ba79d34dacf6c73ee0ae/
cgroup.clone_children               memory.kmem.tcp.max_usage_in_bytes  memory.oom_control
cgroup.event_control                memory.kmem.tcp.usage_in_bytes      memory.pressure_level
cgroup.procs …
```
=> feature: add cgroupspath flag for pouchd

apis/swagger.yml, apis/types/host_config.go, cli/common_flags.go, cli/container.go, daemon/mgr/container.go, daemon/mgr/network.go, network/types/endpoint.go, test/cli_network_test.go, vendor/github.com/docker/go-connections/LICENSE, vendor/github.com/docker/go-connections/nat/nat.go, vendor/github.com/docker/go-connections/nat/parse.go, vendor/github.com/docker/go-connections/nat/sort.go, vendor/vendor.json
Add port mapping for container. You can use:
-p or --port to port binging into container
--expose to expose container's port to access.
NONE
```
```
=> feature: add port mapping for container

pkg/quota/grpquota.go, pkg/quota/prjquota.go
fix project quota can't be set on alikernel-4.9, and adding some debug
logs.
NONE
```bash
Name:         test
Scope:
Status:       map[mount:/home/volume sifter:Default size:1g]
CreatedAt:    2018-3-8 20:03:39
Labels:       map[backend:local hostname:e19h19470.et15sqa]
Mountpoint:   /home/volume/test
/dev/sda5 on /home type ext4 (rw,relatime,prjquota,data=ordered)
Filesystem                Size      Used Available Use% Mounted on
overlay                  49.1G     14.9G     31.7G  32% /
tmpfs                    64.0M         0     64.0M   0% /dev
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                    64.0M         0     64.0M   0% /run
/dev/sda5                 1.0G      4.0K   1024.0M   0% /mnt
tmpfs                    64.0M         0 …
```
=> bugfix: fix project quota can't be set on kernel-4.9

docs/test/test.md
=> doc: refine test doc

cli/image_inspect.go, cli/network.go, cli/volume.go, test/cli_images_test.go, test/cli_network_test.go, test/cli_volume_test.go
Add inspect format option for image/network/volume.
```
#pouch network inspect -f {{.Name}} bridge
bridge
#pouch image inspect -f {{.Name}} docker.io/library/busybox:latest
docker.io/library/busybox:latest
```
=> [feature] add inspect format for image network and volume

Dockerfile
In the original Dockerfile, we use command `go get -u github.com/go-swagger/go-swagger/cmd/swagger` to install swagger binary which is already from the newest code. And we cannot guarantee the quality of the latest code ever.
As we had a rule in `hack/generate-swagger-models.sh` that we should use swagger 0.12.0 to meet our requirement, we should always download a binary which is locked to version swagger 0.12.0.
As a result, I change the command to be `wget --quiet -O /bin/swagger https://github.com/go-swagger/go-swagger/releases/download/0.12.0/swagger_linux_amd64`.
This issue happens almost in all pull requests which we have modified the swagger.yml.
Like https://github.com/alibaba/pouch/pull/879, …
=> fix: make swagger version locked 0.12.0 rather than lastet

hack/make.sh
Print error log in CI. Don't redirect the error log to a file.
Yes. CI did miss some error logs. We need to print these logs.
Print error log in CI.
NA
NA
=> [test] Print error log in CI.

main.go, vendor/github.com/google/gops/LICENSE, vendor/github.com/google/gops/agent/agent.go, vendor/github.com/google/gops/internal/internal.go, vendor/github.com/google/gops/signal/signal.go, vendor/github.com/kardianos/osext/LICENSE, vendor/github.com/kardianos/osext/README.md, vendor/github.com/kardianos/osext/osext.go, vendor/github.com/kardianos/osext/osext_go18.go, vendor/github.com/kardianos/osext/osext_plan9.go, vendor/github.com/kardianos/osext/osext_procfs.go, vendor/github.com/kardianos/osext/osext_sysctl.go, vendor/github.com/kardianos/osext/osext_windows.go, vendor/vendor.json
add gops debug tool for pouch
fixes https://github.com/alibaba/pouch/issues/863
first, install gops tool on your compute:
```
$ go get -u github.com/google/gops
```
second, get pouchd process id, `gops` will print all golang process on your machine.
```
$ gops
```
last, print the pouchd process stack
```
$ gops stack $PID
```
print process goroutine stack just like blow
```
goroutine 863 [select, 2 minutes]:
github.com/alibaba/pouch/vendor/google.golang.org/grpc/transport.wait(0x7f74e0e4c0c8, 0xc420bb42a0, 0x0, 0x0, 0xc4203e0480, 0xc4203680e0, 0x0, 0x0, 0xc420408420)
/tmp/pouchbuild/src/github.com/alibaba/pouch/vendor/google.golang.org/grpc/transport/transport.go:635 +0x181
github.com/alibaba/pouch/vendor/google.golang.org/grpc/transport.(*ht …
```
=> feature: add debugger tool for pouch

cli/common_flags.go, cli/container.go, daemon/mgr/cri.go, daemon/mgr/cri_utils.go, daemon/mgr/spec_process.go, hack/cri-test/test-cri.sh, pkg/user/user.go, pkg/user/user_test.go
We skip the test of "HostNetworkMode", because CRI manager doesn't support logging now.
=> feature: namespace options and supplemental groups for cri manager

daemon/mgr/image_utils.go
We should be able to get the information of the image by full image ID like : 
```
[root@pouch-test pouch]# pouch image inspect sha256:5d9d6baef42b5850535f948d717bf71155bd4b352d392e5ca37ea95eaaac25d9
{
"Architecture": "amd64",
"Config": {
"Cmd": [
"sh"
],
.........
```
And this PR is just a quick workaround to make k8s + pouch could work ASAP, we should make it more elegant and systematic :)
=> bugfix: inspect image by image id with prefix

daemon/mgr/container.go, test/cli_run_test.go
fix: if cgroup-parent is a relative path will not work on host.
if cgroup-parent not specified both in client and daemon, the cgroupParent will be `default` (relative path). so if relative path not work on host , most of ci test will failed in cli_run_test.go.
but ci test like below works fine. it's wired
```
// TestRunWithCgroupParent tests running container with --cgroup-parent.
func (suite *PouchRunSuite) TestRunWithCgroupParent(c *check.C) {
// cgroup-parent relative path
testRunWithCgroupParent(c, "pouch", "TestRunWithRelativePathOfCgroupParent")
// cgroup-parent absolute path
testRunWithCgroupParent(c, "/pouch/test", "TestRunWithAbsolutePathOfCgroupParent")
}
```
so we should figure it out tomorrow @Letty5411
=> bugfix: cgroup-parent must be abs

apis/server/container_bridge.go, cli/top.go, ctrd/container.go, daemon/mgr/container.go, daemon/mgr/container_utils.go, daemon/mgr/container_utils_test.go, test/cli_top_test.go
finish top command
```
root@osboxes:test (zr/finish-top *) -> pouch top 44f675
UID     PID      PPID     C    STIME    TTY    TIME        CMD
root    28725    28714    0    3月14     ?      00:00:00    sh
```
=> feature: finish top interface

cri/stream/remotecommand/attach.go, cri/stream/remotecommand/exec.go, cri/stream/remotecommand/httpstream.go, cri/stream/server.go, daemon/containerio/container_io.go, daemon/containerio/options.go, daemon/containerio/streams.go, daemon/mgr/container.go, daemon/mgr/container_types.go, daemon/mgr/cri_stream.go, hack/cri-test/test-cri.sh
1. Implement exec and attach method of stream server.
2. Add a new backend (streams) to the pouch IO to satisfy the need of stream server.
=> feature: implement exec and attach method of stream server

cli/ps.go, test/cli_ps_test.go
This pr adds no-trunc flag for 'pouch ps' command.
fixes #903 
add flag 
```
[root@izj6c44nzox6sb97nzgmhyz ~]# pouch ps --no-trunc
Name   ID                                                                 Status        Created        Image                            Runtime
foo2   692c77587b38f60bbd91d986ec3703848d72aea5030e320d4988eb02aa3f9d48   Up 1 minute   1 minute ago   docker.io/library/redis:alpine   runc
foo    18592900006405ee64788bd108ef1de3d24dc3add73725891f4787d0f8e036f5   Up 1 minute   1 minute ago   docker.io/library/redis:alpine   runc
[root@izj6c44nzox6sb97nzgmhyz ~]# pouch ps --no-trunc -q
692c77587b38f60bbd91d986ec3703848d72aea5030e320d4988eb02aa3f9d48
18592900006405ee64788bd108ef1de3d24dc3add73725891f4787d0f8e036f5 …
```
=> feature: add no-trunc flag for 'pouch ps'

hack/make.sh, test/cli_run_test.go, test/cli_top_test.go
=> bugfix: fix lxc test error 

test/cli_top_test.go, test/util/util.go
fix cli_top_test PouchTopSuite failed in alios
=> test: fix cli_top_test test case

apis/server/volume_bridge.go, daemon/mgr/container.go, test/cli_volume_test.go
fix volume can be removed when using by container.
mark container's id into volume option "ref" when container attach volume, and remove option "ref" when container deatch volume.
create volume and run container.
```
CreatedAt:    2018-3-13 19:54:58
Mountpoint:   /data/volume/test
Name:         test
Scope:
Status:       map[mount:/data/volume sifter:Default size:1g]
a72c17c38b865d325dbf2372ff5b4e44eb618e8301d2e68fb86131612b2b348b
```
check volume option ref
```
{
"CreatedAt": "2018-3-13 19:54:58",
"Driver": "local",
"Labels": {
"backend": "local",
"hostname": "ubuntu"
},
"Mountpoint": "/data/volume/test",
"Name": "test",
"Status": {
"mount": "/data/volume",
"ref": "a72c17c38b865d325dbf2372ff5b4e44eb618e8301d2e68fb86131612b2b348b",
"sifter": …
```
=> bugfix: fix volume can be removed when using by container

test/cli_network_test.go
Due to issue #924 , the latest httpd image has problem which impact other tests.
In order to make CI works, skip this test. 
And use a stable tag later in test.
=> test: quick fix to skip pull httpd image

daemon/mgr/cri.go, daemon/mgr/cri_utils.go, hack/cri-test/test-cri.sh
First, we create a file /var/lib/pouch/sandbox/${sandbox id}/resolv.conf for every sandbox.
If the pod has configured the DNS configuration, then we write it to the file created above, else we copy the content of /etc/resolv.conf in host to it.
Finally we mount the file to every container's /etc/resolv.conf, then every container in the same pod will have the same DNS configuration :)
=> feature: dns configuration for cri manager

apis/plugins/ContainerPlugin.go, apis/plugins/DaemonPlugin.go, apis/server/container_bridge.go, apis/server/server.go, daemon/config/config.go, daemon/daemon.go, daemon/mgr/container.go, daemon/mgr/spec.go, daemon/mgr/spec_hook.go, docs/features/pouch_with_plugin.md, internal/generator.go, main.go
which support executing custom code at plugin points like start and stop in life cyle of container and daemon
features:
* at daemon start plugin point users can start dfget proxy and setup network plugins.
* before daemon stop users can stop the assist processes we started 
* when creating container users can change some attriubute passed in by request body, which enables we in our company convert parameters that used by old scheduling system to pouch style.
* before start a container users can add more pre-start hooks to runc which enables in our company we setup network qos rule and change some configration files in container  at this point
@allencloud @rudyfly @wangforthinker @Letty5411  PTAL
=> [feature] add plugin framework 

ctrd/image.go
fix: pull a image failed will lead to list images failed
```
root@osboxes:pouch (master) -> pouch images
Error: failed to get image list: {"message":"manifest sha256:bd13a0fc2aa205653032b3fef7895332bbbbc6fc9b0552e42d4b33b4a5481290: not found"}
```
fixes https://github.com/alibaba/pouch/issues/924
=> bugfix:  pull a image failed will lead to list images failed

INSTALLATION.md
I am using a VM on QingCloud to install Pouch. I found that when I copy the installation command to terminal of VM, it will paste some unexpected char, see:
```
root@i-qvufr3ii:~# sudo apt-get install \
> .apt-transport-https \
> .ca-certificates \
> .curl \
> .software-properties-common
```
In fact, `.` is out of expect.
So I update the installation.md to fix this to avoid unexpected behavior.
no
=> fix: make Installation more compatible

apis/server/image_bridge.go, apis/swagger.yml, apis/types/image_info.go, cli/image_list.go, ctrd/image.go, daemon/mgr/container.go, daemon/mgr/cri.go, daemon/mgr/cri_utils.go, daemon/mgr/image.go, daemon/mgr/image_test.go, pkg/reference/def.go, pkg/reference/parse.go, pkg/reference/parse_test.go, pkg/reference/regexp.go, test/api_image_inspect_test.go, test/cli_images_test.go, test/environment/cleanup.go
To keep consistency with Moby and implement cri methods, we need add repoTags and repoDigests fields to ImageInfo and remove the name field in ImageInfo correspondingly.
fixes part of #696
```
-># pouch images
dc8983e47a67   registry.hub.docker.com/library/busybox:1        710.74 KB
dc8983e47a67   registry.hub.docker.com/library/busybox:latest   710.74 KB
-># pouch image inspect dc
{
"Architecture": "amd64",
"Config": {
"Cmd": [
"sh"
],
"Env": [
],
"Image": "",
"Shell": null
},
"CreatedAt": "2018-01-24T04:29:35.590938514Z",
"ID": …
```
=> feature: add repoTags and repoDigests

apis/server/container_bridge.go, apis/swagger.yml, apis/types/container_config.go, cli/common_flags.go, cli/container.go, daemon/mgr/container_types.go, daemon/mgr/spec.go, daemon/mgr/spec_blkio.go, daemon/mgr/spec_namespace.go, pkg/quota/prjquota.go, pkg/quota/set_diskquota.go, test/cli_run_test.go, test/environment/env.go
Add disk quota for container's rootfs. You can use
"--disk-quota" to set rootfs quota when "pouch create" or
"pouch run"
fixes #805 
run container with disk quota for rootfs, such as:
```bash
Filesystem                Size      Used Available Use% Mounted on
overlay                   5.0G      4.0K      5.0G   0% /
tmpfs                    64.0M         0     64.0M   0% /dev
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                    64.0M         0     64.0M   0% /run
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                     1.9G         0      1.9G   0% /sys/firmware
tmpfs …
```
=> feature: add disk quota for container's rootfs

apis/swagger.yml, apis/types/system_info.go, cli/info.go, daemon/daemon.go, daemon/mgr/system.go, internal/generator.go
1. pretty print pouch info
2. add daemon listen address in info
3. add container count ing info
fixes: https://github.com/alibaba/pouch/issues/920
fix part of https://github.com/alibaba/pouch/issues/894
```
root@osboxes:pouch (zr/info-completion *) -> pouch info
Containers: 1
Running: 1
Paused: 0
Stopped: 0
Images:  0
Server Version: 0.3-dev
Storage Driver:
Logging Driver:
Cgroup Driver:
runc: <nil>
Kernel Version: 3.10.0-693.17.1.el7.x86_64
Operating System:
OSType: linux
Architecture:
HTTP Proxy:
HTTPS Proxy:
Debug: true
Labels: []
CPUs: 0
Total Memory: 0
Name:
ID:
LiveRestoreEnabled: false …
```
=> feature: pouch info print information enhance

apis/server/container_bridge.go, client/container.go, client/interface.go, ctrd/container.go, daemon/mgr/container.go, test/api_container_resize.go
finish resize interface:  resize the size of TTY running in the container
```
root@osboxes:wanziren -> pouch --width 10 --height 10 resize test1
root@osboxes:wanziren ->
```
=> feature: finish resize interface

pkg/quota/quota.go
check kernel version when setting disk quota driver, it should check
kernel > 4, instead of major > 4.
For example，the version of kernel is 3.10, and it supports group quota. you can test like this:
```
```
test will be succeed.
=> bugfix: fix check kernel version is wrong

cli/restart.go, main.go
Set flagSet := cmd.PersistentFlags() in main.go
fixes https://github.com/alibaba/pouch/issues/916
I know it works, but i still don't know why, may @allencloud , @skoo87 can tell me why :)
=> bugfix: fix pouchd cannot listen tcp address

apis/server/container_bridge.go, apis/server/router.go, cli/restart.go, client/container.go, client/interface.go, ctrd/container.go, daemon/mgr/container.go, test/api_restart_test.go, test/cli_restart_test.go
finish restart interface daemon part
=> feature: finish restart interface

apis/swagger.yml, apis/types/host_config.go, cli/common_flags.go, cli/container.go, daemon/mgr/spec.go, daemon/mgr/spec_cgroup_memory.go, daemon/mgr/spec_process.go, test/api_container_create_test.go, test/cli_create_test.go
add oom-score-adj and oom-kill-disable flag
=> feature: add oom flag

daemon/mgr/cri.go, daemon/mgr/cri_types.go
We should store the config of sandbox in cri manager.
Because we need some of them when stop or remove the pod and we couldn't get it directly from API.
=> feature: sandbox store for cri manager

daemon/mgr/network.go, network/mode/bridge/bridge.go, registry/auth.go, volume/core.go
1, rename upper-case  'Sirupsen' to 'sirupsen'
2, change import path `extra/libnetwork/Godeps/_workspace/src/github.com/Sirupsen/logrus` to `github.com/sirupsen/logrus`
fixes #949
=> bugfix: corrent the import path of logrus

daemon/mgr/network.go
revert commit: 8a70a80
libnetwork's logrus version is different from pouchd, so we need to
set libnetwork's logrus addintionly.
run pouchd and see network log format
also cc @faycheng 
=> bugfix: initialize the network log

cli/upgrade.go, client/container.go, daemon/mgr/container.go, pkg/utils/utils.go, pkg/utils/utils_test.go, test/cli_upgrade_test.go, test/utils.go, vendor/github.com/imdario/mergo/CODE_OF_CONDUCT.md, vendor/github.com/imdario/mergo/LICENSE, vendor/github.com/imdario/mergo/README.md, vendor/github.com/imdario/mergo/doc.go, vendor/github.com/imdario/mergo/map.go, vendor/github.com/imdario/mergo/merge.go, vendor/github.com/imdario/mergo/mergo.go, vendor/vendor.json
finish upgrade interface daemon part
```
root@osboxes:wanziren -> pouch upgrade --name test1 registry.hub.docker.com/library/busybox:latest
test1
```
* 1. Create a new container 
```
root@osboxes:pouch (zr/finish-upgrade) -> pouch inspect test2
{
"Args": null,
"Config": {
"Cmd": [
"sh"
],
"Env": [
],
"Image": "registry.hub.docker.com/library/busybox:latest",
"Shell": null
},
"Created": "2018-03-20T02:19:05.418084614Z",
"HostConfig": {
"NetworkMode": "bridge",
"RestartPolicy": {
"Name": "no"
},
"Runtime": "runc",
"BlkioDeviceReadBps": null,
"BlkioDeviceReadIOps": null,
"BlkioDeviceWriteBps": null,
"BlkioDeviceWriteIOps": null, …
```
=> feature: finish upgrade interface

.circleci/config.yml
We need a standard to validate all MarkDown files in Pouch project. After finding all related tools, I decided to try markdownlint (https://github.com/markdownlint/markdownlint).
We have already use travisCI to finish unit test and integration test, this time I try to take advantages of circleCI to finish this part.
In the future, I will support webhook of circleCI in @pouchrobot to make it info pull request circleCI error when it fails.
none
None
None
Currently I think the circleCI will fail with no doubt, since no one write markdown files according to [markdownlint](https://github.com/markdownlint/markdownlint).
cc @HusterWan @Letty5411
=> feature: add circleci to pouch to validate markdown files

ctrd/container.go, daemon/mgr/container.go
In ctrd/container.go we have two functions that are all to get pids in container, so we should delete one of them.
=> bugfix: rm dump ContainerPIDs method

.circleci/config.yml, CHANGELOG.md, CONTRIBUTING.md, FAQ.md, INSTALLATION.md, MAINTAINERS.md, README.md, ROADMAP.md, ctrd/README.md, docs/README.md, docs/architecture.md, docs/contributions/code_styles.md, docs/features/pouch_with_dragonfly.md, docs/features/pouch_with_lxcfs.md, docs/features/pouch_with_plugin.md, docs/features/pouch_with_prometheus.md, docs/features/pouch_with_rich_container.md, docs/features/pouch_with_runV.md, docs/features/pouch_with_tls.md, docs/kubernetes/pouch_with_cri_introduction.md, docs/kubernetes/pouch_with_cri_verification.md, docs/kubernetes/pouch_with_kubernetes_deploying.md, docs/test/debug_in_travis.md, docs/test/test.md, hack/package/README.md, volume/README.md
remove trailing space:  `%s/\s\+$//e`
replace tab to 4 spaces: `%s/\t/     /g`
rules: https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md
ignore errors:
~~MD002 - First header should be a top level header~~
~~MD003 - Header style~~
~~MD004 - Unordered list style~~
~~MD007 - Unordered list indentation~~
MD013 - Line length
~~MD014 - Dollar signs used before commands without showing output~~
MD024 - Multiple headers with the same content
~~MD026 - Trailing punctuation in header~~
MD029 - Ordered list item prefix
MD036 - Emphasis used instead of a header
~~MD038 - Spaces inside code span elements~~
=> doc:  fix errors checked by markdownlint

ctrd/client.go, ctrd/interface.go, daemon/daemon.go, daemon/mgr/container.go, daemon/mgr/image.go, docs/features/pouch_with_rich_container.md, internal/generator.go
=> refactor:pouch ctrd layer refactor

cli/main.go, cli/remount_lxcfs.go, hack/install_lxcfs_on_centos.sh, hack/make.sh, hack/package/rpm/build.sh, hack/package/rpm/service/lxcfs.service, lxcfs/lxcfs.go, main.go
To improve availability, lxcfs process should be managed by other process, such as systemd.
NONE
1. Remove the code of starting lxcfs in Pouchd. 
2. Check if the mount point of lxcfs is existed when starting Pouchd.
1. Make sure lxcfs is running, and the mount point of lxcfs is `/var/lib/lxcfs`
2. `pouchd --enable-lxcfs`
3. `pouch run -m 512M --enableLxcfs=true  registry.hub.docker.com/library/busybox:latest head -n 1 /proc/meminfo`
4. The output should be `524288 kB`
=> refactor: set lxcfs managed by systemd

daemon/mgr/image_utils.go, daemon/mgr/image_utils_test.go, pkg/reference/parse.go, pkg/reference/parse_test.go
since we add user defined registry and repo namespace, we split
image name complement process into two part, one is in pkg/reference,
the other is in daemon/mgr/image_utils.go.
=> refactor: modify logic in complement image fullname

apis/server/image_bridge.go, daemon/mgr/cri.go, daemon/mgr/cri_utils.go, daemon/mgr/image.go, hack/cri-test/test-cri.sh, test/cli_images_test.go
=> bugfix: pull image and get its status with RefDigest

daemon/mgr/image_test.go
add cases for testing `imageCache.get`
this pr is related to issue #975 & pr #973 .please don't merge it before merging #973 
make unit-test
=> test: add cases for testing imageCache.get

apis/server/server.go, cli/info.go, cri/service/cri.go, daemon/config/config.go, daemon/daemon.go, daemon/mgr/system.go, main.go, pkg/utils/utils.go, pkg/utils/utils_test.go, test/cli_upgrade_test.go
This PR adds labels for pouch daemon. This makes user can input labels like `pouchd --label a=b --label c=d`,
After that we could use pouch info to get the labels info:
```
Debug: false
Labels: 
a=b
c=d
CPUs: 0
Total Memory: 0
LiveRestoreEnabled: false
```
I also make the config passing as a pointer rather than copied struct instance.
none
none
none
none
This PR also needs adding daemon integation test.
=> feature: add daemon label for Pouch

client/client_mock_test.go, client/container.go, client/container_start.go, client/container_start_test.go
For more reliable client package which could be a golang SDK for Pouch developer, we should add more guarantee work on this. This PR adds mock test for the client package. 
In the code, we add a mock server in the client when unit testing.
none
none
none
none
=> test: add mock test for pouch package client

pkg/reference/parse.go, pkg/reference/parse_test.go, test/cli_pull_test.go
With this PR, we could pull image like "google/cadvisor:latest" correctly.
=> bugfix: handle image format 'namespace/name:tag' correctly

apis/server/router.go
=> bugfix: restart router miss versionMatcher

apis/server/router.go, test/api_container_restart_test.go
In the original test file test/api_restart_test.go, we have created containers with the same name, so I change one into another one.
In addition, I change the filename from `test/api_restart_test.go` to `test/api_container_restart_test.go`.
What is more, there is bug in router.go which is `r.Path(versionMatcher + "/containers/{id:.*}/restart").Methods(http.MethodPost).Handler(s.filter(s.restartContainer))`. In this line of code, we would make http server to get the container via `id` in the url path. While in code https://github.com/alibaba/pouch/blob/master/apis/server/container_bridge.go#L65, it is finding name using `name := mux.Vars(req)["name"]`. As a result, incompatibility happens. The gotten name will already be empty string …
=> fix: url mistake and test incorrectness

apis/swagger.yml, apis/types/container.go
This PR has fixed an incompatible issue in the pouch's API.
When communicating between Pouch client and daemon, we use json type to transfer data. While to be more compatible with moby's API, we need to make the transfer all the same. 
This fix some incompatibility.
this is related to https://github.com/alibaba/pouch/issues/977
none
none
none
=> fix: make container ID json name compatible

apis/server/router.go
I think without this PR, code adding routes to pouch server is very messy. 
This PR makes the routed adding much more simplified.
Typically, I change `r.Path(versionMatcher + "/containers/{name:.*}").Methods(http.MethodDelete).Handler(s.filter(s.removeContainers))` into `addRoute(r, http.MethodDelete, "/containers/{name:.*}", s.removeContainers)`.
And add a function which is named `addRoute`.
In code change `func (s *Server) filter(handler handler) http.HandlerFunc {`, I think there is no need to add `(s *Server)`.
none
none
none
=> refactor: make route code much more siplified

apis/swagger.yml, apis/types/system_info.go, cli/login.go, cli/logout.go, credential/file_store.go, credential/helpers.go, daemon/mgr/system.go
1. logout command will get default registry from system info
2. remove default registry with namespace library, make format
from registry.hub.docker.com/library to registry.hub.docker.com
=> feature: make logout use default registry

client/system.go, client/system_version.go, client/system_version_test.go
add mock test for system_version on client side
=> test: add mock test for system_version

apis/server/container_bridge.go, apis/swagger.yml, apis/types/mount_point.go, cli/common_flags.go, daemon/mgr/container.go, daemon/mgr/container_test.go, daemon/mgr/spec_volume.go, test/cli_volume_test.go
Add bind mode, it contains:
"ro/rw/dr/rr/z/Z/nocopy/private/rprivate/slave/rslave/shared/rshared"
common mode for all bind are: "ro/rw"，"z/Z" will be supported later,
"dr/rr/nocopy" just for volume, dr means direct replace, rr means random replace, nocopy will be supported later.
"private/rprivate/slave/rslave/shared/rshared" just for rootfs.
see test/cli_volume_test.go:TestVolumeBindReplaceMode
=> feature: add bind mode

apis/server/container_bridge.go, apis/swagger.yml, apis/types/mount_point.go, cli/common_flags.go, daemon/mgr/container.go, daemon/mgr/container_test.go, daemon/mgr/spec_volume.go, test/cli_volume_test.go
Add bind mode, it contains:
"ro/rw/dr/rr/z/Z/nocopy/private/rprivate/slave/rslave/shared/rshared"
common mode for all bind are: "ro/rw/z/Z",
"dr/rr/nocopy" just for volume,
"private/rprivate/slave/rslave/shared/rshared" just for rootfs.
=> feature: cherry-pich one commit

client/volume_create_test.go
fix logic error in volume create mock test
=> bugfix: fix logic error in volume create mock test

client/container.go, client/container_get.go, client/container_get_test.go
=> test:add container get test

daemon/mgr/cri.go
Actually I forget to specify the args of the cmd executed in the container, so fill it in this PR.
=> bugfix: specify both cmd and its args when create a container

apis/server/router.go, test/api_version_parameter_test.go
i check the moby api, it also support with or without version info in restful api url
Now we support both without version info in restful api url:
```
wanziren@osboxes:pouch (zr/fix-api-version) -> sudo curl /var/run/pouchd.sock http://0.0.0.0:8080/info
curl: (3) <url> malformed
{"Containers":200,"ContainersRunning":200,"Debug":true,"DefaultRegistry":"registry.hub.docker.com","DefaultRuntime":"runc","DriverStatus":null,"IndexServerAddress":"https://index.docker.io/v1/","KernelVersion":"3.10.0-693.17.1.el7.x86_64","Labels":[],"ListenAddresses":["tcp://0.0.0.0:8080","unix:///var/run/pouchd.sock"],"OSType":"linux","PouchRootDir":"/var/lib/pouch","SecurityOptions":null,"ServerVersion":"0.4.0-dev"}
```
and with version info in restful api url: …
=> bugfix: restful api url should support both with or without version info

cli/create.go, test/cli_create_test.go
change the output of container create
old way:
```
#pouch create --cpuset-cpus=0-1 --memory=4m --memory-swap 4m busybox top
container ID: c7f1fc453f6efbbd400e7d587d1277cc00a52efc893ee9c15cd2759cf71e049d, name: c7f1fc
now:
#pouch create --cpuset-cpus=0-1 --memory=4m --memory-swap 4m busybox top
c7f1fc453f6efbbd400e7d587d1277cc00a52efc893ee9c15cd2759cf71e049d
```
=> bugfix: change container create output

apis/server/volume_bridge.go, cli/volume.go, daemon/mgr/volume.go, test/cli_volume_test.go, volume/core.go, volume/core_util.go, volume/types/volume.go
Add options when using volume list, add volume driver into default
volume list information. Add list volumes function in volume core module.
fixes #921
listing volume format is "DRIVER VOLUME NAME", you can add some options, such as size and mountpoint, list volume with options like this:
```
DRIVER   VOLUME NAME     SIZE     MOUNT POINT
local    volume1                      ulimit   /mnt/local/volume1
local    test                             1g       /data/volume/test
local    volume-test               10g      /data/volume/volume-test
```
=> feature: add options when using volume list

client/registry_login.go
remove statuscode compare, since if login get unauthorized
error, http post will get a nil Response.
Fixes #1030.
=> bugfix: fix client login logic

.circleci/config.yml, Makefile
This pr move unit-test and check-code to circleCI, while others( integration test and cri test) still use travisCI.
This PR is based on @ZouRui89 's pr https://github.com/alibaba/pouch/pull/1039.
fixes #1008
=> feature: add circleci parrallism testing to split unit-test and code-check

daemon/mgr/network.go
pouch daemon will print duplicate error messages if fails to create endpoint.
so, i remove duplicate output in func `EndpointCreate`.
```
ERRO[2018-04-03 20:40:33.310004469] failed to create endpoint, err: service endpoint with name 169a941d already exists
ERRO[2018-04-03 20:40:33.310011239] failed to create endpoint: service endpoint with name 169a941d already exists
```
Thanks a lot for your reviews and comments.
=> bugfix: remove duplicate error msgs

cli/volume.go
modify volume inspect docs, it supports to inspect  multi-volumes,
and supports to inspect volume with format.
NONE
=> bugfix: modify volume inspect docs

.circleci/config.yml, .travis.yml, codecov.yml
This PR adds a codecov.yml file to ignore some test files. Since I think we do not need to test file 
```
- "extra/*"
- "vendor/*"
- "apis/types/*"
```
none
=> feature: restrict codecov.yml to ignore files

cli/image_inspect.go, cli/network.go
=> doc: fix  image inspect and network inspect command docs

daemon/mgr/container_types.go, daemon/mgr/cri.go
In order to be consistent with Docker:
1. User has specified container's entrypoint, don't use the cmd of image's configuration to fill it , even if it is empty.
2. User has not specified container's entrypoing, use the entrypoint of image's configuration to fill it, as well as cmd.
=> bugfix: distinguish cmd and entrypoint better

ctrd/client.go, ctrd/client_test.go, ctrd/container.go, ctrd/image.go, ctrd/snapshot.go, ctrd/watch.go, ctrd/wrapper_client.go, pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go
change ctrd containerd client to client pool to work around the grpc-go client concurrent streams limitation
now we can `pouch run` more then 100 containers
```
time for i in {1..200}; do echo $i; pouch run -d registry.hub.docker.com/library/busybox:latest sleep 100000; done
....
real	1m33.644s
user	0m11.269s
sys	0m2.299s
```
```
root@osboxes:pouch (zr/grpc-pool) -> ps aux | grep containerd-shim | wc -l
202
```
fixes https://github.com/alibaba/pouch/issues/766
=> feature: containerd grpc client pool

apis/swagger.yml, apis/types/container_config.go, cli/common_flags.go, cli/container.go, daemon/mgr/spec_annotations.go, test/cli_create_test.go, test/cli_run_test.go, test/cli_start_test.go
spec annotation flag pass all user defined runtime annotation to
runtime, note that whether the annotation will take effect depend
on your runtime inplement.
=> feature: add spec annotation flag

daemon/mgr/spec_hook.go
setup hook in advance to avoid panic if no prestart hook setup before this place
=> bugfix: setup hook in advance to avoid panic if no prestart hook setup before

test/cli_run_test.go, test/environment/env.go
=> test: modify hardcode test device /dev/sda

client/container.go, client/container_remove.go, client/container_remove_test.go, client/container_stop.go, client/container_stop_test.go
add container remove and stop test
=> test:add container remove and stop test

daemon/mgr/network.go, test/cli_network_test.go
add network inspection with network ID
```
> pouch network inspect ab65cbdb889a6b02
{
"Driver": "bridge",
"ID": "ab65cbdb889a6b0218aa075a0d56b6bd1d81ffd5dcc179ba9489f749c829ffa3",
"IPAM": {
"Config": [
{
"Gateway": "172.19.0.1",
"Subnet": "172.19.0.0/16"
}
],
"Driver": "default"
},
"Name": "bridge-0"
}
```
=> feature: inspect network by ID

Makefile
golint: not found has exit code 0
fixes https://github.com/alibaba/pouch/issues/1042
Remove the code leading to the failure.
```
bash-3.2$ golint ./... | grep -Fv 'vendor/' | grep -Fv 'extra' | grep -v ".pb.go:" | tee /dev/stderr
bash: golint: command not found
bash-3.2$ echo $?
0
bash-3.2$ golint ./... | grep -Fv 'vendor/' | grep -Fv 'extra' | grep -v ".pb.go:"
bash: golint: command not found
bash-3.2$ echo $?
1
```
remove golint file if it exists in your PATH
execute make lint
NA
=> golint: not found has exit code 1

daemon/mgr/container.go, pkg/utils/utils.go, pkg/utils/utils_test.go
if one image has multi tags, we will choose a tag name random(`list[0]`), that may not equals to input image name
fixes https://github.com/alibaba/pouch/issues/1001
there are some tricks:
pre-condition: if a image has multi tags:
```
root@osboxes:test (zr/revert-#997 *) -> pouch image inspect 50dcd054e8fe
{
"Architecture": "amd64",
"Config": {
"Cmd": [
"sh"
],
"Env": [
],
"Image": "",
"Shell": null
},
"CreatedAt": "2018-02-28T22:14:49.023807051Z",
"ID": "sha256:50dcd054e8fe6d4c2e7d34458ff09aa9f15a4bc747a8d6b741174c21340bd4db",
"Os": "linux",
"RepoDigests": [
"registry.hub.docker.com/library/busybox@sha256:2107a35b58593c58ec5f4e8f2c4a70d195 …
```
=> bugfix: container name not equals input params

daemon/mgr/spec_volume.go
By default, some paths like `/proc/sys` is readonly.
However if it is the privileged container, these paths should not be only readable.
=> bugfix: for privileged container, make some paths not be readonly

apis/swagger.yml, apis/types/exec_create_resp.go, apis/types/image_info.go, apis/types/network_create_resp.go, apis/types/network_info.go, apis/types/network_inspect_resp.go
We found that in Moby 1.12.6, lots of API communication uses json to wrap data. However, in Moby 1.12.6, almost all field ID is in json format `Id` which is one upper-case and the other is `lower-case`. While in the master code of Pouch, we use `ID` in json format. It will leads to incompatibility there. This PR tries to fix that.
fix one part of https://github.com/alibaba/pouch/issues/977
none
none
none
=> fix: make json ID be Id to be compatible

apis/swagger.yml, apis/types/resources.go, cli/common_flags.go, cli/container.go, daemon/mgr/spec.go, daemon/mgr/spec_cgroup_cpu.go, pkg/opts/cpu.go, test/cli_run_test.go, test/z_cli_daemon_test.go
This adds `--cpu-quota` and `--cpu-period` to container options.
`--cpu-period` should be in range [1000,1000000], and `--cpu-quota` should be in [1000, ∞).
fixes https://github.com/alibaba/pouch/issues/1031
none
none
none
=> feature: add cpu period and quota for containers

client/container.go, client/container_pause.go, client/container_pause_test.go, client/container_unpause.go, client/container_unpause_test.go
add container pause and unpause test
=> test:add container pause and unpause test

hack/kubernetes/allinone.sh
This script allows users to init kuberenete master node with pouch containers available.
Both Ubuntu and CentOS are supported.
NONE
After running this script, the user can then use 
```
kubeadm join ...
```
to test whether the master node has been successfully initiated.
=> feature: add allinone to deploy pouch as available container to kubernetes

ctrd/client.go, daemon/mgr/image.go, pkg/errtypes/errors.go, pkg/quota/prjquota.go, test/environment/env.go, test/util_api.go
fix some issues in go report, include ineffectual assignments and typos etc
fix #964
=> fix: issues with go report

test/daemon/daemon.go, test/util_daemon.go, test/z_cli_daemon_test.go
Refine the daemon test framework.
=> test: refine daemon framework

daemon/mgr/cri.go, daemon/mgr/cri_stream.go
=> bugfix: loop execInspect to get result for cri manager's exec method

cli/network.go, cli/volume.go
In the original code, parent command of Pouch has no execution function which could be tell users error happens.
I wish to add this into integration test, however I have no idea how to check exit code in test framework. 
@sunyuan3 
fix #1076 
add a RunE function in parent command.
```
root@ubuntu:~/go/src/github.com/alibaba/pouch# echo $?
1
root@ubuntu:~/go/src/github.com/alibaba/pouch#
root@ubuntu:~/go/src/github.com/alibaba/pouch#
root@ubuntu:~/go/src/github.com/alibaba/pouch# ./pouch network sdfghjk dfghj
Error: command 'pouch network sdfghjk' does not exist.
Please execute `pouch network --help` for more help
root@ubuntu:~/go/src/github.com/alibaba/pouch# echo $?
1
root@ubuntu:~/go/src/github.com/alibaba/pouch# ./pouch network …
```
=> fix: make pouch network non-existent return exit code 1

ctrd/image_proxy_util.go, daemon/daemon.go, pkg/quota/prjquota.go, pkg/utils/utils.go, test/util_api.go
1. fix the **gocyclo** part of goreport 
2. fix bug: the no-proxy's environment name should be 'NO_PROXY' or 'no_proxy', not 'noProxy'.
fixes #964
=> fix: gocyclo issues in go report

client/container.go, client/container_get_test.go, client/container_list_test.go, client/container_pause_test.go, client/container_remove_test.go, client/container_rename_test.go, client/container_resize.go, client/container_resize_test.go, client/container_restart.go, client/container_restart_test.go, client/container_start_test.go, client/container_unpause_test.go, client/container_update_test.go, client/image_inspect_test.go, client/image_list_test.go, client/image_pull_test.go, client/image_remove_test.go, client/network_create_test.go, client/network_inspect_test.go, client/network_list_test.go, client/network_remove_test.go, client/registry_login_test.go, client/system_info_test.go, client/system_ping_test.go, client/system_version_test.go, client/volume_create_test.go, client/volume_inspect_test.go, client/volume_list_test.go, client/volume_remove_test.go
add container resize and restart test
=> test:add container resize and restart test

test/daemon/daemon.go, test/util_daemon.go, test/z_cli_daemon_test.go
Add deamon tests for ：
1. label
2. configure file
=> test: add tests for label and config file in daemon

main.go
not all type can be casting to string
Fixes: #1083
=> bugfix: fix interface casting error

client/container.go, client/container_create.go, client/container_create_test.go
=> test:add container create test

daemon/mgr/container.go
For Go Report. daemon/mgr/container.go has a golint issue. Remove if and just return err.
fixes one part of #964
=> refactor: refactor return err for golint

daemon/mgr/container_utils.go, daemon/mgr/container_utils_test.go, daemon/mgr/cri_utils.go, daemon/mgr/spec.go, daemon/mgr/spec_linux.go, hack/build, hack/cri-test/test-cri.sh, vendor/github.com/opencontainers/selinux/LICENSE, vendor/github.com/opencontainers/selinux/go-selinux/label/label.go, vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go, vendor/github.com/opencontainers/selinux/go-selinux/selinux.go, vendor/github.com/opencontainers/selinux/go-selinux/xattrs.go, vendor/vendor.json
With this PR, we could enable one of the security context --- SELinux, if it's configured in CRI.
=> feature: selinux for cri manager

daemon/mgr/network.go
Removing ip mask in Networks.IPAddress when inspecting a container.
Wrong format: "IPAddress": "172.17.0.2/24", change to ""IPAddress":
"172.17.0.2"
fixes #1079
=> bugfix: remove ip mask in Networks.IPAddress

apis/server/image_bridge.go, apis/server/image_bridge_test.go
when using swarm to pull an image, it post a request with a param named fromImage, which already include a tag, then we shouldn't append a 'latest' to it.
fixes #1109
=> bugfix: do not append latest to image name having a tag already

cli/info.go, daemon/mgr/system.go
This pr enhance the output of 'pouch info' by adding the info of http proxy(image proxy).
fixes one part of #1096 
start pouch like 
```pouchd --image-proxy=http://127.0.0.1:5678```
then
```
$ pouch info
Containers: 1
Running: 1
Paused: 0
Stopped: 0
Images:  0
ID:
Name:
Server Version: 0.3-dev
Storage Driver:
Logging Driver:
Cgroup Driver:
runc: <nil>
Kernel Version: 3.10.0-693.17.1.el7.x86_64
Operating System:
OSType: linux
Architecture:
HTTP Proxy: http://127.0.0.1:5678
HTTPS Proxy:
Debug: true
Labels: []
CPUs: 0
Total Memory: 0
LiveRestoreEnabled: false
Daemon Listen Addresses: …
```
=> feature: add image proxy info in 'pouch info'

cli/image_inspect.go, cli/inspect.go, cli/inspect/inspector.go, cli/inspect/inspector_test.go, cli/network.go, cli/volume.go, pkg/utils/utils.go, test/cli_create_test.go, test/cli_images_test.go, test/cli_inspect_test.go, test/cli_network_test.go, test/cli_ps_test.go, test/cli_rich_container_test.go, test/cli_run_test.go, test/cli_update_test.go, test/cli_upgrade_test.go, test/cli_volume_test.go, test/z_cli_daemon_test.go
make inspect output an array
fixes: #1071
=> bugfix: make inspect output an array

daemon/mgr/network.go
del endpoint after failing to create endpoint
=> bugfix: del endpoint after failing to create endpoint

daemon/config/config.go, daemon/daemon.go, hack/cri-test/test-utils.sh, main.go
With this PR, the CRI service of pouch will be off by default.
If we want to enable it, we could start pouchd like:
```
pouchd --enable-cri
```
fixes #1114
=> feature: add a flag of pouchd to specify whether enable CRI

daemon/mgr/cri.go
With this PR, cri manager could handle image which should be pulled with auth.
=> feature: image auth for cri manager

cli/cli.go, cli/main.go, cli/run.go, cli/start.go, daemon/mgr/container.go, test/cli_network_test.go, test/cli_run_test.go, test/cli_start_test.go, test/z_cli_daemon_test.go
Fixes: #1075
1. make container exit with real exit code
2. fix stop wait after stdin close
3. fix some test case hang, such as this will hang forever, miss detach flag.
```
-       command.PouchRun("run", "--name", name, "-m", "512M", "--enableLxcfs=true",
+       command.PouchRun("run", "-d", "--name", name, "-m", "512M", "--enableLxcfs=true",
```
4. fix container exit code not equal 0 after container start
=> bugfix: make container exit with real exit code

ctrd/image.go, daemon/mgr/cri.go, hack/cri-test/test-cri.sh
Now we get image ID by calculating ourself, unfortunately it's wrong.
For example `busybox:1-uclibc` and `busybox:1` should have same ID,  however:
```
[root@pouch-test pouch]# pouch images
IMAGE ID       IMAGE NAME                                         SIZE
58af67620523   registry.hub.docker.com/library/busybox:1          710.83 KB
b2e60002262d   registry.hub.docker.com/library/busybox:1-uclibc   709.90 KB
```
So with this PR we get it directly from containerd then:
```
[root@pouch-test pouch]# pouch images
IMAGE ID       IMAGE NAME                                         SIZE
8ac48589692a   registry.hub.docker.com/library/busybox:1          710.83 KB
8ac48589692a   registry.hub.docker.com/library/busybox:1-uclibc   709.90 KB
```
=> bugfix: we should get image ID from containerd

main.go
make TLS config params can be setup in the config file which introduce by falg `--config-file`
@Ace-Tang
=> make TLS config params can be setup in the file

apis/server/container_bridge.go, apis/swagger.yml, apis/types/container_json.go, apis/types/snapshotter_data.go, ctrd/interface.go, ctrd/snapshot.go, daemon/mgr/container.go, daemon/mgr/container_types.go
add snapshotter info into container json
since graphdriver has been replace by snapshotter, so i also rename the GraphDriver to Snapshotter in pouch
fixes #1011 
```
root@osboxes:wanziren -> pouch inspect -f "{{.GraphDriver.Data.UpperDir}}" test
/var/lib/pouch/containerd/root/io.containerd.snapshotter.v1.overlayfs/snapshots/1809/fs
```
now we has snapshotter info in container json
```
"Snapshotter": {
"Data": {
"MergedDir": "/var/lib/pouch/containerd/state/io.containerd.runtime.v1.linux/default/6933c23039432c5a1b1f88c6d94c39fe8fd88943121ac7af419b2c42a2e440fe/rootfs",
"UpperDir": "/var/lib/pouch/containerd/root/io.containerd.snapshotter.v1.overlayfs/snapshots/1809/fs"
},
"Name": "overlayfs"
},
```
```
root@osboxes:wanziren -> pouch inspect …
```
=> feature: add snapshotter info into container json

apis/swagger.yml, apis/types/container_config.go, cli/common_flags.go, cli/container.go, daemon/mgr/container.go, daemon/mgr/spec_blkio.go, pkg/quota/grpquota.go, pkg/quota/prjquota.go, pkg/quota/quota.go, pkg/quota/set_diskquota.go, pkg/quota/type.go, test/cli_network_test.go, test/cli_run_test.go
Add diskquota support regular expression.
NONE
We can use ```pouch run --disk-quota="key=value"``` to set quota for container. This pr can make it support to use regular expression key, such as: --disk-quota=".*=1g", it means all the quota of mount points are '1g', the priority of key '.*' is the lowest. If it has no 'key', just have  'value', such as: ```--disk-quota=1g```, it means the quota of rootfs is 1g. If the mountpoint is a volume, the quota of volume is base on volume's size, the disk-quota is not take effect on a volume.
The example is test case: ```TestRunWithDiskQuotaRegular```
create a volume with size limit: 256m 
```
Name:         diskquota-volume
Scope:
Status:       map[mount:/data/volume sifter:Default size:256m]
CreatedAt:    2018-4-8 14:18:35 …
```
=> feature: add diskquota support regular expression

daemon/daemon.go, pkg/system/machine.go, pkg/system/network.go, test/api_daemon_update_test.go
This PR adds two default labels in pouchd daemon:
* node_ip: this is node ip which is fetched by `hostname -i`;
* serial number: machine's serial number
none
```
root@ubuntu:~/go/src/github.com/alibaba/pouch# pouch info
Containers: 8
Running: 8
Paused: 0
Stopped: 0
Images:  0
ID:
Name: ubuntu
Server Version: 0.4.0-dev
Storage Driver: overlayfs
Logging Driver:
Cgroup Driver:
runc: <nil>
Kernel Version: 4.4.0-87-generic
Operating System: "Ubuntu 16.04.3 LTS"
OSType: linux
Architecture:
HTTP Proxy:
HTTPS Proxy:
Debug: false
Labels:
node_ip=127.0.1.1
SN=0
CPUs: 1
Total Memory: 1.953 GiB …
```
=> feature: add node ip and sn into daemon labels

test/cli_run_test.go, test/environment/env.go
=> test: add lxcfs binary check

cli/container.go, cli/run.go, cli/start.go, test/cli_run_test.go
add rm flag in pouch run command
=> feature: add rm flag in pouch run command

daemon/mgr/container.go
=> bugfix: fix daemon panic when meta snapshotter is nil

cli/common_flags.go, cli/container.go, daemon/mgr/container.go, pkg/opts/mountpoint.go, pkg/opts/mountpoint_test.go, test/cli_run_test.go
Add volumes-from for container, container can use the volumes of another
containers. The format is `<containerID>[:mode]`
fixes #463
1. create old container with volume
```
CreatedAt:    2018-4-16 14:46:18
Mountpoint:   /mnt/local/test-volume
Name:         test-volume
Scope:
Status:       map[sifter:Default]
6203151a7134ae9305cbeddba90c874d76eff9bf345cc30a9e34277d89a4d7d4
```
2. stop old container
```
```
3. create new container with old container's volume
```
6821c74073fb6a2262b1c00aa2ceaabc47463e06f4e6e718e8827889afd83492
```
=> feature: add volumes-from for container

daemon/mgr/container.go, daemon/mgr/container_types.go, pkg/collect/safe_map.go, pkg/collect/safe_map_test.go
add gc to clean unused exec processes
add gc to clean unused exec processes, gc process will be triggered every 5 minutes.
=> feature: gc unused exec processes

cri/config.go, daemon/mgr/cri.go, docs/kubernetes/pouch_with_kubernetes_deploying.md, main.go
If we want to use other images of infra container other than default "k8s.gcr.io/pause-amd64:3.0",
we should specify pouchd's configuration like "pouchd --enable-cri --sandbox-image XXX"
fixes #1158
=> bugfix: make infra image configurable

daemon/config/config.go, daemon/config/config_test.go, main.go, pkg/utils/utils.go, pkg/utils/utils_test.go, test/z_cli_daemon_test.go
move daemon config code from main.go to daemon/config/config.go,
suporrts to resolve config file contains nested object.
for eg, resolve file
```
map[string]interface{}{
"a": "a",
"b": "b",
"c": "c",
"iter1": map[string]interface{}{
"i1": "i1",
"i2": "i2",
},
"iter11": map[string]interface{}{
"ii1": map[string]interface{}{
"iii1": "iii1",
"iii2": "iii2",
},
},
}
```
to
```
map[string]interface{}{
"a":    "a",
"b":    "b",
"c":    "c",
"i1":   "i1",
"i2":   "i2",
"iii1": "iii1",
"iii2": "iii2",
}
```
=> refactor: refactor config file resolve

INSTALLATION.md, hack/make.sh, hack/package/deb/Makefile, hack/package/rpm/build.sh, vendor/github.com/containerd/containerd/Makefile, vendor/github.com/containerd/containerd/RUNC.md, vendor/github.com/containerd/containerd/cio/io.go, vendor/github.com/containerd/containerd/cio/io_unix.go, vendor/github.com/containerd/containerd/cio/io_windows.go, vendor/github.com/containerd/containerd/content/helpers.go, vendor/github.com/containerd/containerd/contrib/seccomp/seccomp_default.go, vendor/github.com/containerd/containerd/dialer/dialer.go, vendor/github.com/containerd/containerd/fs/diff.go, vendor/github.com/containerd/containerd/image.go, vendor/github.com/containerd/containerd/oci/spec_opts_unix.go, vendor/github.com/containerd/containerd/rootfs/diff.go, vendor/github.com/containerd/containerd/sys/socket_unix.go, vendor/github.com/containerd/containerd/vendor.conf, vendor/github.com/containerd/containerd/version/version.go, vendor/vendor.json
Upgrade containerd to make the pouchd stable.
The version of containerd will be changed from v1.0.0 to v1.0.3
fixes #1141 
```
$ govendor fetch github.com/containerd/containerd@v1.0.3
```
It's the dependency upgrade. I have tested `pouch run -it busybox /bin/sh` in local and it passed.
It should be covered by CI.
NONE
=> feature: upgrade containerd version to v1.0.3

daemon/mgr/container.go
Setting quota-id without setting disk-quota, it should be failed and
returns error.
```
Error: failed to run container: {"message":"failed to set mount point disk quota: invalid argument, set quota-id without disk-quota"}
```
=> bugfix: fix set quota-id without disk-quota

daemon/mgr/container.go, test/cli_run_test.go
old container has bind directory into container, such as "-v /tmp:/tmp",
when use 'volumefrom' to create new container, it will be failed when
setup volumes.
NONE
=> bugfix: failed to create 'volumefrom' container

ctrd/utils.go, daemon/mgr/container.go, daemon/mgr/volume.go, storage/volume/core_util.go, test/cli_run_test.go, test/cli_volume_test.go, test/util_daemon.go
parse volumes from image, so pouchd will create a volume that is defined
in image automatically.
In addition, if volume has no size, the disk quota will set to volume.
NONE
run a container with image what have volume
```
Filesystem      Size  Used Avail Use% Mounted on
overlay         5.0G   16K  5.0G   1% /
tmpfs            64M     0   64M   0% /dev
shm              64M     0   64M   0% /dev/shm
tmpfs            64M     0   64M   0% /run
/dev/sdb2       5.0G   16K  5.0G   1% /var/lib/mysql
tmpfs           2.0G     0  2.0G   0% /sys/firmware
tmpfs           2.0G     0  2.0G   0% /proc/scsi
```
=> feature: parse volumes from image

daemon/mgr/container.go
=> bugfix: update SafeMap item just call Put, no need call Remove

daemon/mgr/container_types.go, daemon/mgr/container_types_test.go, test/cli_ps_test.go, test/cli_stop_test.go
record stopped container last exit time, like
```
$ pouch ps
Name     ID       Status                     Created          Image            Runtime
356700   356700   stopped (137) 36 minutes   36 minutes ago   busybox:latest   runc
```
=> feature: record container last exit time

daemon/mgr/cri.go
fixes problem mentioned in #1144
=> bugfix: evaluate finish time of container in CRI correctly

daemon/mgr/container.go, test/api_container_rename_test.go
because when doing rename, user may specify container id instead of container name, in the processing of clean the old name from `nameToId` cache, we cannot suppose that the `oldName` is the name of the old container. we use the real name to clean the cache.
fixes #1174
=> bugfix: if user rename container with id use the real name to clean the cache

cli/logs.go
Option `LogConfig` is omitempty in config. That means we allow `c.HostConfig.LogConfig` is nil. 
There is no need to check the log type, we don't use it now in `log` sub command, maybe in the furture.
Fix #1075 
Fix #1072
=> remove log format type check

daemon/mgr/container.go, docs/kubernetes/pouch_with_kubernetes_deploying.md
Fix container start failed problem: if start failed once, all start action will fail because of network endpoint not deleted.
fixes https://github.com/alibaba/pouch/issues/1068
=> bugfix: container cannot start after first start failed

docs/features/pouch_with_runV.md
Fix minor mistakes in pouch_with_runV.md docs. The runV build path should be `$Home/go/src/github.com/hyperhq`
=>  fix minor mistakes in pouch_with_runV.md docs

ctrd/container.go, daemon/containerio/cio.go, daemon/containerio/container_io.go, daemon/containerio/options.go, daemon/mgr/container.go, daemon/mgr/cri.go, test/cli_network_test.go, test/cli_ps_test.go, test/cli_restart_test.go, test/cli_run_test.go, test/cli_start_test.go, test/cli_stop_test.go, test/cli_top_test.go, test/cli_unpause_test.go, test/cli_update_test.go, test/cli_upgrade_test.go, test/z_cli_daemon_test.go
Before this PR, we open the stdin of container IO by default.
Actually it's wrong, we should close it by default. 
Unless user specify like `pouch run -i ....`, then we should open it.
=> feature: refactor exec to enable configure stdin

.circleci/config.yml, Dockerfile
Yes. The CI is not happy right now.... Use `go get -u golang.org/x/lint/golint`...
=> bugfix: reset to `go get -u golang.org/x/lint/golint`

apis/server/network_bridge.go, apis/server/router.go, daemon/mgr/container.go
This PR fix some problem:
1. function named: %s/DisconnectContainerFromNetwork/Disconnect
2. refactor: if store container info to disk failed return errors
=> refactor: if store container info to disk failed return errors

main.go
make logrus detect whether output with color instead of always output with color.
when redirect pouchd output a file, avoid outputting message like `ESC[34mINFOESC[0m` to the file.
=> bugfix: make logrus detect whether output with color

daemon/mgr/container.go, test/cli_stop_test.go
make stopping non-running container valid
make this be compatible  with moby's api.
fix #1207
=> fix: make stopping non-running container valid

apis/swagger.yml, apis/types/resources.go
Remove the `DiskQuota` useless field from Resource
None
None
None
=> bugfix: remove the DiskQuota useless field from Resource

apis/swagger.yml, apis/types/update_config.go, cli/update.go, daemon/mgr/container.go, test/cli_update_test.go
1. remove update image: if user want to change image of a container, he/she should use upgrade interface
2. fix update env bugs
fixes https://github.com/alibaba/pouch/issues/1188
=> bugfix: remove update image and fix bugs when update env

test/cli_update_test.go
=> test: fix ci fail cause container run and stop

pkg/bytefmt/bytefmt.go, pkg/bytefmt/bytefmt_test.go, test/cli_volume_test.go
fix volume size without unit, such as size=1024 will be failed.
NONO
check the size has unit or not, if it has no unit size, we will add "B" at the end of size.
```
Mountpoint:   /data/pouch/volume/test
Name:         test
Scope:
Status:       map[sifter:Default size:1048576 mount:/data/pouch/volume]
CreatedAt:    2018-4-25 21:28:44
```
=> bugfix: fix volume size without unit

daemon/mgr/container.go, test/cli_run_test.go
#./docker -H unix:///run/pouchd.sock inspect eff3a2846686
[]
json: cannot unmarshal string into Go value of type struct {}
fixes https://github.com/alibaba/pouch/issues/1211
```
root@osboxes:test (zr/fix-volume-struct *) -> docker -H unix:///run/pouchd.sock inspect test2
[
{
"Args": null,
"Config": {
"Cmd": [
"/bin/bash"
],
"Env": [
],
"Hostname": "osboxes",
"Image": "registry.hub.docker.com/library/ubuntu:14.04",
"Shell": null,
"Volumes": {
"/mnt": null
}
},
"Created": "2018-04-25T11:50:50.324220921Z",
"GraphDriver": {
```
=> bugfix: Volume info of inspect output is incompatible with Moby API

daemon/mgr/container.go
Add parse Config.Volumes when create container.
NONE
=> bugfix: add parse Config.Volumes when create container

daemon/mgr/image.go
add default tag ":latest" when using `pouch rmi` to remove untagged container images.
fixes #1104
just use the same way as `pouch pull`
frist, pull some images:
```
pouch pull library/busybox
pouch pull library/hello-world
```
then, just remove them:
```
pouch rmi library/busybox library/hello-world
```
=> bugfix: add default tag ":latest" when using pouch rmi to remove untagged container images.

cli/update.go, ctrd/utils.go, daemon/mgr/container.go, test/cli_update_test.go
Support  all parameters of update interface in alidocker
=> feature: support update container's cpu-period

apis/swagger.yml, apis/types/update_config.go, cli/update.go, daemon/mgr/container.go
fix  update compatibility with  alidocker
alidocker update container label is `[]string`
pouch `UpdateConfig.Label` is `map[string]string`
=> bugfix: update label compatibility with alidocker

cli/exec.go, ctrd/container.go, hack/cri-test/test-cri.sh, test/api_container_exec_inspect_test.go, test/api_container_exec_start_test.go, vendor/github.com/docker/docker/pkg/stdcopy/stdcopy.go, vendor/vendor.json
The docker exec api uses custom stream bytes if the tty is false.
In order to align with docker API, we need to use
github.com/docker/docker/pkg/stdcopy package to modify stream bytes.
Align with docker v1.24 API. As we known, the docker API has custom stream bytes when the client doesn't set tty. More information is here: https://github.com/moby/moby/blob/master/client/container_attach.go#L10-L33
Fix #1221
use `github.com/docker/docker/pkg/stdcopy` to wrap the `io.Writer`. 
```
➜  docker ./docker -H unix:///var/run/pouchd.sock exec -i 05e7c1b71cf63137fbac112f5ab2c5a6d9002c938aca304e259507b9c4aec66c ls
Unrecognized input header: 98
```
after fix:
```
➜  docker ./docker -H unix:///var/run/pouchd.sock exec -i …
```
=> bugfix: align with docker v1.24 API

cli/run.go
`setRawMode` is used to terminal case. If the shell is non-interactive or non-terminal, we should not set the raw mode for the input.
None
check tty before set the raw mode
we need to set the shell in no-interactive mode, please use the following the script:
```
#!/bin/bash
cat >test <<'EOF'
set +i # set non-interactive
pouch run -i busybox:latest echo test
EOF
echo 'running bash -i <test'
bash -i <test
```
before this change:
```
➜  /tmp sh ./test-interactive
running bash -i <test
root@ubuntu-xenial:/tmp# set +i # set non-interactive
root@ubuntu-xenial:/tmp# pouch run -i busybox:latest echo test
Error: failed to set raw mode
root@ubuntu-xenial:/tmp# exit
```
after this change:
```
➜  /tmp sh ./test-interactive
running bash -i <test …
```
=> bugfix: setRawMode can only be set when the user set tty

apis/swagger.yml, apis/types/update_config.go, cli/update.go, daemon/mgr/container.go, storage/quota/quota.go, storage/quota/set_diskquota.go
Update API should support update container diskquota
=> feature: update restful api support update container diskquota

cli/cli.go
add client debug flag, so we can get more debug info when running
pouch commands
Signed-off-by: Chuanyun Li <lcy041536@gmail.com>
Add debug flag in client. So we can get more debug infos when running pouch commands
Add debug flag in client. So we can get more debug infos when running pouch commands
```
root@ubuntu-1:~# ./pouch/pouch volume create -D -n volume2  -l like=football -s host=ubuntu1
INFO[0000] start client at debug level                  
DEBU[2018-04-27 11:41:50.937401046] create a volume: volume2, options: [], labels: [like=football], selectors: [host=ubuntu1] 
Labels:       map[backend:local hostname:ubuntu-1 like:football]
Mountpoint:   /mnt/local/volume2
Name:         volume2
Scope:        
Status:       map[sifter:Default]
CreatedAt:    2018-4-27 11:41:50
Driver: …
```
=> feature: add client debug flag

hack/vagrant/.gitignore, hack/vagrant/README.md, hack/vagrant/Vagrantfile, hack/vagrant/bootstrap.sh
add vagrant environment for development
https://github.com/alibaba/pouch/issues/1243
=> feature: add vagrant environment for development

docs/kubernetes/pouch_with_kubernetes_deploying_aliyun.md
deploy kubernetes with pouch powerd by aliyun
=> docs: deploy kubernetes with pouch powerd by aliyun

daemon/mgr/spec_hook.go, storage/quota/quota.go
Update env of running container failed: Invalid cross-device link, caused by not set overlayfs `work` diskquota
wrong container's disk quota:
```
[root@e19h16400.et15sqa /home/ziren.wzr]
#lsattr -p /home/t4/pouch/containerd/root/io.containerd.snapshotter.v1.overlayfs/snapshots/170
0 --------------e---- /home/t4/pouch/containerd/root/io.containerd.snapshotter.v1.overlayfs/snapshots/170/work
16777514 --------------e---P /home/t4/pouch/containerd/root/io.containerd.snapshotter.v1.overlayfs/snapshots/170/fs
```
normal container's disk quota, `workdir` disk quota is 0:
```
[root@e19h16400.et15sqa /home/ziren.wzr]
#lsattr -p /home/t4/pouch/containerd/root/io.containerd.snapshotter.v1.overlayfs/snapshots/171
16777514 --------------e---P …
```
=> bugfix: set container env failed Invalid cross-device link

cli/inspect.go
Should show QuotaId instead of QuotaID.
Align with existing system: change `QuotaID` to `QuotaId`.
NONE
```
➜  pouch create --disk-quota=1g --quota-id=123 busybox:latest
40601016760b939592c66c0f0c7600c22285923273b95f1a0ab0138399662cc7
➜  pouch inspect 40601016760b939592c66c0f0c7600c22285923273b95f1a0ab0138399662cc7 | grep Quota
"DiskQuota": {
"QuotaId": "123"
```
=> bugfix: align with existing system

daemon/mgr/container.go
alidocker use `Labels["DiskQuota"]` to record container diskquota, so when update diskquota, we also need to update the value of `Labels["DiskQuota"]`
=> bugfix: compability with alidocker when update container diskquota

daemon/mgr/volume.go, storage/volume/modules/tmpfs/tmpfs.go
The tmpfs volume is now mounted in the /etc/docker/plugins/tmpfs. It
should be mounted in /mnt/tmpfs
The tmpfs volume is now mounted in the /etc/docker/plugins/tmpfs. It
should be mounted in /mnt/tmpfs
fix some misspells
NONE
1. create tmpfs volume
```
root@ubuntu-1:~# pouch volume create -d tmpfs -n tmp_vol1
CreatedAt:    2018-4-28 11:17:36
Driver:       tmpfs
Mountpoint:   /mnt/tmpfs/tmp_vol1
Name:         tmp_vol1
Scope:        
Status:       map[sifter:Default]
```
2. run container with the volume
```
root@ubuntu-1:~# pouch run -v tmp_vol1:/test -d reg.docker.alibaba-inc.com/redis
3a841472c493934885cbed99dd56c75ac48fbfaa32a9f3626e5e9701d5cb82a0
```
3. see the mount path
```
root@ubuntu-1:~# mount |grep tmp_vol1
shm on …
```
=> bugfix: fix the mount path of tmpfs volume and some misspells

pkg/utils/mount.go
In some linux releases, the mountpoint is not under /usr/bin dir, which
causes the failure of tmpfs detachment. So we only use the mountpoint,
which is in the system path
In some linux releases, the mountpoint is not under /usr/bin dir, which
causes the failure of tmpfs detachment. So we only use the mountpoint,
which is in the system path
fixes #1252
=> bugfix: fix mountpoint binary not found error

hack/make.sh
Signed-off-by: u2takey <u2takey@gmail.com>
facilitate make.sh build by checking install status before do install binaries
=> refactor: facilitate make.sh build

daemon/mgr/container.go, test/api_container_restart_test.go, test/api_container_stop_test.go, test/cli_restart_test.go, test/cli_stop_test.go, test/z_cli_daemon_test.go
can't stop a paused container
after restart pouch, can't unpause a paused container
fixes #1268
* can't stop a paused container
* after restart pouch, can't unpause a paused container
* when stop the container, if the container is paused, allow it
* restore a paused container when start the pouchd daemon
=> bugfix: can't stop a paused container

test/cli_restart_test.go
restart_paused_container ci failed
```
FAIL: /go/src/github.com/alibaba/pouch/test/cli_restart_test.go:63: PouchRestartSuite.TestPouchRestartPausedContainer
/go/src/github.com/alibaba/pouch/test/cli_restart_test.go:68:
command.PouchRun("pause", name).Assert(c, icmd.Success)
/go/src/github.com/alibaba/pouch/vendor/github.com/gotestyourself/gotestyourself/icmd/command.go:61:
t.Fatalf("at %s:%d - %s\n", filepath.Base(file), line, err.Error())
... Error: at cli_restart_test.go:68 - 
Command:  /usr/local/bin/pouch pause TestPouchRestartPausedContainer
ExitCode: 1
Error:    exit status 1
Stdout:   
Stderr:   Error: failed to pause container TestPouchRestartPausedContainer: {"message":"container's status is not running: exited"}
```
=> bugfix:  restart_paused_container ci failed

ctrd/container.go
when we start a exec process in containerd, we should do
delete operate after exec process exit, to delete exec pid file.
fix exec process pid leak, like: 
```
root@www:/var/lib/pouch/containerd# ls state/io.containerd.runtime.v1.linux/default/46b849a76f28b195a086c35ac1fd4006f9010135e38607e6882e813c7222f2d9
0cdf0d112068e221068d2fcaa578f2cc7dc5803616538be048415c5c48ce55c5.pid  93c116b3f7200d025d251be92597f50fa4da8f4b9bc8837d92f8a65ffa799dae.pid  init.pid
5247e2472a6bce3eb669c083cf241b2dc27203348a96f446c7426b273637e911.pid  bc31ff95cc4f2cdb98b55ac565fe5698fc2adaa48ac2280ac128cb19287d7331.pid  log.json
8553a230f58b376c52c67bf6bfb5b4cb6991434fed77eac7f294492dbeba1fcf.pid  config.json                                                           rootfs …
```
=> bugfix: free resource after exec exit

daemon/mgr/container.go, daemon/mgr/spec_hook.go
set volumes to /etc/mtab in container, it makes the "df" command to show
the volume's information.
=> feature: set volumes to /etc/mtab

daemon/config/config.go, daemon/mgr/system.go, internal/generator.go
This pr adds the value assertion of 'Architecture/Images/LoggingDriver/RegistryConfig' on daemon side, in which case 'pouch info' command wil output more field value.
[root@instance-1 zouruicloud]# pouch info
Containers: 0
Running: 0
Paused: 0
Stopped: 0
Images:  1
ID: 
Name: instance-1
Server Version: 0.4.0
Storage Driver: overlayfs
Logging Driver: 
Cgroup Driver: 
runc: <nil>
Kernel Version: 3.10.0-693.11.1.el7.x86_64
Operating System: "CentOS Linux 7 (Core)"
OSType: linux
Architecture: amd64
HTTP Proxy: 
HTTPS Proxy: 
Debug: false
Labels:
node_ip=10.142.0.2
SN=GoogleCloud-0F7AA324BDD10D51358D5410E1D02814
CPUs: 1
Total Memory: …
=> enhance: add more field in 'pouch info' command

test/api_image_create_test.go, test/api_system_test.go, test/api_volume_list_test.go, test/cli_alikernel_test.go, test/cli_images_test.go, test/cli_volume_test.go, test/util_daemon.go
This PR mainly fixed some potential failure when tests run in no-travis-CI  environment.
For example:
* if the `homedir` of pouch daemon is not default value,  we need to get it dynamically.
* If there is legacy volumes, tests like `TestVolumeListOk ` may fail as it checks there are totally and exactly two volumes.
* If users set test images instead of using default ones, test `TestImagesWorks ` may fail.
=> test: make test more robust

ctrd/client.go, ctrd/client_opts.go, ctrd/client_test.go, ctrd/interface.go, ctrd/wrapper_client.go, daemon/config/config.go, daemon/daemon.go, main.go, pkg/utils/utils.go
When `pouchd` restart, if old `containerd` is alive, we take it over.
=> feature: take over old containerd instance when pouchd restart

.circleci/config.yml, docs/contributions/code_styles.md
This pull request tries to polish the code style document of project Pouch. These code styles should be followed when contributors are collaborating in this open source project. We will encourage every contributor to read this code style document first, and then do the code change.
In this pull request, I put forward the following 10 code style rules which are additional:
* RULE001 - Add blank line between field's comments
* RULE002 - Add parameter name in interface definition
* RULE003 - Import Packages
* RULE004 - Variable declaration position 
* RULE005 - Generation of action failure
* RULE006 - Return fast to ident less
* RULE007 - Lowercase log and error
* RULE008 - Nested errors
* RULE009 - Comment correctly
* RULE010 - Always …
=> docs: polish code style document for pouch

pkg/meta/boltdb.go
Add lock in boltdb, in order to avoid pouchd panic when put/get boltdb
objects concurrently.
use shell script will cause pouchd panic
```shell
#!/bin/bash
op=$1
for i in `seq 1 10`
do
case $op in
create)
pouch run -d --name multi-create-$i -v /mnt/dir1 -v /mnt/dir2 -v /mnt/dir3 -v /mnt/dir4 -v /mnt/dir5 -v /mnt/dir6 -v /mnt/dir7 -v /mnt/dir8 -v /mnt/dir9 -v /mnt/dir10 registry.hub.docker.com/library/busybox:latest top &
;;
remove)
pouch rm -vf multi-create-$i
;;
*)
;;
esac
done
```
```
```
pouchd panic
```
unexpected fault address 0x7fc8fd450853
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7fc8fd450853 pc=0xbf3adc]
goroutine 570 [running]:
runtime.throw(0x1b6bfeb, 0x5)
/usr/local/go/src/runtime/panic.go:605 +0x95 fp=0xc4210d8548 sp=0xc4210d8528 pc=0xbc1275 …
```
=> bugfix: add lock in boltdb

storage/volume/config.go, storage/volume/core.go, storage/volume/modules/ceph/ceph.go, storage/volume/types/storage.go, storage/volume/types/volume.go
change volume metadata struct for remote storage manager.
=> bugfix: change volume metadata struct

apis/server/container_bridge.go, apis/server/exec_bridge.go, apis/server/image_bridge.go, apis/server/network_bridge.go, apis/server/volume_bridge.go, daemon/mgr/container.go, daemon/mgr/container_exec.go, daemon/mgr/image.go, daemon/mgr/network.go, daemon/mgr/volume.go
This pr tries to make container, image, network, volume interface's implementation much more in order. This will make go files much more readable.
In addition, I split two files `exec_bridge.go` and `container_exec.go` since they are quite decoupled, I think.
none
none
none
none
=> refactor: reorder function sequence to make it more reasonable

daemon/mgr/network.go
Fix remove all endpoints when network disconnect.
=> bugfix: fix remove all endpoints when network disconnect

apis/server/container_bridge.go, apis/server/image_bridge.go, ctrd/container.go, daemon/daemon.go, daemon/mgr/container.go, daemon/mgr/container_exec.go, daemon/mgr/container_monitor.go, daemon/mgr/container_rich_mode.go, daemon/mgr/container_rich_mode_test.go, daemon/mgr/container_types.go, daemon/mgr/container_types_test.go, daemon/mgr/container_utils.go, daemon/mgr/container_utils_test.go, daemon/mgr/cri.go, daemon/mgr/cri_utils.go, daemon/mgr/cri_utils_test.go, daemon/mgr/spec.go, daemon/mgr/spec_annotations.go, daemon/mgr/spec_hook.go, daemon/mgr/spec_linux.go, daemon/mgr/spec_mount.go, daemon/mgr/spec_process.go, daemon/mgr/system.go
In the ContainerMgr of original code, we have two structs which describe container instance, one is Container, and the other is ContainerMeta. While we have the following relationship between them:
```golang
type ContainerMeta struct {
sync.Mutex
*Container
Detachkeys string
}
```
So, we can find that ContainerMeta has a very similar construction of Container. So we could only make use of Container to eliminate one to make code and data structure much more simplified.
none
none
none
none
=> refactor: eliminate containerMeta in daemon manager

cli/exec.go, client/container.go, client/container_exec.go, client/interface.go, test/cli_exec_test.go
add ContainerExecInspect client api, refactor container
part in client package.
make exec exit with correct exit code.
Fixes: #344.
add ContainerExecInspect client api, refactor container
part in client package.
make exec exit with correct exit code.
=> bugfix: fix exec not exit with correct exit code

.circleci/config.yml, pkg/errtypes/errors.go
I add tool [misspell](https://github.com/client9/misspell) to check incorrect English words spelling in this project.
I combined this feature in CI with test type of markdownlint.
In addition I use a new Dockerfile to construct new image `allencloud/mdlmisspell:v0.1`:
```
FROM ubuntu:16.04
RUN apt-get update \
&& apt-get install -y rubygems git curl \
&& gem install rake \
&& gem install bundler \
&& apt-get clean
RUN git clone https://github.com/markdownlint/markdownlint.git \
&& cd markdownlint && git checkout v0.4.0 && rake install
RUN git clone https://github.com/client9/misspell.git \
&& cd misspell && curl -L -o ./install-misspell.sh https://git.io/misspell && sh ./install-misspell.sh
RUN mv misspell/bin/misspell …
```
=> feature: add misspell tool to check English words

hack/make.sh
Push a test image to docker registry and pull it in each test instead of build a fresh new image.
In this way, it may reduce the test cost time. 
Also fix some shell format by handy.
fix #1282
=> test: using existing image and fix shell format error

ctrd/container.go, daemon/mgr/spec_mount.go
Mount `/sys/fs/cgroup` into the container.
#1247 
Use oci.Spec and containerd will help us to do mount.
```
➜  pouch git:(bugfix_add_mount_spec_in_oci) pouch run -it registry.hub.docker.com/library/busybox:1.28 sh
/ # ls -al /sys/fs/cgroup/
total 0
dr-xr-xr-x   13 root     root           340 May 14 09:16 .
drwxr-xr-x    9 root     root             0 May 14 08:20 ..
drwxr-xr-x    2 root     root             0 May 14 09:16 blkio
lrwxrwxrwx    1 root     root            11 May 14 09:16 cpu -> cpu,cpuacct
drwxr-xr-x    2 root     root             0 May 14 09:16 cpu,cpuacct
lrwxrwxrwx    1 root     root            11 May 14 09:16 cpuacct -> cpu,cpuacct
drwxr-xr-x    2 root     root             0 May 14 09:16 cpuset
drwxr-xr-x    2 root     root …
```
=> bugfix: mount /sys/fs/cgroup into container

.gitignore, cri/config/config.go, cri/service/cri.go, cri/src/cri.go, cri/src/cri_network.go, cri/src/cri_stream.go, cri/src/cri_types.go, cri/src/cri_utils.go, cri/src/cri_utils_test.go, cri/src/cri_wrapper.go, daemon/config/config.go, daemon/daemon.go, internal/generator.go
move the code about cri out of mgr, in order to decouple.
=> refactor: move the code about cri out of mgr

main.go
When the daemon server fails, the process will be hang because the
no-one closes the channel. We should exit.
Make the daemon exit happy.
NONE
Basically, we should run the daemon main in new goroutine and wait for it to exit. Based on this, we can receive the signal and clean it up. 
Use available port and it should be success.
```
pouchd --listen tcp://localhost:5000 --debug
```
Use used port and it should be fail
```
python -m SimpleHTTPServer 5000 &
pouchd --listen tcp://localhost:5000 --debug
```
@allencloud , @HusterWan and @rudyfly 
Should we need to clean it up like `sigHandle` when we receive error from `Run()`?
cc @shaloulcy
=> bugfix: make the daemon exit happy

test/api_container_restart_test.go
This pull request adds missing removal of container.
cc @Letty5411 
Otherwise I will get CI failure like:
```
FAIL: /go/src/github.com/alibaba/pouch/test/cli_ps_test.go:76: PouchPsSuite.TestPsAll
/go/src/github.com/alibaba/pouch/test/cli_ps_test.go:86:
// show running containers default
c.Assert(lines[1], check.Equals, "")
... obtained string = "TestAPIRestartPauseContainer   4b8795   Up 1 minute   1 minute ago   registry.hub.docker.com/library/busybox:1.28   runc"
... expected string = ""
```
=> test: add missing removal of container

test/cli_ps_test.go
```
----------------------------------------------------------------------
FAIL: /go/src/github.com/alibaba/pouch/test/cli_ps_test.go:113: PouchPsSuite.TestPsNoTrunc
/go/src/github.com/alibaba/pouch/test/cli_ps_test.go:131:
c.Assert(kv[name].id, check.HasLen, 64)
... obtained string = ""
... n int = 64
```
=> test: fix cli_ps_test failed

daemon/containerio/jsonfile.go, daemon/logger/jsonfile/jsonfile_read_test.go
The file related error may be os.ErrClosed. If so, we can show the
container has been stopped.
Make the jsonfile log friendly.
Fixes #1325 
Since the error has been wrapped by the Write function, we should use the `strings.Contain` to check the error if it contains the `file already closed`.
Basically, it's hard to verify it without change the logic, because it causes by the concurrent issue:
Before jsonfile writes the data into the file, the container manager has been stopped it and closed it.
In order to make it happen, we can add the `time.Sleep` before `Write`. It will show up.
=> bugfix: make the jsonfile log friendly

apis/swagger.yml, apis/types/container_json.go, test/cli_ps_test.go
=> bugfix: ExecIDs should be a slice

daemon/mgr/container.go
Right now flaky test happens once in a while because ```getExecConfig``` does not always get the execConfig result before IO is pipe closed.
This pr changed the sequence inside ```execExitedAndRelease```, which pouchd will call to execute ```exit```.  By moving IO close operation behind the execConfig value assignment, the result getting is ensured.
fixes #1337
=> bugfix: move IO part behind to ensure execConfig result assignment before IO closes

test/cli_create_test.go, test/cli_exec_test.go, test/cli_help_test.go, test/cli_inspect_test.go, test/cli_network_test.go, test/cli_ps_test.go, test/cli_pull_test.go, test/cli_restart_test.go, test/cli_rich_container_test.go, test/cli_rm_test.go, test/cli_rmi_test.go, test/cli_run_test.go, test/cli_start_test.go, test/cli_stop_test.go, test/cli_top_test.go, test/cli_unpause_test.go, test/cli_update_test.go, test/cli_upgrade_test.go, test/cli_volume_test.go
This PR mainly enhances code in cli_xxx_test.go in the following two aspects: 
1. using `icmd.result.Stderr()` instead of `icmd.result.Error` to print readable error message when stderr is not nil. Please notice that, if you wanna check running CMD return success, please user icmd.result.Assert() instead of using check.Assert(icmd.result.Error, check.IsNil). Because the following usage will not print readable error message.
2. using defer to do cleanup work. When create a container or volume or network, following a `defer` to make sure the resource will always be deleted even if test failed.
fix #1323
=> test: enhance cli related tests

INSTALLATION.md
$ apt-key fingerprint BE2F475F
pub   4096R/BE2F475F 2018-02-28
Key fingerprint = F443 EDD0 4A58 7E8B F645  9C40 CF68 F84A BE2F 475F
uid                  opsx-admin <opsx@service.alibaba.com>
fixes #1336
=> Update INSTALLATION.md apt-key fingerprint BE2F475F

daemon/mgr/volume.go, plugins/plugins.go, storage/volume/core.go, storage/volume/core_util.go, storage/volume/driver/driver.go, storage/volume/driver/driver_interface.go, storage/volume/driver/proxy.go, storage/volume/driver/remote.go, storage/volume/driver/types.go, storage/volume/modules/local/local.go, storage/volume/types/vars.go, storage/volume/types/volume.go, storage/volume/types/volume_util.go
Now pouch only supports local/tempfs/ceph volumes. Docker can support more volumes  with the help of volume plugin mechanism. In this PR，we implement remote volume driver, which also use volume plugin mechanism. Pouch volume plugin is compatible with docker, So we can use existing mature docker volumes drivers.
NONE
* installation：[https://github.com/CWSpear/local-persist](https://github.com/CWSpear/local-persist)
After start the local-persist volume plugin, it will create local-persist.sock in `/run/docker/plugins/`
```
pouch volume create -d local-persist --name test_vol -o mountpoint=/data/test_vol
CreatedAt:    2018-5-16 17:31:45
Driver:       local-persist
Mountpoint:   /data/test_vol
Name:         test_vol
Scope: …
```
=> feature: remote volume driver

daemon/mgr/system.go, hack/build, main.go, test/cli_version_test.go, version/version.go
auto-generate git commit, build time at build time,
fix go-version hard code.
Make version infomation atuo-generated at build time.
Before this pr
```
$ sudo pouch version
Arch:            amd64
BuildTime:       unknown
GitCommit:       unknown
GoVersion:       go1.9.1
KernelVersion:   4.4.0-121-generic
Os:              linux
Version:         0.4.0
APIVersion:      1.24
```
With this pr
```
$ sudo pouch version
GoVersion:       go1.10.2
KernelVersion:   4.4.0-121-generic
Os:              linux
Version:         0.4.0
APIVersion:      1.24
Arch:            amd64
BuildTime:       2018-05-18T13:37:46+08:00
GitCommit:       0.4.0-258-gef3b5e9-dirty
```
=> build: generate version information at build time

cri/src/cri.go, daemon/mgr/container.go, daemon/mgr/image.go, daemon/mgr/image_store.go, daemon/mgr/image_store_test.go, pkg/reference/parse_test.go, test/api_image_inspect_test.go, test/cli_rmi_test.go, test/environment/env.go
Basically, the user can use sha256:xyz to inspect image or run
container.
Enhance the Image Manager: Allow user to use image digest-type ID to consume pouch image.
For example, we pull busybox:1.28 by pouch. After pulled, the use can use the following method to inspect the image:
- pouch image inspect 8ac48589692a
- pouch image inspect sha256:8ac48589692a
- pouch image inspect busybox:1.28
- pouch image inspect busybox@sha256:58ac43b2cc92c687a32c8be6278e50a063579655fe3090125dcb2af0ff9e1a64
Fixes #1348 
Update the imageStore search functionality. We add the `sha256:" If the refOrID miss.  
BTW, both the `Delete` and `Search` functionality should use the following method to check the reference is ID or not. 
```
reference.IsNamedOnly(ref) || …
```
=> feature: allow use image by digest id

test/cli_run_test.go
Some kernel not support pids cgroup that make test case TestRunWithPidsLimit fail
=> test: fix TestRunWithPidsLimit fail cause no pids cgroup support

apis/swagger.yml, apis/types/system_info.go, cli/info.go, daemon/mgr/system.go, storage/volume/driver/driver.go, test/api_system_test.go
feature: add volume drivers info for system info
add volume drivers info when return system info
NONE
```
~# pouch info
Containers: 17
Running: 2
Paused: 0
Stopped: 15
Images:  4
ID: 
Name: ubuntu-1
Server Version: 0.4.0
Storage Driver: overlayfs
Logging Driver: 
Volume Drivers: [local-persist ceph tmpfs local]
Cgroup Driver: 
runc: <nil>
Kernel Version: 4.4.0-116-generic
Operating System: "Ubuntu 16.04.4 LTS"
OSType: linux
Architecture: amd64
HTTP Proxy: 
HTTPS Proxy: 
Debug: true
Labels:
node_ip=127.0.1.1
SN=0
CPUs: 1
Total Memory: 3.859 GiB
LiveRestoreEnabled: true
LxcfsEnabled: false
Daemon Listen …
```
=> feature: add volume drivers info for system info

cli/common_flags.go
pids-limit should have zero as initial value, or runtime
will fail to set if kernel not support pid-limit, that will
fail to start container.
=> bugfix: remove pids-limit initial value

cli/common_flags.go
remove initial value in cgroup-parent flag, or this flag
can never be set from config file when create container
with pouch cli.
```
func (mgr *ContainerManager) createContainerdContainer(ctx context.Context, c *Container) error {
// CgroupParent from HostConfig will be first priority to use,
// then will be value from mgr.Config.CgroupParent
if c.HostConfig.CgroupParent == "" { 
c.HostConfig.CgroupParent = mgr.Config.CgroupParent
}    
```
If pouch cli give cgroup-parent a default value, the `c.HostConfig.CgroupParent ` will  never be empty, and it can never use `CgroupParent ` set from daemon config file.
The default cgroup parent we already set in 
```
// same with containerd use. or make it a variable
cgroupsParent := "default"
if …
```
=> bugfix: fix cgroup-parent can not set from config

cli/pause.go, cli/restart.go, cli/rm.go, cli/rmi.go, cli/start.go, cli/unpause.go, test/cli_restart_test.go, test/cli_start_test.go, test/cli_unpause_test.go
enable managing more containers for some commands
Some commands just support managing one container/image, which is inconvenient for users to use. This pr enables managing one or more containers for some client commands and fixes little bugs in commands that support manage more than one container by now.
NONE.
```
$ pouch ps -a
Name            ID       Status                  Created        Image                                            Runtime
my_container2   0a83b7   Stopped (0) 3 seconds   1 minute ago   registry.hub.docker.com/library/busybox:latest   runc
my_container1   2aa41e   Stopped (0) 3 seconds   1 minute ago   registry.hub.docker.com/library/busybox:latest   runc
$ pouch start my_container1 my_container2
my_container1
my_container2
$ pouch ps 
Name            ID …
```
=> feature: enable managing more containers for some commands

apis/opts/env.go, apis/opts/env_test.go, daemon/mgr/container.go, test/cli_update_test.go
when we use `update` command to update container's env, we not only support add or update env, but also delete env
1. Check container's `env`:
```
root@osboxes:test (zr/update-env) -> pouch exec -it for-test env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOME=/
```
2. add `foo=bar` env
```
root@osboxes:test (zr/update-env) -> pouch update --env "foo=bar" for-test
root@osboxes:test (zr/update-env) -> pouch exec -it for-test env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
foo=bar
HOME=/
```
3. change `foo=bar` to `foo=bar1`
```
root@osboxes:test (zr/update-env) -> pouch update --env "foo=bar1" for-test
root@osboxes:test (zr/update-env) -> pouch exec -it for-test env …
```
=> feature: support update and delete env

.travis.yml, Makefile, hack/build, hack/make.sh, main_test.go, test/api_container_exec_inspect_test.go
Currently, `pouch` project only collect code coverage for unit-test. We have added hundreds of integration tests and it could be better if we could also have code coverage for integration tests.
I mainly refer these two articles and adjust it for `pouch` project:
https://www.cyphar.com/blog/post/20170412-golang-integration-coverage
https://blog.golang.org/cover
Here is what I have done:
1. Add `main_test.go` test file and wrap `main` function in it. 
In this way, when using `go test -c`, it will build a pouch daemon binary with source code edited by `go test`  inserting coverage related code. 
And this binary could still server as a pouch daemon with the following CMD:
```
./pouchd-test DEVEL --debug 
``` 
When start the above `pouchd-test` deamon, it will launch a pouch daemon with the …
=> test: add test coverage for integration test

docs/user/config_file.md
=> docs: add daemon config file doc

main.go
save pid into pidfile only when pidfile path is given, make code more reasonable.
=> bugfix: add judge for whether pidfile path is given

apis/server/image_bridge.go, apis/server/router.go, apis/swagger.yml, cli/main.go, cli/tag.go, client/image_tag.go, client/image_tag_test.go, client/interface.go, ctrd/image.go, ctrd/interface.go, daemon/mgr/image.go, daemon/mgr/image_store.go, test/api_image_tag_test.go, test/cli_tag_test.go
Since the containerd provides the ImageService to modify the boltdb
data, we can add tag reference into the containerd. Just in case that
the client removes the source image.
Use containerd's ImageService to implement `pouch tag` functionality. Allow user to create tag reference to existing image.
NONE.
The containerd stores the image name as key in the `boltdb`. `pouch run/image inspect/rmi` will use the primary reference as name to handle image information.
If we don't use the `boltdb` provided by containerd.ImageService, we will loss the tag reference when we remove the source image.
Therefore, when user adds tag reference to the existing image, I will do the following things:
* get the image from containerd
* use the tag reference as primary …
=> feature: init pouch tag functionality

hack/cri-test/test-utils.sh
Right now, cri-test will report flaky test from time to time, due to the default sandbox image is at home, while travis, which is located abroad, is used to run cri-test.
This pr changs the default sandbox image ```registry.cn-hangzhou.aliyuncs.com/google-containers/pause-amd64:3.0``` to ```gcr.io/google_containers/pause-amd64:3.0```, to reduce the possibility of random test errors caused by image pulling failure.
NONE
=> enhance: replace the default sandbox image for pouchd with google-released image

test/main_test.go, test/util_api.go
The post method of pullImage will hijack the connection so that the HTTP header always contains 200. It means that we cannot just check the HTTP status. We should read all the data bytes from server.
NONE
Read the bytes from server and check the error in the jsonstream.
Remove the `command.PouchRun("pull", busyboxImage)` in the beginning of test so that we can make sure the `PullImage` works well or not.
It is very important to make CI happy
=> bugfix: make the PullImage test util work

apis/swagger.yml, apis/types/resources.go, cli/common_flags.go, test/cli_run_test.go
blkio.weight_device need cfq io scheduler enable, add this
instruction for blkio-weight-device
add condition check for ci test TestRunBlockIOWeightDevice
Same problem also exist in #1346.
```
[root@r10d08216.sqa.zmf /root]
#pouch run -ti --blkio-weight-device "/dev/sda:1000" reg.docker.alibaba-inc.com/sunyuan/ubuntu:14.04 bash
Error: failed to run container 143a0e: {"message":"failed to create task, container id: 143a0e09b0d0d3905a6c56f66aa55576c0801fd50d1dc5072d6578eefc182231: OCI runtime create failed: container_linux.go:265: starting container process caused \"process_linux.go:348: container init caused \\\"process_linux.go:320: setting cgroup config for procHooks process caused \\\\\\\"failed to write 8:0 1000 to blkio.weight_device: write …
```
=> cli: add instruction for blkio-weight-device

daemon/mgr/container.go
fix panic when execute `exec` command with flag `-d`
fixes #1392
=> bugfix: panic when execute exec command with flag -d

test/api_image_inspect_test.go, test/environment/env.go
=> bugfix: use the stable image ID in test

test/cli_tag_test.go, test/utils.go
=> bugfix: use busybox:1.25 instead of busybox:1.28 in cli_tag_test

ctrd/client.go, ctrd/watch.go
fix problem: container may be killed when containerd process exit
we use a channel to listen container's task status, when channel return, we think the container is quit in simple, so we will kill container and container's task.
but when we restart pouchd, it will cause all channels broken, so we `wrongly` judge container task exited, and will  kill running container.
```
time="2018-05-24T11:42:49.209164971+08:00" level=info msg="the task has quit, id: 5e487dbae0b37c8d2c83328c1a5cccc449645365b58036e3b5c4795b8bd86c6c, err: rpc error: code = Internal desc = transport is closing, exitcode: 255, time: 0001-01-01 00:00:00 +0000 UTC"
time="2018-05-24T11:42:49.209504432+08:00" level=error msg="failed to delete task, container id: …
```
=> bugfix: containerd instance exit may cause container exit

test/cli_images_test.go
Since the image mgr return the images list in random order, in testing
we should sort before check and match.
NONE
NONE
NONE
=> test: sort image list before check

.travis.yml
When the PR only changes the doc file, we should not run the integration test because it will take us so long to wait.
NONE
Use `TRAVIS_COMMIT_RANGE` to make diff.
NONE
=> feature: travis doesn't run document-only changed commit

hack/make.sh
After integration tests, we will clean the local-persist volume plugin
#1396
=> enhance: clean the local-persist after integration tests

apis/server/volume_bridge.go, apis/swagger.yml, cli/volume.go, storage/volume/modules/local/local.go, test/cli_alikernel_test.go, test/cli_run_volume_test.go, test/cli_volume_test.go
Before use 'size' or 'opt.size' to set volume size, now change it to
'opt.size', 'size' will not effective.
fixes #1399 
use this way to create volume
```
```
=> bugfix: change the option to set volume size

daemon/daemon.go, daemon/mgr/container.go
fix bug: containerMgr use the networkMgr struct before initialize it that will occur `panic: runtime error: invalid memory address or nil pointer dereference`
when start `pouchd`, we will call `containerMgr.Restore` to restore all running containers,  if the container has already exited but disk file record the status is `running`, we must  call `markStoppedAndRelease` method to clean the container's resources and mark it `stopped`.
`markStoppedAndRelease` method will call `containerMgr.networkMgr`, so if `networkMgr` not initialized, there will painc:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x17d2e14]
goroutine 47 [running]: …
```
=> bugfix: we must call Restore container after initialize network Mgr

apis/server/image_bridge.go, cli/pull.go, cli/run.go, cli/upgrade.go, client/request.go
fix #1379
and remove the duplicate image tag in logs
=> bugfix: pull image before run and upgrade

apis/server/image_bridge.go, apis/server/router.go, apis/swagger.yml, cli/load.go, cli/main.go, client/image_load.go, client/image_load_test.go, client/interface.go, client/request.go, ctrd/image.go, ctrd/interface.go, daemon/mgr/image.go, daemon/mgr/image_load.go, pkg/multierror/def.go, pkg/multierror/def_test.go, test/api_image_load_test.go, test/cli_load_test.go, vendor/github.com/containerd/containerd/images/oci/exporter.go, vendor/github.com/containerd/containerd/images/oci/importer.go, vendor/vendor.json
Allow user to load **oci.v1 format** image by tar stream. 
NONE
Use containerd image oci importer to load the image.
First one is help:
```
➜  /tmp pouch load -h
load a set of images by tar stream
Usage:
pouch load [OPTIONS] [IMAGE_NAME]
Examples:
$ pouch load -i busybox.tar busybox
Flags:
-h, --help           help for load
-i, --input string   Read from tar archive file, instead of STDIN
```
Since we don't have dump functionality for pouch, we need to verify it by `ctr`.
```
➜  /tmp ctr images export test.tar registry.hub.docker.com/library/busybox:1.28
➜  /tmp pouch load test < test.tar
➜  /tmp pouch images
IMAGE ID       IMAGE NAME   SIZE
8ac48589692a   test:1.28    710.83 KB
➜  /tmp pouch run 8ac48589692a ls
bin
dev
etc
home
proc
root
run
sys …
```
=> feature: add pouch load functionality

FAQ.md
Add support for FAQ about linux kernel version and distribution versions.
none
none
none
none
=> docs: update FAQ.md to add kernel version support

apis/swagger.yml, apis/types/container_config.go, cli/common_flags.go, cli/container.go, cri/v1alpha1/cri_utils.go, cri/v1alpha2/cri_utils.go, daemon/mgr/container.go, daemon/mgr/spec_mount.go, test/cli_run_test.go
Now when we start a container,  it has no network files, including /etc/hosts, /etc/hostname and /etc/resolv.conf. In this PR, we will generate container's network files when container starts
fixes https://github.com/alibaba/pouch/issues/1162
The libnetwork will help us generate network files(/etc/hosts and /etc/resolv.conf). /etc/hostname will be generated by pouchd.
At last, we should mount it into container.
start a container,  and list /etc
```
BusyBox v1.21.1 (Ubuntu 1:1.21.0-1ubuntu1) built-in shell (ash)
Enter 'help' for a list of built-in commands.
~ # ls /etc/
group          hosts          passwd
hostname       nsswitch.conf  resolv.conf
```
check network files
```
~ # cat /etc/hostname
helloPouch
~ # cat /etc/hosts
127.0.0.1	localhost …
```
=> feature: add container's network files

.circleci/Dockerfile, .circleci/config.yml, hack/cri-test/test-cri.sh, hack/cri-test/test-utils.sh, hack/generate-swagger-models.sh, hack/install_lxcfs_on_centos.sh, hack/make.sh, hack/package/deb/build.sh, hack/package/package.sh, hack/package/rpm/build.sh, hack/package/rpm/scripts/after-install.sh, hack/package/rpm/scripts/after-remove.sh, hack/package/rpm/scripts/after-trans.sh, hack/package/rpm/scripts/before-install.sh, hack/package/rpm/scripts/before-remove.sh, hack/vagrant/bootstrap.sh
This PR help pouch to pass the ShellCheck (https://github.com/koalaman/shellcheck). There is a short report.
SC2086 Double quote to prevent globbing and word splitting **94** fail(s)
SC2046 Quote this to prevent word splitting **8** fail(s)
SC2034 POUCH_SOCK appears unused. Verify it or export it **7** fail(s)
SC2039 In POSIX sh, 'pushd' is not supported **6** fail(s)
SC2148 Tips depend on target shell and yours is unknown. Add a shebang **5** fail(s)
SC2112 'function' keyword is non-standard. Delete it **4** fail(s)
SC2016 Expressions don't expand in single quotes, use double quotes for that **3** fail(s)
SC2006 Use $(..) instead of legacy `..` **2** fail(s)
SC2129 Consider using { cmd1; cmd2; } >> file instead of individual redirects **1** fail(s)
SC2071 < is for string comparisons. Use …
=> fix: correct shell script format via shellcheck reports

apis/server/container_bridge.go, apis/server/network_bridge.go, apis/server/utils.go, apis/server/volume_bridge.go
This pr adds more log on pouchd side. While creating a new container, network or volume, create args will be printed on pouchd log, which enables us to debug a possible creation failure on API side.
```Infof()``` is adopted since we think it is better for production environment, than ```Debugf()```.
fixes #664
```
INFO[2018-06-01T07:45:48.197062353Z] Calling POST /v1.24/volumes/create, client @ 
INFO[2018-06-01T07:45:48.197302776Z] create volume with args: {"Driver":"local","DriverOpts":{"opt.size":"100g"},"Name":"pouch-volume"}
```
```
INFO[2018-06-01T07:46:52.219091382Z] Calling POST /v1.24/networks/create, client @ 
INFO[2018-06-01T07:46:52.219286598Z] create network with args: {"Name":"pouchnet","CheckDuplicate":true,"Driver":"bridge","IPAM" …
```
=> enhance: add more log for creating new objects

daemon/mgr/container.go, daemon/mgr/container_utils.go, pkg/system/cgroup.go, pkg/system/cgroup_test.go
check cgroup resource valid in container create,
discard un-support cgroup set related flag.
Pouch run get lots of flags that whether these flags can be set depend on the 
corresponding cgroup file is exist. Add check for the cgroup file is needed.
=> feature: add cgroup resources check

hack/make.sh, hack/package/rpm/build.sh
Signed-off-by: zhuangqh <zhuangqhc@163.com>
Correct hard coding in several shell script, using configurable variable instead.
Fix a minor bug in #1447
=> refactor: correct hard coding in several shell script

test/api_container_create_test.go, test/api_container_delete_test.go, test/api_container_exec_create_test.go, test/api_container_exec_inspect_test.go, test/api_container_exec_start_test.go, test/api_container_inspect_test.go, test/api_container_logs_test.go, test/api_container_pause_test.go, test/api_container_rename_test.go, test/api_container_resize_test.go, test/api_container_restart_test.go, test/api_container_start_test.go, test/api_container_stop_test.go, test/api_container_wait_test.go, test/api_image_delete_test.go, test/util_api.go
Signed-off-by: zhuangqh <zhuangqhc@163.com>
replace DelContainerForceOk with DelContainerForceMultyTime
fixes #1376
=> fix: replace DelContainerForceOk with DelContainerForceMultyTime

docs/features/pouch_with_runV.md
This PR adds docs about how to run legacy kernels in Guest OS provided by runV with PouchContainer.
It includes the background, scenarios and support on it.
However, I am still wondering if we could directly embed the video into this documents file rather than redirect to an outer link. Any ideas on this part? @zhuangqh 
none
none
none
none
=> docs: add supporting legacy kernels into runV

daemon/mgr/container_utils.go
Set memory swap initial value to 0 and add more check in cgroup info check.
Fixes: #1463
=> bugfix: set memory swap initial value to 0

apis/server/image_bridge.go, ctrd/container.go, daemon/containerio/jsonfile.go, daemon/mgr/container.go, daemon/mgr/container_exec.go, daemon/mgr/container_state.go, daemon/mgr/container_types.go, daemon/mgr/spec.go, test/api_container_logs_test.go, test/cli_pull_test.go, test/cli_top_test.go
In the container manager, code usually use 
```
c.Lock()
defer c.Unlock()
```
to avoid race condition. While I think it is not so preferred since it does have serious affect on performance.
This PR dis three types of things:
* encapsulate all state management into a single file container_state.go;
* make container.Lock much more grained granularity.
* change log format to make it more explicit.
fixes #1244
=> feature: update lock policy for container management

Makefile
add help info into makefile
none
added make help command
```
[root@qing pouch]# make help
fmt                  run go fmt
lint                 run go lint
vet                  run go vet
unit-test            run go test
validate-swagger     run swagger validate
install              build and install binary into /usr/local/bin
uninstall            uninstall pouchd and pouch binary
integration-test     build binary and run integration-test
cri-test             build binary and run cri-test
test                 run the build integration-test cri-test
help                 this help
```
none
=> feature: add make help into makefile

apis/swagger.yml, apis/types/ip_a_m_config.go, daemon/config/config.go, daemon/daemon.go, daemon/mgr/network.go, extra/libnetwork/drivers/bridge/port_mapping.go, extra/libnetwork/drivers/bridge/setup_ipv4.go, extra/libnetwork/drivers/bridge/setup_verify.go, main.go, network/config.go, network/mode/bridge/bridge.go, network/mode/bridge/vars.go
Change the default nat bridge network from 172.17.0.1/24 to 192.168.5.1/24
Complete the bridge network configure.
Don't to change bridge device ip address.
=> feature: modify defaut bridge mode

hack/package/rpm/build.sh, hack/package/rpm/scripts/after-install.sh, hack/package/rpm/service/pouch-lxcfs.service
Instead of offering `lxcfs` binary, pouch rpm offers a `pouch-lxcfs` binary to avoid conflict with users environment.
fix #1476 
1. change the `liblxcfs.so` to `libpouchlxcfs.so` in lxcfs source code.
2. remove files in `share` directory, which is used for LXC
3. rename lxcfs.service to pouch-lxcfs.service
Now rpm includes the following files:
```
#rpm -qlp pouch-1.0.0-1.el7.centos.x86_64.rpm
warning: pouch-1.0.0-1.el7.centos.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 439ae9ec: NOKEY
/usr/bin/pouch-lxcfs
/usr/lib/systemd/system/pouch-lxcfs.service
/usr/lib/systemd/system/pouch.service
/usr/lib64/libpouchlxcfs.so
/usr/local/bin/containerd
/usr/local/bin/containerd-release
/usr/local/bin/containerd-shim
/usr/local/bin/containerd-stress …
```
=> bugfix: rename lxcfs to pouch-lxcfs in pouch.rpm

daemon/mgr/container_utils.go, daemon/mgr/spec_linux.go, test/cli_run_memory_test.go
set value of memory swap double of non-zero memory value if
not specify --memory-sawp.
2x memory swap value is advised but not must.
You should typically size your swap space to approximately 2x main
memory for systems with less than 2GB of RAM, or approximately 1x main
memory if you have more. If you do not have a lot of RAM, though, you
will generally want a lot more swap. It is not recommended that you
configure any less than 256M of swap on a system and you should keep in
mind future memory expansion when sizing the swap partition. The
kernel's VM paging algorithms are tuned to perform best when there is at
least 2x swap versus main memory. Configuring too little swap can lead
to inefficiencies in the VM page scanning code as well as create issues
later on if you add more memory to …
=> fix: set memory swap double of non-zero memory value

hack/build
This patch is used for fix issue #1477.
6fa7b4b2a52f9f8ceaef7532a3e79ae15fd88c8f
Without this patch:
pouch# make install
pouch# ll -h pouch pouchd
-rwxr-xr-x 1 root root 29M Jun   7 17:21 pouch*
-rwxr-xr-x 1 root root 58M Jun   7 17:21 pouchd*
With the patch:
pouch# make install
pouch# ll -h pouch pouchd
-rwxr-xr-x 1 root root 17M Jun   7 17:19 pouch*
-rwxr-xr-x 1 root root 33M Jun   7 17:19 pouchd*
As subject
use strip command to remove the symbol table and debugging information from an executable pouch and pouchd.
to compare size of pouch and pouchd binaries by ls -lh before and after applying this patch.
=> hack.build: reduce the size of pouch and pouchd binaries

network/mode/bridge/bridge.go
Before default nat network is 172.17.0.1/24, commit: 7e7f6072 has
changed it to 192.168.5.1/24. If "p0" is exist, pouchd start will check
gateway is error.
fixes https://github.com/alibaba/pouch/issues/1494
When get the bridge route is nil and haven't configed gateway in config.json, so we use bridge ip address as gateway.
set p0 bridge as before 172.17.0.1/24, and start pouchd
=> bugfix: fix the wrong bridge gateway

cri/v1alpha1/cri.go, cri/v1alpha2/cri.go, daemon/mgr/spec_mount.go
When I try to launch a pod of flannel, there are two problems:
1. flannel pod will mount the `/run` in the host to the container's `/run`, which is duplicate with the default mounts created by pouchd and we should override the default one.
2. When an error occurred in the process of running a sandbox (for example, network not initialized), we should delete the running sandbox container. Otherwise kubelet will list the sandboxes and to wrongly assume the error sandbox is running which is not expected.
=> if run sandbox failed, clean up; deduplicate the default mounts with user defined ones

pkg/utils/utils.go, pkg/utils/utils_test.go
make nullable value like `false` and 0 not be recognized as
empry value, in config set, they should be valid value.
=> fix: support nullable bool value set in config

daemon/containerio/container_io.go
if the consumer pops the data slower than the producer, the data will be
overrided by the coming data.
Fixed bug caused by the shared data.
In the [pouch](https://github.com/alibaba/pouch/blob/master/daemon/containerio/cio.go#L125), we use the following statement to copy data from fifo into containerio.
```
// https://github.com/alibaba/pouch/blob/master/daemon/containerio/cio.go#L125
go func(r io.ReadCloser) {
io.Copy(ioset.out, r)
r.Close()
wg.Done()
}(f)
// https://github.com/alibaba/pouch/blob/master/daemon/containerio/container_io.go#L219
func (cio *ContainerIO) Write(data []byte) (int, error) {
switch cio.typ {
case stdout:
for _, b := range cio.backends {
if cover := b.outRing.Push(data); cover {
logrus.Warnf("cover data, backend: %s, id: …
```
=> bugfix: copy data before put it into ringbuf

hack/kubernetes/allinone_aliyun.sh
+ Delete '\r' in hack/kubernetes/allinone_aliyun.sh to pass shellcheck
+ Delete unused variables in hack/kubernetes/allinone_aliyun.sh to pass shellcheck
None
```
tr -d '\r' < hack/kubernetes/allinone_aliyun.sh > hack/kubernetes/allinone_aliyun.sh.bak
rm -rf hack/kubernetes/allinone_aliyun.sh
mv hack/kubernetes/allinone_aliyun.sh.bak hack/kubernetes/allinone_aliyun.sh
```
=> fix: Make hack/kubernetes/allinone_aliyun.sh to pass shellcheck

daemon/mgr/container.go
if pouch update a container get error, restore container
config, aviod container record error config.
Fixes: #1512
Fixes: #1512
=> bugfix: restore config after update fail

cri/v1alpha1/cri.go, cri/v1alpha2/cri.go, daemon/mgr/container.go, daemon/mgr/container_state.go
add feature: UpdateContainerResources of CRI Manager
None
```
WARNING: Current Kernel does not support memory swap, discard --memory-swap 
bd6c5b9de4874f6703961ed543a9056a9762279433c6cad0fd8b63f42f636ff5
20971520
DEBU[0000] UpdateContainerResourcesRequest: &UpdateContainerResourcesRequest{ContainerId:bd6c5b9de4874f6703961ed543a9056a9762279433c6cad0fd8b63f42f636ff5,Linux:&LinuxContainerResources{CpuPeriod:0,CpuQuota:0,CpuShares:0,MemoryLimitInBytes:31457280,OomScoreAdj:0,CpusetCpus:,CpusetMems:,},} 
DEBU[0000] UpdateContainerResourcesResponse: &UpdateContainerResourcesResponse{} 
bd6c5b9de4874f6703961ed543a9056a9762279433c6cad0fd8b63f42f636ff5
31457280
```
=> feature: UpdateContainerResources of CRI Manager

hack/package/rpm/build.sh
=> bugfix: fix rpm package bug

hack/build
Reverts alibaba/pouch#1484
debug symbols also are removed by strip, although size of pouch and pouchd binaries are reduced, perhaps, we can append --only-keep-debug option to strip to avoid this issue later.
=> Revert "hack.build: reduce the size of pouch and pouchd binaries"

cli/update.go, ctrd/utils.go, daemon/mgr/container.go, test/cli_update_test.go
this PR has done two things:
* remove update `memory-swappiness`, actually runc not allow to update this param, so it's no sense to update it in pouch.
* fix update `CPUQuota` , in containerd 1.0.3 this var is defined int64, but in containerd 0.2.4 is defined uint64, so we should not allow to pass `-1` value of `CPUQuota` to containerd.
```
CPUQuota int64
CpuQuota uint64
```
=> fix: update cpu-quota of 0.2.4 container may occur error

cri/v1alpha1/cri_stream.go, cri/v1alpha2/cri_stream.go, pkg/net/doc.go, pkg/net/interface.go, pkg/net/interface_test.go
The stream sever should bind an system interface, otherwise the URL it return will be like:
`"http://:10010/exec/oM5ZZlm3"`
So as mentioned in issue #1516 , we can't exec the pod from other nodes.
If the URL is lack of ip address, it will be localhost by default. 
However the pod is not in the local node, so the local stream server will return 404.
#1516
=> bugfix: bind an address for stream server

apis/swagger.yml, apis/types/registry_service_config.go, cli/main.go, cli/update_daemon.go, client/client.go, client/daemon_update.go, client/daemon_update_test.go, client/interface.go, cri/config/config.go, daemon/config/config.go, main.go, network/config.go, network/mode/bridge/bridge.go, storage/volume/config.go, test/z_cli_daemon_test.go
Currently, update daemon only supports with restful api, there is no cli command,
so need add it, in addition, it only supports update with pouchd is alive, so we need
update config file when pouchd is dead.
Pouch daemon config file is json format, it's hard to modify
with shell script, so add this function to change the config file easily.
NONE
If pouchd is alive, it will change, daemon config if it supports, 
and then change the config file. If pouchd is dead, it just update
the daemon config file. Currently, online update only support
`image-proxy` and `label`, more options will be supported at the
following few prs.
pouchd offline set:
You can specified the config file by set `--config-file` to update, 
if pouchd is alive, you can set `--offline=true` to modify config file only,
more …
=> feature: add update daemon config function

daemon/mgr/container.go
change the order of generating mountpoints.
1. generate MountPoints from other containers(volumes-from)
2. generate MountPoints from binds
3. generate MountPoints from images
4. generate MountPoints from Config.Volumes
Why?
Every volume has a destination in container. So if two volume have the same destination, only one volume takes effect. 
Now the order of volume taking effect is 
1. generate MountPoints from Config.Volumes
2. generate MountPoints from images
3. generate MountPoints from binds
4. generate MountPoints from other containers(volume-from)
So if Config.Volumes,  images, binds and volume-from all have a volume whose destination is the same. Only the Config.Volumes will take effect.
Indeed, the right order is
volumes-from 》 binds …
=> bugfix: change the order of generating MountPoints

cri/v1alpha1/cri.go, cri/v1alpha2/cri.go
Please refer: #1536
When stop the sandbox, if the network namespace file of the sandbox does not exist, skip tearing down the pod network.
fixes #1536
=> bugfix: skip teardown network, if the sandbox has been stopped

daemon/mgr/container.go, daemon/mgr/volume.go, storage/volume/core.go, storage/volume/driver/driver_interface.go, storage/volume/modules/local/local.go
Add attach volume  when container start. Now volume attaching is
at container create stage, but if host have been restarted, container won't be
created, so volume can't be attached.
Add Config() for volume driver, it makes volume driver can use the
configure of volume in daemon. Now set `volume-meta-dir` and
`volume-timeout` into driver config.
NONE
A running container can start again after host have been restarted.
=> bugfix: add attach volume when container start

daemon/mgr/container.go, daemon/mgr/container_state.go, daemon/mgr/container_types.go
This pull request did these things:
1. encapsulate more code blocks into a single function to add more readability;
2. add more information setting in `SetStatusExited`
3. avoid to set status `stopped` in `markExitedAndRelease`;
4. avoid to set status `stopped` in `Remove` action. 
none
none
none
none
=> refactor: make code more encapsulate and logic simple

test/api_container_logs_test.go, test/cli_alikernel_test.go, test/cli_restart_test.go, test/cli_run_blkio_test.go, test/cli_run_pid_test.go, test/cli_run_test.go, test/cli_start_test.go, test/cli_upgrade_test.go, test/z_cli_daemon_test.go
Add "top" CMD when running a container. If we don't specify CMD when starting a container, it will use the default one in image, most of time it is `sh`. Sometimes, test may expect the container in `running` state, which is not true if CMD is not specified explicitly.
=> bugfix: refine tests with specifying CMD

ctrd/container.go, ctrd/container_types.go, daemon/mgr/container.go, daemon/mgr/container_types.go, pkg/mount/mount.go, pkg/mount/mount_test.go
Actually, the containerd support creating a container by just specifying the container rootfs, the feature is very useful when we want to take over the container created by other container hypervisor.
in order to distinguish container that created by specifying rootfs or snapshot, we add a flag `RootFSProvided`, when the flag set, the container is created by just specifying rootfs.
this feature is also needed by upgrade docker to PouchContainer,  we must support taking over containers created by docker
we also should consider the abnormal situations like host crashed etc. so when starting a `RootFSProvided` container , we should check if the `rootfs` has mounted, if not, we must mount it.
=> feature: support creating container by just specifying rootfs

cli/common_flags.go, cli/update.go, daemon/mgr/container_utils.go, test/cli_restart_test.go, test/cli_run_cpu_test.go, test/cli_update_test.go, test/cli_upgrade_test.go
the related command line flag about cpu share should be `--cpu-shares` rather than `--cpu-share`.
This update would be compatible with moby's way.
none
change the flag file and test
none
none
=> fix: rename cpu-share to cpu-shares in command line

test/cli_restart_test.go
This pr changes the test cases for restart action:
1. add command in running container;
2.add containers with all states to check the restart action, like running, exited, stopped, created.
this is similar to https://github.com/alibaba/pouch/pull/1548
none
none
none
@Letty5411
=> test: add all states container restart validation

test/cli_upgrade_test.go
add top command in upgrade test suite to make run a long running container.
none
add top command in upgrade test suite
none
=> test: add top command in upgrade test suite

apis/opts/memory_swappiness.go, apis/opts/memory_swappiness_test.go, apis/swagger.yml, apis/types/resources.go, cli/common_flags.go, daemon/mgr/container.go, daemon/mgr/container_types.go, daemon/mgr/container_utils.go, test/cli_update_test.go
add container config settings check, include container config and
host config in create container, update container.
fix memory_swappiness initial value to zero, since -1 is invalid.
```
#echo -1 > /sys/fs/cgroup/memory/pouch/4d770c0e1a84320c513d9569511c0d65046eda456723340851356b9eb86c0e01/memory.swappiness 
bash: echo: write error: Invalid argument
```
=> feature: add container setting check

apis/opts/shm_size.go, apis/opts/shm_size_test.go, cli/common_flags.go, cli/container.go, daemon/mgr/container_utils.go, daemon/mgr/spec_mount.go, test/cli_run_test.go
support run commond `pouch run -d --shm-size 1g  registry.hub.docker.com/library/busybox:latest top`
=> feature: support shm size

.circleci/config.yml
This pr add webhook notification mechanism in circleci config file. In this case, when circleci fails our friend PouchRobot will make a comment to report.
=> feature: add webhook to notify our friend PouchRobot when circleci fails

test/cli_run_volume_test.go, test/util_api.go
the volumes of container have four different sources(volumes-from,
binds, images and Config.Volume). If two volumes have the same destination,
only one volume is reserved. The order is
volumes-from > binds > images > Config.Volume
the volumes of container have four different sources(volumes-from, binds, images and Config.Volume). If two volumes have the same destination, only one volume is reserved. The order is
volumes-from > binds > images > Config.Volume
NONE
NONE
NONE
=> test: add test for different volume sources

storage/volume/README.md, storage/volume/core.go
Right now,  the volume core has no lock. It may have problems in some race conditions. In this pull request, we add volume lock.
NONE
=> enhance: add volume lock

test/cli_network_test.go, vendor/github.com/docker/libnetwork/sandbox_store.go, vendor/vendor.json
It seems a bug of libnetwork. When libnetwork restores the sandbox, it forgets to initialize the epPriority map. So the Join panic. The latest alibaba/libnetwork has fixed the bug. We will vendor the latest libnetwork and add some test cases
https://github.com/alibaba/libnetwork/commit/655f08f8be32ff847d0554ef0128a3de80665cd6
It seems a bug of libnetwork. When libnetwork restores the sandbox, it forgets to initialize the epPriority map. So the Join panic. The latest alibaba/libnetwork has fixed the bug. We will vendor the latest libnetwork and add some test cases
fixes #1550
=> bugfix: vendor latest libnetwork for connect panic

apis/server/server.go, pkg/user/user.go, pkg/user/user_test.go
adjust pouchd unix socket file mode, make it ownered by group
pouch.
Before this patch, we can only use pouch with user root, with this patch, we add this permission to group pouch. We create a unix sock with pouch group, and change it mode to 0660, make other group can write
```
$ ls -l /run/pouchd.sock 
srw-rw---- 1 root pouch 0 6月  21 12:36 /run/pouchd.sock
$ users
ace
$ pouch images
IMAGE ID       IMAGE NAME                                          SIZE
00f017a8c2a6   reg.docker.alibaba-inc.com/base/busybox:latest      686.62 KB
8ac48589692a   registry.hub.docker.com/library/busybox:1.28        710.83 KB
e38bc07ac18e   registry.hub.docker.com/library/hello-world:linux   5.26 KB
```
=> feature: adjust pouchd unix socket premissions

daemon/daemon.go, daemon/mgr/container.go, daemon/mgr/network.go
the network manager must be initialized after container manager has restored all containers, as the network manager need to get the real ActiveSandboxes which are returned by container manager?
the network manager must be initialized after container manager has restored all containers, as the network manager need to get the real ActiveSandboxes which are returned by container manager?
what is real ActiveSandboxes?  
For example,  a container is running. Then we reboot the OS, the container status in metadata is running. But actually it is stopped. We must restore all containers,  then we can get the real container status
fixed #1439
=> bugfix: network not found

apis/server/exec_bridge.go
This pr adds log for ```create exec``` operation for debugging. The daemon side will print related args, which is the configuration of ```create exec```.
fixes #1563
```
pouch exec -it ab4edf sh
```
Here is the log from daemon side:
```
create container exec with args: {"AttachStderr":true,"AttachStdin":true,"AttachStdout":true,"Cmd":["sh"],"Tty":true} 
```
=> enhance: add log for create container exec operation for debugging

apis/plugins/ContainerPlugin.go, apis/server/container_bridge.go, apis/swagger.yml, apis/types/update_config.go, cli/update.go, daemon/mgr/container.go, test/cli_update_test.go
refactor container update diskquota type, change it from `string` to
`map[string]string`, make it consistent with container create api.
NONE
=> refactor: refactor container update diskquota type

test/cli_run_memory_test.go
=> test: add TestRunMemoryOOM test case

apis/opts/config/blkio.go, apis/opts/config/blkio_test.go, apis/opts/config/runtime.go, apis/opts/config/runtime_test.go, apis/opts/config/ulimit.go, cli/container.go, main.go
move config file cli/ulimit.go, cli/blkio.go, config/opt/runtime.go
to apis/opts/config, put all user defined flag var type into one places.
=> refactor: move config file from cli into one places

daemon/mgr/container_state.go, test/cli_run_test.go
`SetStatus` set Running flag to true when started a container
fixes https://github.com/alibaba/pouch/issues/1602
=> bugfix: we should set Running flag to true when started container

.circleci/config.yml, .travis.yml
I used to use QingCloud as my pouchrobot, while currently I change this to be alibaba cloud.
So I need to update the travisCI webhook address and circleci webhook address.
none
none
none
none
=> feature: update pouchrobot address tobe Alibaba Cloud

daemon/mgr/container.go
amendContainerSettings should before validateConfig
=> bugfix: fix memory-swap flag not validate correct

apis/swagger.yml, apis/types/container_exec_inspect.go, apis/types/process_config.go, apis/types/registry_service_config.go, daemon/mgr/container_exec.go
exec inspect return json body align with moby api. delete all `omitemtpy` flag from ContainerExecInspect
=> bugfix: execConfig remove omitemtpy

daemon/mgr/container.go
when execute prestart hook, if container's rootfs not mounted will cause start failed. so, we should mount the rootfs before excute prestart hook.
=> bugfix: execute remount rootfs before prestart hook

daemon/logger/syslog/fmt.go, daemon/logger/syslog/validate.go, daemon/logger/syslog/validate_test.go
A lot of log collectors consumes log data and indexs it by the timestamp in millisecond format. In order to make the collector to consume data in the order, we need to add the sequence number in the log. Simplify the case, PouchContainer will uses the nano timestamp as sequene number.
NONE
Add one more syslog formatter
First, we should follow the `/var/log/syslog` and run `pouch run --log-driver syslog --log-opt syslog-format=rfc5424micro-seq --log-opt tag={{.DaemonName}} busybox echo hi`.
We will got the message in the syslog like:
```
Jul  2 15:41:02 ubuntu-xenial 1 1530517262291559773 2018-07-02T15:41:02.291559+08:00 ubuntu-xenial pouchd 7335 pouchd - hi
```
=> enhance: add new formatter for syslog

daemon/mgr/image.go
Since the containerd doesn't identify the application/octet-stream media
type, it will cause ListImages API fails to return images to the caller.
In order to avoid odd thing happen and add patch to containerd, we
should ignore the error to make PouchContainer robust.
Fixed #1583
Ignore the error.
1. pouch pull redis:2
2. pouch images
```
➜  pouch git:(bugfix_make_image_list_successful) pouch images
8c811b4aec35   docker.io/library/busybox:1                      710.81 KB
8c811b4aec35   docker.io/library/busybox:1-uclibc               710.81 KB
8c811b4aec35   registry.hub.docker.com/library/busybox:latest   710.81 KB
```
3. check the pouch daemon log
```
WARN[2018-07-05T10:22:06.69910634+08:00] encountered unknown type …
```
=> bugfix: list image should ignore error if containerd can't handle well

cri/annotations/annotations.go, cri/v1alpha1/cri.go, cri/v1alpha1/cri_types.go, cri/v1alpha1/cri_utils.go, cri/v1alpha2/cri.go, cri/v1alpha2/cri_types.go, cri/v1alpha2/cri_utils.go
fixes #1580
1. Prerequisites Installation, the runtime binaries you will use is necessary
2. You should start pouchd with the configuration like 
```
pouchd --enable-cri --cri-version v1alpha2 --add-runtime runv=runv >pouchd.log 2>&1  &
```
3. After setting up your kubernetes cluster, you can create a deployment like this :
```
apiVersion: apps/v1
kind: Deployment
metadata:
name: pouch
labels:
pouch: pouch
spec:
selector:
matchLabels:
pouch: pouch
template:
metadata:
labels:
pouch: pouch
annotations:
io.kubernetes.runtime: runv
spec:
containers:
- name: pouch
image: docker.io/library/nginx:latest
ports:
- containerPort: 80
```
3. Use command  `pouch ps` to observe the runtime of the container.
=> feature: make runtime choosing supported in CRI managers for Kubernetes

apis/server/server.go, cri/criservice.go, daemon/daemon.go, hack/package/deb/systemd/pouch.service, hack/package/rpm/service/pouch.service, vendor/github.com/coreos/go-systemd/LICENSE, vendor/github.com/coreos/go-systemd/NOTICE, vendor/github.com/coreos/go-systemd/daemon/sdnotify.go, vendor/github.com/coreos/go-systemd/daemon/watchdog.go, vendor/github.com/coreos/go-systemd/util/util.go, vendor/github.com/coreos/go-systemd/util/util_cgo.go, vendor/github.com/coreos/go-systemd/util/util_stub.go, vendor/github.com/coreos/pkg/LICENSE, vendor/github.com/coreos/pkg/NOTICE, vendor/github.com/coreos/pkg/dlopen/dlopen.go, vendor/github.com/coreos/pkg/dlopen/dlopen_example.go, vendor/vendor.json
For the case that systemctl start pouch, we need to make sure that the
pouchd has been started successfully. We cannot rely on the exit code
of systemctl only, we need to use NOTIFY_SOCKET to send the state to
the systemd.
For the case that **systemctl start pouch**, we need to make sure that the pouchd has been started successfully. We cannot rely on the exit code of systemctl only, we need to use NOTIFY_SOCKET to send the state to the systemd.
So when the pouchd has set up , it will send the state to systemd
fixes #1568 
none
none
=> feature: add systemd notify

apis/server/exec_bridge.go, apis/server/router.go, cli/exec.go, cri/v1alpha1/cri.go, cri/v1alpha1/cri_stream.go, cri/v1alpha2/cri.go, cri/v1alpha2/cri_stream.go, daemon/mgr/container.go, daemon/mgr/container_exec.go, test/cli_exec_test.go
when daemon deal with exec process get error, process will get stuck,
since http connection has been hijacked, it won't finish and return
with error message. Fix it by write error message into hijacked
connection, close io when process get error.
fixes: #1151
fixes: #1151
=> bugfix: fix exec stuck when exec get error

apis/server/image_bridge.go, cli/pull.go, ctrd/image.go, daemon/mgr/image.go, pkg/jsonstream/format.go, pkg/jsonstream/image_progress.go, pkg/jsonstream/stream.go, pkg/jsonstream/types.go, test/util_api.go
Since the existing swarm, mesos or other scheduled system maybe use the docker client to pull image from PouchContainer, PouchContainer should change data stream to help user to use PouchContainer.
It can help user to migrate to PouchContainer from docker.
fixes #1579
With original design, the PouchContainer uses the array as data packet in the stream. However, the docker client can only consume the json as one packet in the stream. Before this change, we will got the error like that:
```
docker -H {Pouch Daemon Host} pull busybox
json: cannot unmarshal array into Go value of type jsonmessage.JSONMessage 
```
In order to make it happen, we need to adjust data stream with one json object as packet.
Basically, we need to confirm the pouch cli does work well.
```
➜  ~ pouch pull ruby …
```
=> enhance: adjust data stream from pouch pull api

daemon/mgr/container.go
When the container failed to start, we should release the container resources, including network and containerio.
NONE
=> bugfix: release the container resources if contaienr failed to start

cli/network.go
enhance: display disconnect result for pouch network disconnect
Now If we disconnect a container from a network, it will display nothing. This PR will print the success message like
```
container test is disconnected from network bridge
```
NONE
NONE
if **pouch network disconnect** successfully, it will print success
=> enhance: display disconnect result for pouch network disconnect
