alibaba/pouch

README.md

doc: add apache license bar in README.md.
And it will make apache license more clear when reading.
NONE
NONE
NONE
NONE

doc: add apache license bar in README.md

---

.travis.yml
hack/make.sh

Signed-off-by: Ce Gao <ce.gao@outlook.com>
Update go version to 1.9.1 in Travis CI
Fixes #118 
Update the version in .travis.yml and set path to remove the hack in hack/make.sh
Run CI
nil

ci: Update go version to 1.9.1

---

FAQ.md

Signed-off-by:  HusterWan zirenwan@gmail.com
fix CONTRIBUTING.md reference address in FAQ.md

bugfix:fix CONTRIBUTING.md reference address in FAQ.md

---

Dockerfile
Makefile
apis/swagger.yml

Signed-off-by: codejuan <xh@decbug.com>
- Fixes `apis/swagger.yml`
- Add `swagger validate` in `Makefile`
Fixes #125
1. Fixes `apis/swagger.yml` 
2. Add `go get swagger` in `Dockerfile`
3. Add `swagger validate` in `Makefile`

fix: add swagger validate 

---

docs/pouch_with_tls.md

Signed-off-by: Frank Yang yyb196@gmail.com
add document for how to protect pouchd by using tls
code change is included in PR #40
fixes #66 
Now that pouch repository status has changed from private to public, old branch change cannot be received by old pr #66 , that is why this new pr is draft.
@allencloud @WIZARD-CXY @Letty5411 PTAL.

doc: add document for how to protect pouchd by using tls

---

apis/server/volume_bridge.go
cli/volume.go

Modify volume usage.
fixes #128 
fixes #129 

bugfix: modify volume usage

---

daemon/mgr/image.go
test/pouch_api_help_test.go
test/pouch_cli_help_test.go
test/pouch_cli_version_test.go
volume/driver/driver.go

fix code improvement
Signed-off-by: zhubingbing <zhubingbing10@gmail.com>
fix code improvement
fixes #124 
https://goreportcard.com/report/github.com/alibaba/pouch

bugfix: go report tells code needs improvement

---

docs/pouch_with_prometheus.md

docs: format and fix nits in monitoring
I think we need some tool to check and validate the markdown document. I remembered that there are some kind of tools to achieve this, but I don't remember the names. Could someone have experience and remind me?
NONE
NONE
NONE
NONE

docs: format and fix nits in monitoring

---

ROADMAP.md

This PR adds a ROADMAP.md file for project. More details, we could refer the content and file change of this PR.
fixes #12 
NONE
NONE
NONE

docs: add ROADMAP.md for Pouch project

---

CONTRIBUTING.md

Add test case contribution instruction in CONTRIBUTING.md.
No
None. Just for updating document. 
None
None

add test case contribution instruction

---

.travis.yml

Since when travisCI get cu failure, it will throw out a notification which has a format of 
```
{\"id\":306215418,\"number\":\"50\",\"config\":{\"dist\":\"trusty\",\"sudo\":\"required\",\"language\":\"go\",\"go\":[\"1.9.1\"],\"go_import_path\":\"github.com/alibaba/pouch\",\"notifications\":{\"webhooks\":{\"urls\":[\"http://121.201.13.205:6789/ci_notifications\"],\"on_failure\":\"always\",\"on_error\":\"always\"}},\"before_install\":[\"sudo apt-get update -qq\",\"sudo apt-get install -y -qq autoconf automake\"],\"script\":[\"sudo env \"PATH=$PATH\" hack/make.sh\"],\".result\":\"configured\",\"group\":\"stable\"},\"type\":\"pull_request\",\"state\":\"failed\",\"status\":1,\"result\":1,\"status_message\":\ …
```

fix: make travisCI has no double quote

---

daemon/mgr/container.go

make code ident less and return fast.
I think less ident will make code more readable and return fast could make codes structure much better.
NONE
NONE
NONE
NONE

refactor: make code ident less and return fast

---

CONTRIBUTING.md
FAQ.md
docs/pouch_with_prometheus.md

Signed-off-by:  ZeroMagic anthonyliu65535@gmail.com
fix the spelling mistakes in CONTRIBUTING.md and FAQ.md.
fix the error ip in docs/pouch_with_prometheus.md
No

typo: fixed some spelling mistakes

---

docs/pouch_with_prometheus.md

Signed-off-by: ZeroMagic anthonyliu65535@gmail.com
add document for how to specify port
fixes #157 

doc: add document for how to specify port

---

client/system.go
daemon/config/config.go
daemon/daemon.go

Fix grammatical issue

---

README.md

fixed some grammatical issues
fixed some grammatical issues in readme.md
NONE
fixed some grammatical issues
has checked...
..

Grammatical issues

---

ctrd/README.md
internal/generator.go

fix some typos
...
....
....
....

fix some typos and complete some comments

---

apis/server/container_bridge.go
apis/server/router.go
daemon/mgr/container.go
daemon/mgr/container_types.go

the commit is only used to define interfaces, not to implement.

feature: add container remove interface

---

test/pouch_cli_help_test.go

Add wrong args in pouch_cli_help_test.go
NONE
NONE
NONE
NONE

fix:Update pouch_cli_help_test.go

---

test/pouch_cli_create_test.go

NO
add a test case:TestPouchCreateDuplicateContainerName
cd pouch/test && go test
None

add TestPouchCreateDuplicateContainerName

---

test/pouch_cli_create_test.go

[DO NOT MERGE]fix: update test to fix pr 163

---

test/lib_common.go
test/lib_env.go
test/pouch_api_info_test.go
test/pouch_cli_create_test.go
test/pouch_cli_help_test.go
test/pouch_cli_images_test.go
test/pouch_cli_ps_test.go
test/pouch_cli_pull_test.go
test/pouch_cli_start_test.go
test/pouch_cli_stop_test.go
test/pouch_cli_version_test.go
test/pouch_cli_volume_test.go

Add demo test for CMD test. As the skeleton is similar, no need to pay much attention to the common test functions.

test : Add test demo for pouch CMD

---

docs/test/debug_in_travis.md

Add a document about how to use debug mode in TravisCI.

doc: add doc about how to debug in travis

---

docs/commandline/start.md

Add a document about "pouch start" command.

doc: add document for CMD pouch start

---

FAQ.md

Move what is Pouch to the top, since it is the most important one.
Clean up the language.

doc: clean up first two sections of FAQ

---

INSTALLATION.md

Fix typo found in the installation guide 

docs: typo fix for INSTALLATION.md

---

INSTALLATION.md

clean up the first section of quick start

doc: update quick start

---

Makefile

* Add missing prerequisites for .PHONY target
* Make a few tweaks for readability in future
Signed-off-by: Runrioter Wung runrioter@gmail.com

Add missing prerequisites for .PHONY target

---

apis/server/container_bridge.go
apis/server/router.go
apis/swagger.yml
cli/main.go
cli/rename.go
client/container.go
daemon/mgr/container.go

Signed-off-by: zeppp  zeppp1995@gmail.com
`pouch rename [container] [newName]`rename a container with new name.

feature:add pouch rename

---

cli/stop.go

add some descriptions and examples

fix: update stop.go to add cli long description and example

---

docs/test/test.md

Add doc about how to run pouch test.
Developing test part will be added later after more discussion.

doc: add test document

---

cli/start.go

update start.go by add descriptions and examples
None
..
try the process on my centos7

fix: update start.go by adding descriptions and examples

---

FAQ.md
apis/README.md

Fix some typos

---

CONTRIBUTING.md

Fixes issue for #210 according to comments listed
Fixes #210 

doc:remove [Git Flow] part in CONTRIBUTING.md

---

cli/pull.go

fix return code when pouch pull image occurred error
fixes https://github.com/alibaba/pouch/issues/237
```
[root@docker-registry github.com]# pouch pull docker.io/library/centos:ttt
docker.io/library/centos:ttt: resolving      |--------------------------------------|
elapsed: 0.4 s                total:   0.0 B (0.0 B/s)
Error: failed to pull image: docker.io/library/centos:ttt not found
[root@docker-registry github.com]# echo $?
1
```

bugfix: fix return code when pull image occurred error

---

apis/server/container_bridge.go
apis/server/router.go
daemon/mgr/container.go

bugfix: fix rename's bug

---

Makefile

Signed-off-by: Tao Qingyun <845767657@qq.com>
use `go env` for `GOPATH` and little cleanup in Makefile

clean Makefile to simplify env

---

pkg/ringbuff/ringbuff.go

bugfix: container has exited, the state is running

---

cli/rename.go

Signed-off-by: zeppp zeppp1995@gmail.com
fix a typo in rename.go

fix:fix typos in rename.go

---

cli/pull.go

update pull.go by adding description and example

fix: Update pull.go

---

apis/server/image_bridge.go
apis/server/router.go
apis/swagger.yml
cli/main.go
cli/rmi.go
client/image.go
ctrd/image.go
daemon/mgr/image.go
daemon/mgr/image_types.go
test/pouch_cli_rmi_test.go

add cli pouch rmi command
fixes https://github.com/alibaba/pouch/issues/268
```
[root@docker-registry github.com]# pouch rmi docker.io/library/nginx:latest
docker.io/library/nginx:latest
```

feature: add pouch rmi command

---

test/lib_common.go
test/lib_env.go
test/pouch_cli_version_test.go
vendor/github.com/gotestyourself/gotestyourself/LICENSE
vendor/github.com/gotestyourself/gotestyourself/icmd/command.go
vendor/github.com/gotestyourself/gotestyourself/icmd/exitcode.go
vendor/github.com/gotestyourself/gotestyourself/icmd/ops.go
vendor/vendor.json

Add a lib function: RunCmd. And a demo of usage in : pouch_cli_version_test.go.
With this function, user could fill a struct with their CMD and expected results, this function will execute CMD, check results and assert failure if there is error.
The usage is as following:
```
+	cmd = PouchCmd{
+		args:        "version",
+		result:      true,
+		outContains: "APIVersion",
+	}
+	RunCmd(c, &cmd)
```
A failure log is as following:
```
#go test -check.f PouchVersionSuite
▽
package main
----------------------------------------------------------------------
FAIL: pouch_cli_version_test.go:21: PouchVersionSuite.TestPouchVersion
pouch_cli_version_test.go:31:
RunCmd(c, &cmd)
lib_common.go:110:
// Add "(?s)" to match …
```

test: add RunCmd lib function to reduce the work of developing cli tests

---

FAQ.md

In community, lots of peopler ask me that what is difference between Pouch and Kubernetes.
Then I wrote the difference or relationship in FAQ.md
NONE
NONE
NONE
NONE

doc: add question of the difference between Pouch and Kubernetes

---

test/pouch_api_version_test.go

I add API /version test which includes status code checking, response content checking.
We need to add more integration test no matter API test or cli test.
NONE
NONE
NONE
NONE
/cc @Letty5411 @sunyuan3

test: add /version API test

---

README.md

- Revised wording.
- Cut repetitions.
- Remove trailing spaces.
fixes #162
Read through and adjust wording accordingly. Trailing spaces are removed automatically by VIM.
Please read through and see if the changes make sense.
None.

docs: revise README.md for better presentation.

---

cli/image.go
ctrd/image.go

make "pouch images" to show correct image's size.
fixes #
```
root@ubuntu:~/go/src/github.com/alibaba/pouch# pouch images
IMAGE ID       IMAGE NAME                                  SIZE
ded83fbb30d5   reg.docker.alibaba-inc.com/busybox:latest   2.66 MB
```

bugfix: the image's size is not correct

---

daemon/mgr/container.go
daemon/mgr/container_utils.go

This PR refactor the code in container.go. Every time when I read create function, I feel uncomfortable with this block of code.
So I make this pr encapsulates ID and name generation into container_utils.go
NONE
NONE
NONE
NONE

refactor: encapsulate ID and name generation

---

apis/server/container_bridge.go
cli/ps.go

show runtime in pouch ps.
```
$ sudo ./pouch ps
Name   ID   Status   Image   Runtime
```

feature: show runtime in ps command

---

apis/server/router.go
daemon/mgr/container.go
daemon/mgr/container_utils.go
daemon/mgr/image.go
pkg/errtypes/errors.go

Define the special errors, so it's better to control the logic and
state.
mgr is the core control layer, it should not contain the http state, because the http is a entry only and in the future, We will have the cri entry.  

refactor: define errors in pkg

---

docs/pouch_with_runV.md

This PR adds more details about pouch with runv. For example, for users, user experience is important. It provides one example to illustrate this.
NONE
NONE
NONE
NONE

doc: polish runv doc with hypervisor-based container exeperience

---

apis/server/container_bridge.go
apis/server/router.go
apis/swagger.yml
cli/main.go
cli/pause.go
client/container.go
ctrd/container.go
daemon/mgr/container.go

add the new feature to pause a running container
run the test on my centos

feature: add pause feature

---

ctrd/container.go

ctrd/container.go:247:10: undefined: ErrTrylockFailed

bugfix: fix the compile error

---

hack/make.sh
test/lib_common.go
test/pouch_cli_create_test.go
test/pouch_cli_help_test.go
test/pouch_cli_images_test.go
test/pouch_cli_ps_test.go
test/pouch_cli_rmi_test.go
test/pouch_cli_start_test.go
test/pouch_cli_version_test.go
test/pouch_cli_volume_test.go

1. fix an error in RunCmd,
2. use RunCmd in cli related tests
3. add pull busybox image in hack/make.sh, because of issue#313, pull CMD can't be called successfully in test code.

test: use RunCmd function

---

INSTALLATION.md

fix dead link about runv in INSTALLATION.md
fixes #323 
NONE
NONE
/cc @jumping

doc: fix dead link about runv in INSTALLATION.md

---

ctrd/image.go

Fix bug: The image should support sha256, sha512 or other no-registered algorithms.
https://github.com/opencontainers/image-spec/blob/master/descriptor.md#digests 
None
Follow the image-spec.
None
None

fix: image digest supports several algos, not just sha256

---

apis/server/container_bridge.go
apis/server/router.go
apis/swagger.yml
cli/main.go
cli/unpause.go
client/container.go
ctrd/container.go
daemon/mgr/container.go
daemon/mgr/container_types.go
test/pouch_cli_unpause_test.go

feature:add unpause command

---

cli/image.go
cli/pull.go
cli/rename.go
cli/start.go
cli/stop.go
cli/version.go

update descriptions and examples of cmd
NONE

fix: update descriptions and examples of cmd

---

ctrd/container.go

when failed to execute a process in container,  need to output the error informat to "cli"
./pouch exec -ti 9de6a7 ps
starting container process caused "exec: \"ps\": executable file not found in $PATH": unknown
fix #339 

bugfix: make "pouch exec" to output the error info

---

cli/volume.go

Add volume cli comments, it is used to generate cli docs.

volume: add volume cli comments

---

daemon/spec/container_spec.go
daemon/spec/namespace.go
daemon/spec/spec.go

namespace handler be used to set the namespaces of spec. In the future, we need to enhance them.

feature: add namespace handlers

---

test/pouch_api_create_test.go
test/request/request.go

Add two test lib functions to construct Query and Body fields in request. 
Add positive test for /containers/create API.

test: add WithQuery and WithJsonBody lib function, add create api test

---

test/pouch_api_container_create_test.go
test/pouch_api_container_inspect_test.go
test/pouch_api_container_list_test.go

Add test for container inspect/list APIs.

test: add container list\inpect api test

---

apis/server/container_bridge.go
apis/swagger.yml
cli/stop.go
client/container.go
ctrd/container.go
daemon/mgr/container.go
daemon/mgr/container_types.go
test/pouch_cli_stop_test.go

Add timeout in stop command
Signed-off-by: mozhuli <21621232@zju.edu.cn>

fix: add timeout in stop command

---

test/pouch_api_container_create_test.go
test/pouch_api_container_delete_test.go
test/pouch_api_container_pause_test.go
test/pouch_api_container_rename_test.go
test/pouch_api_container_stop_test.go
test/pouch_api_image_delete_test.go
test/request/request.go

add pause/stop/rename api tests

test: add pause/stop/rename/ api tests

---

hack/make.sh
test/pouch_api_container_start_test.go
test/pouch_api_image_create_test.go
test/pouch_api_image_list_test.go
test/pouch_api_volume_create_test.go
test/pouch_api_volume_delete_test.go
test/request/request.go

test: add start api test

---

apis/swagger.yml

Cmd could only be an array of string. So I update swagger.yml to make it correct.
NONE
NONE
NONE
NONE

doc: remove an improper description in cmd

---

test/api_container_create_test.go

test: add more /containers/create api tests

---

test/api_container_create_test.go
test/api_container_start_test.go

test: add more /container/name/start tests

---

test/api_container_stop_test.go

test:add stop api tests

---

test/api_container_inspect_test.go

test:add inspect api tests

---

cli/inspect.go

Fix typo in image inspect command
NONE
NONE
NONE
NONE

fix: fix typo in image inspect cli

---

test/api_container_pause_test.go

test: add pause api tests

---

test/api_container_delete_test.go

test:add delete api tests

---

pkg/randomid/id_test.go

This pr is about to add unit test for `Generate` function in randomid pkg.
"None"
Just assert the length of id generated by `Generate` is `64`
run "make unit-test"
"None"

test: add unit test case for func Generate

---

hack/make.sh

Create the integration-cli test binary.  Avoid setting up golang environment in host.
No
Build integration cli test binary in container and execute the binary in host.
hack/make.sh
None

test: create the integration-cli test binary

---

apis/swagger.yml

This is a fix PR of https://github.com/alibaba/pouch/pull/403. In the original code, api.md generation fails because the invalidness of swagger.yml content.
Issue was found via https://github.com/alibaba/pouch/pull/403
NONE
NONE
NONE

fix: make swagger.yml doc generation errorless

---

apis/server/router.go
cli/pull.go

Signed-off-by: Tiramisu 1993 <sabergeass@gmail.com>
Fix `typo` and `unrecognized printf verb` based on go report of pouch in https://goreportcard.com/report/github.com/alibaba/pouch
None
Just address them based on go report
run `make unit-test`
Haven't fix the `cyclomatic complexities` on the report. Not sure if it's necessery to be addressed.

refactor:fix nits based on go report

---

cli/run.go

runExample fix: there is one example lost $ before cli command

bugfix: fix run Example

---

cli/run.go

use -ti to run a bash in container, when we type "exit" command, the cli
don't exit util type other characters via keyboard.

bugfix: when exit the running container, the cli don't stop forever

---

CODE_OF_CONDUCT.md

This PR adds CODE_OF_CONDUCT.md for pouch. This file is all provided via GitHub.
NONE
NONE
NONE
NONE

doc: Create CODE_OF_CONDUCT.md

---

.travis.yml
hack/make.sh

Create multi targets in hack/make.sh.
No
Add multi targets in hack/make.sh.
hack/make.sh check
hack/make.sh build
hack/make.sh check build unit-test
hack/make.sh check build unit-test integration-cli-test
None

test: enable hack/make.sh check build unit-test integration-cli-test

---

ctrd/container.go

this commit can make pouch run with runv successful

[workaround fix]: fix runv can not run with pouch

---

hack/make.sh

print daemon log if test is failed
None
if integration test is failed, print daemon log.
hack/make.sh
None

test: print daemon log if test is failed

---

test/api_container_create_test.go
test/api_container_delete_test.go
test/api_container_exec_test.go
test/api_container_inspect_test.go
test/api_container_list_test.go
test/api_container_pause_test.go
test/api_container_rename_test.go
test/api_container_start_test.go
test/api_container_stop_test.go
test/request/request.go
test/utils.go

Add container related functions for test.
It now prints more info when the response status is not as expected.

test: add container related util functions

---

test/api_container_start_test.go
test/request/request.go

Add two /container/name/start api tests.

test: add api start tests

---

hack/make.sh
test/api_image_create_test.go

Add an image test
Add "-check.v" args to print verbose info when run integration test.

test: add image api tests

---

.travis.yml
Makefile

add test in Makefile
No
add test and integration-test in Makefile
make integration-test
make test
None

test: add test in Makefile

---

daemon/containerio/container_io.go
daemon/mgr/container.go

define a Close() function to close the container's stdio(stdin, stdout, stderr)

refactor: define a Close() function to close the container's stdio(stdin, stdout, stderr)

---

ctrd/container.go
ctrd/watch.go
daemon/mgr/container.go

refactor:  remove useless fields from ctrd.Message struct

---

apis/swagger.yml

This PR adds `POST /containers/{id}/attach` in swagger.yml.
NONE
NONE

fix: add attach API in swagger.yml

---

test/api_container_create_test.go
test/api_container_exec_test.go
test/api_container_start_test.go
test/api_container_stop_test.go

Add api test for exec/create/stop

test: add api test for exec/create apis

---

.gitignore
Makefile
hack/build

Make pouch build in independent GOPATH, so it no need to let pouch
source in '$GOPATH/src/github.com/alibaba/pouch', it put source code
in anywhere.
use separate directory as GOPATH, don't use system GOPATH
The method of build pouch is same as before. 'make' or 'make build', 'make check', 'make test' and so on.

refactor: make pouch build in independent GOPATH

---

daemon/mgr/cri.go

We may use the following method to verify that we can use pouch to run a pod:
```
{
"metadata": {
"attempt": 1,
},
"linux": {
}
}
53bfc944e2e6b391089d441d364e9fea98ea4a51c882d831f5a83d5fd0803162
[root@pouch-test cri-tools]# …
```

feature: implement basic RunPodSandbox method for cri manager

---

test/api_container_attach_test.go

Add attach test to test attach a non existing container return 404.
As of issue #470 , the return code is 200 now. Later, when this issue is fixed, test should also be changed.

test: add attach test to test attach a non existing container return 404

---

ctrd/container.go
ctrd/image.go
daemon/mgr/container.go
daemon/mgr/container_types.go
daemon/mgr/spec_process.go

igned-off-by: skoo87 <marckywu@gmail.com>

feature: add GetImageConfig for ctrd and store Image's config into container meta 

---

daemon/mgr/cri.go

fixes part of #420
We may use the following method to verify that we can pull and list images:
```
[root@pouch-test pouch]# crictl pull docker.io/library/redis:alpine
[root@pouch-test pouch]# crictl images
IMAGE                       TAG                 IMAGE ID            SIZE
docker.io/library/redis     alpine              0153c5db97e58       10.1MB
```

feature: implement PullImage and ListImages methods for cri manager

---

test/api_network_create.go
test/api_network_delete.go
test/utils.go

test: add network api test

---

cli/exec.go

pouch create registry.hub.docker.com/library/busybox:latest
pouch exec -i a70c6e /bin/sh  
will be stuck.
fix #377 

bugfix: exec process may be stuck

---

cli/container.go
cli/create.go
cli/run.go
daemon/mgr/container.go
daemon/mgr/container_types.go
test/cli_start_test.go

feature: add --env option for container

---

apis/server/container_bridge.go
cli/container.go
cli/create.go
cli/run.go
test/cli_create_test.go

feature: add --label option for container

---

cli/container.go
cli/create.go
cli/run.go
ctrd/container.go
test/cli_start_test.go

feature: add --entrypoint and --workdir options for container

---

docs/pouch_with_cri_verification.md

This PR adds pouch cri validation details
This is related to https://github.com/alibaba/pouch/issues/474
NONE
NONE
NONE

docs: add docs about verify pouch cri

---

daemon/mgr/cri.go

We may use the following method to verify that we can create and start container in sandbox:
```
{
"metadata": {
"attempt": 1,
},
"linux": {
}
} …
```

feature: implement CreateContainer and StartContainer method for cri manager

---

daemon/mgr/spec_volume.go

fix: correct the configuration of mounts

---

cli/container.go
cli/create.go
cli/run.go
daemon/mgr/spec_namespace.go
test/cli_start_test.go

feature: add hostname option for container

---

cli/container.go
cli/create.go
cli/run.go
daemon/mgr/spec.go
daemon/mgr/spec_cgroup_cpu.go

include --cpu-share, --cpuset-cpus and --cpuset-mems

feature: add cpu options for container

---

test/api_container_exec_start_test.go
test/environment/env.go
test/request/request.go
test/utils.go

Add test for exec start API. Also add Hijack functions.
Now the CI still fails, due to a 101 request code, still need to debug.

test: add exec start test

---

apis/swagger.yml
apis/types/container_config.go
daemon/config/config.go
daemon/mgr/container.go
lxcfs/lxcfs.go
main.go
test/api_container_create_test.go

Add lxcfs to make Pouch feel more like a real independent system
fixed #140 
1. Add lxcfs flag to pouchd, and start lxcfs process by pouchd
1. Add `EnableLxcfs` to struct ContainerConfig
1. If `EnableLxcfs` of ContainerCreateConfig is true, then bind lxcfs proc files to container(https://github.com/alibaba/pouch/issues/140#issuecomment-347425189)
1. install and stop lxcfs
```
apt-get install lxcfs
service lxcfs stop
```
2. start pouchd with lxcfs
```
pouchd --enable-lxcfs=true --lxcfs=/usr/bin/lxcfs
```
3. create a container with lxcfs
```
curl --unix-socket  /var/run/pouchd.sock -H "Content-Type: application/json"   -d '{"Image": …
```

feature: support lxcfs

---

hack/make.sh

Add test support for lxcfs.
Fix issue #522

test: support lxcfs test in CI

---

CONTRIBUTORS
hack/generate-contributors.sh

This PR added a way to generate contributors file.
NONE
Use a shell script to use git log content to generate contributors.
NONE
NONE

feature: add contributors generation to pouch

---

daemon/mgr/cri.go

We may use the following method to verify that we can stop, remove and list container in sandbox:
```
{
"metadata": {
"attempt": 1,
},
"linux": {
}
} …
```

feature: implement StopContainer, RemoveContainer and ListContainers of cri manager

---

daemon/mgr/cri.go
daemon/mgr/cri_test.go
daemon/mgr/cri_utils.go

Move help functions of cri manager to cri_utils.go and add some unit tests for them in cri_test.go

test:basic unit test for cri manager

---

test/cli_exec_test.go

add test for CLI exec.
Due to issue #536 , CI fails now.

test: add CLI exec test

---

cli/network.go
client/network.go

add network remove implementation on cli and client side
fixes part of #218 

feature: add network remove implementation on cli and client side

---

daemon/mgr/cri.go

We may use the following method to verify that we can stop and remove sandboxes:
```
{
"metadata": {
"attempt": 1,
},
"linux": {
}
} …
```

feature: implement StopPodSandbox and RemovePodSandbox of cri manager

---

test/cli_create_test.go

Add two create tests to test `-e` and `-w` options.

test: add create CLI tests

---

main.go

Please make sure you have read and understood the contributing guidelines;
https://github.com/alibaba/pouch/blob/master/CONTRIBUTING.md -->
try to find containerd binary named "containerd" in linux path(/usr/bin,/usr/local/bin...) first, and it could be overridden by  `--containerd-path` 

bugfix: find containerd binary in linux path first

---

daemon/config/config.go
main.go

pouchd do not need config of containerd(/etc/containerd/config.toml)

[refactor]remove containerd config dependency

---

hack/make.sh

docker container should be removed after test.
fix #566 

test: remove docker container after test

---

daemon/mgr/system.go
test/cli_version_test.go
version/version.go

change "GOVersion" to go1.9.1
NONE

fix: change "GOVersion" to go1.9.1

---

version/version.go

change Pouch version to "0.1.0-rc0"
NONE

fix: change Pouch version to "0.1.0-rc0"

---

Makefile

fix can't 'make client'.
when make client, it causes this error:
```shell
./hack/build: line 40: cd: /tmp/pouchbuild/src/github.com/alibaba/pouch: No such file or directory
go build -o pouch github.com/alibaba/pouch/cli
can't load package: package github.com/alibaba/pouch/cli: cannot find package "github.com/alibaba/pouch/cli" in any of:
/usr/local/go/src/github.com/alibaba/pouch/cli (from $GOROOT)
/tmp/pouchbuild/src/github.com/alibaba/pouch/cli (from $GOPATH)
/tmp/pouchbuild/src/github.com/docker/libnetwork/Godeps/_workspace/src/github.com/alibaba/pouch/cli
Makefile:27: recipe for target 'client' failed
make: *** [client] Error 1
```
'make client' need depend 'pre' in Makefile. …

bugfix: fix can not make client

---

cli/pull.go

image pull ARGS should be: "Args: cobra.ExactArgs (1),"
change `"Args: cobra.MinimumNArgs(1),  "` into  `"Args:cobra.ExactArgs(1), "`
NONE
change `"Args: cobra.MinimumNArgs(1),`  " into  `"Args:cobra.ExactArgs(1), "`
NONE
https://github.com/alibaba/pouch/blob/master/cli/pull.go#L38
This line of code has a bug and should be:` "Args: cobra.ExactArgs (1),"`

bugfix：image pull ARGS should be: "Args: cobra.ExactArgs (1),"

---

test/api_image_create_test.go
test/cli_start_test.go

This fix workaround issue #569 and #583 .
This fix only make sure these tests pass on CentOS. The above two issues still need to be investigated.

test: workaround issue#569 issue#583

---

CHANGELOG.md
version/version.go

This PR is submitted before pouch release 0.1.0.
Before released, we need to update the Version variable in code.
And we need to update the CHANGELOG to fit the thing we did.
NONE
NONE
NONE
NONE

doc: add release version and changelog

---

test/api_network_inspect_test.go

add network api test on inspect feature

test: add network inspect api test

---

README.md

This PR polishes the README.md of Pouch.
This PR adds a new feature in it and move rich container ahead of P2P image distribution.
NONE
NONE
NONE
NONE

doc: polish features within Pouch's README.md

---

daemon/mgr/volume.go
test/api_volume_delete_test.go

In PR https://github.com/alibaba/pouch/pull/585, we found that volume inspect will never return status code 404. So this PR tries to return 404 status code.
None
None
None
None

fix: make remove and inspect volume return 404 when not found

---

cli/network.go
cli/volume.go

This pr removes unnecessary variables on cli network and volume side and update the volume inspect example.
NONE

fix: remove unnecessary variables and update the volume inspect example

---

hack/install_lxcfs_on_centos.sh
hack/make.sh

Install lxcfs on CentOS from source code.
fix #567 

test: add install lxcfs script for CentOS

---

daemon/mgr/cri.go
daemon/mgr/cri_utils.go
hack/cri-test/test-cri.sh

1. Pull the sandbox image if it doens't exist.
2. Integrate "basic sandbox operation" test into CI.

feature: pull sandbox image if it doesn't exist and complete basic sandbox operation

---

hack/make.sh

test: fix install_lxcfs_on_centos.sh path error

---

volume/modules/ceph/map.go

using the` fast return `approach,make the code less indentation, in order to improve the readability of the code.
NONE
NONE
NONE
NONE

refactor:using the fast return approach，make the code less indentation.

---

INSTALLATION.md

describe how to install pouch on Centos7
NONE

doc: install pouch on centos7

---

INSTALLATION.md

fix doc
NONE
source code build and ./pouch images ls
NONE

fix: unknown command "ls" for "pouch images"

---

daemon/mgr/cri_test.go

test: add filter cri sandbox test

---

daemon/mgr/cri_test.go

test: add cri parse container name test and filter container test

---

daemon/mgr/cri.go

We may use the following method to verify that we can execSyn container:
```
{
"metadata": {
"attempt": 1,
},
"linux": {
}
}
bf1b6fc8cf9ec4c496fe620f1df101266208203bc73f3e01ef2cb7027fd7cec3
[root@pouch-test cri-tools]# cat container-config.json 
{
"metadata": {
"name": "busybox"
},
"image":{
"image": …
```

feature: implement execSync of cri manager

---

apis/swagger.yml
apis/types/resources.go

We wish to add more advanced container option to pouch container. This helps container to be isolated better than usual containers.
Actually pouch has a plan to support more advanced options in container, network, volume and other managed objects. This pr only lists some container's options.
This PR is WIP. We need to add more accurate description to these added fields.
Also, most of these options need to be applied in runC. But I think containerd can be transparent.
None
Add more advanced options for container.
None
None

[DO-NOT-MERGE]feature: add more advanced container options in pouch

---

docs/architecture.md

fix typo in architecture.md
fixes https://github.com/alibaba/pouch/issues/621
NONE
NONE
NONE

docs: fix typo in architecture.md

---

FAQ.md
docs/features/pouch_with_rich_container.md

Rich container is one of killing features in Pouch. It helps technical staff to complete packaging fat applications almost with no effort.
This PR adds document for rich container. And I try to describe `rich container` in the following aspects:
* intriduction
* scenario
* get started
* underlying implemention
Some places in this document is not complete. I will add them in follow-ip PR. Or you may think we can add some fields in this PR. It is totally OK. Please let me know, if there are improvement on that.
This may help some when you implement this in cli or daemon side. @wangforthinker 
none
none
**4.Describe how to verify …

docs: add rich container document

---

cli/container_test.go
cli/volume_test.go
client/client_test.go
ctrd/client_test.go
daemon/containerio/cache_test.go
daemon/mgr/container_utils_test.go
daemon/mgr/cri_utils_test.go
daemon/mgr/network_test.go
pkg/client/httpcli_test.go
pkg/client/url_test.go
pkg/exec/command_test.go
pkg/httputils/http_utils_test.go
pkg/reference/regexp_test.go
pkg/utils/tls_test.go

We added CodeCov to analyze the unit test coverage of this repo. While we can see that the unit test coverage is not so large, see:
```diff
@@            Coverage Diff             @@
==========================================
+ Coverage   14.21%   14.25%   +0.03%     
==========================================
Files          65       65              
Lines        3736     3719      -17     
==========================================
- Hits          531      530       -1     
+ Misses       3159     3143      -16     
Partials       46       46
```
The Coverage is only about 14.0 %. This PR tries to add more unit test framework code in Pouch to help finish more unit test.
All these code are auto …

test: add more framework unit test code for pouch

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

This PR polishes the PR and issue templated.
None
None
None
None

docs: improvement for github templates

---

hack/build

CI can't detect unit test error. Even if unit test is failed, travis ci is paas. This PR it to fix the issue.
Yes
Add "set -e " in hack/build.
make unit-test

fix: can't detect unit test error

---

hack/make.sh

Use `pouch version` to check if the pouchd has been started.
As there may be legacy pouchd socket file.
fix issue#670

test: user pouch version to check the status of pouchd

---

test/cli_run_test.go
test/cli_volume_test.go

test:add volume tests

---

test/cli_volume_test.go

test: add volume selector test

---

test/cli_network_test.go
test/cli_volume_test.go

test: add network tests

---

ctrd/image_proxy_util.go
ctrd/utils.go
daemon/config/config.go
daemon/daemon.go
main.go

pull image always stucks in grpc stream transport, do not merge now.
https://github.com/containerd/containerd/issues/2060
this is related to https://github.com/alibaba/pouch/issues/103.

feature: add dragonfly as a http proxy for pulling image

---

daemon/mgr/container.go
daemon/mgr/cri.go
daemon/mgr/cri_utils.go
daemon/mgr/spec_volume.go
hack/cri-test/test-cri.sh

It has already passed the corresponding tests in cri-tools.

feature: volume and mount propagation for cri manager

---

cli/blkio.go
cli/blkio_test.go

This PR adds some unit test cases for blk.
It also polishes some validation error message in blk.
NONE
NONE
NONE
/cc  @Letty5411 @Ace-Tang

test: add blk test cases

---

ctrd/container_lock.go
ctrd/container_lock_test.go

This PR adds unit test cases for container_lock.go.
none
none
none
none

test: add unit test for container lock

---

test/api_network_create.go
test/api_network_inspect_test.go
test/api_network_list_test.go
test/cli_network_test.go
test/utils.go

When creating bridge network, `subnet` and `gateway` should be specified.

test: fix network test wrong usage

---

cli/volume_test.go
daemon/mgr/network_test.go

test: add unit test for network

---

hack/make.sh

Add -y option to avoid interrupt automation.
Yes.
"Apt get install" command would interrupt automation test.
Do you want to continue? [Y/n] 
add -y option
make test
NA

add -y option to avoid interrupt automation

---

cli/create.go
cli/exec.go
cli/image_inspect.go
cli/image_list.go
cli/inspect.go
cli/network.go
cli/pause.go
cli/ps.go
cli/pull.go
cli/rename.go
cli/rm.go
cli/rmi.go
cli/run.go
cli/start.go
cli/stop.go
cli/unpause.go
cli/version.go
cli/volume.go
client/container.go
client/image.go
client/network.go
client/request.go
client/system.go
client/volume.go
test/cli_images_test.go
test/environment/cleanup.go

feature: add context in pouch cli

---

daemon/mgr/container.go
daemon/mgr/container_utils.go
daemon/mgr/container_utils_test.go

This PR adds test cases for file container_utils.go.
None
None
None
None

test: add unit test for container utils

---

cli/common_flags.go
cli/create.go
cli/run.go
docs/commandline/pouch_create.md
docs/commandline/pouch_run.md

We know that command run and create have lots of common flags. And we do not wish to repeat ourselves. So I combine these flags into one copy.
None
None
None
/cc @Ace-Tang @Letty5411

refactor: combine command run and create's flags

---

daemon/mgr/cri.go
daemon/mgr/cri_network.go
daemon/mgr/cri_utils.go
hack/cri-test/test-cri.sh

This PR implement port mapping in CRI manager by using CNI port map plugin.
fixes part of #635

feature: port mapping for cri manager

---

cli/cli.go
client/client.go
client/container.go
client/image.go
client/interface.go
test/main_test.go
test/request/request.go

refactor: abstract common api client

---

test/cli_create_test.go
test/cli_exec_test.go
test/cli_images_test.go
test/cli_network_test.go
test/cli_ps_test.go
test/cli_start_test.go
test/cli_stop_test.go
test/cli_unpause_test.go

Add explicitly remove container operation in each test where container is created.
We should not rely on the cleanup function to do all work.

test: add cleanup for test

---

volume/core.go

fix create volume failed, but metadata is stored.
fixes #703 
storing metadata after creating volume successfully.
```bash
Error: {"message":"mount path is not a dir /tmp/test6"}
1
Name:
pouch-volume
```

bugfix: fix create volume failed but metadata is stored

---

pkg/bytefmt/bytefmt_test.go

test: add unit test for bytefmt

---

INSTALLATION.md

describe how to install pouch on ubuntu16.04
NONE
NONE

doc: install pouch on ubuntu

---

daemon/mgr/container.go

Network device is remaining after container have been removed.
Adding "markStoppedAndRelease" after have called "client.DestroyContainer".
fixes #758 
The test steps are same as issue steps.

bugfix: network device is remaining after container have been removed

---

daemon/mgr/cri.go
daemon/mgr/cri_network.go

Signed-off-by: YaoZengzeng <yaozengzeng@foxmail.com>
fixes #748

feature: complete functions of cni manager

---

apis/server/image_bridge.go
cli/login.go
cli/pull.go
client/container.go
client/image.go
client/interface.go
client/network.go
client/request.go
client/system.go
client/volume.go
credential/config_file.go
credential/credential.go
credential/file_store.go
credential/helpers.go
credential/helpers_test.go
credential/store.go
ctrd/image.go
ctrd/utils.go
daemon/mgr/cri.go
daemon/mgr/cri_utils.go
daemon/mgr/image.go
main.go
registry/auth.go

1. credential directory include something about registry
username/password storage.
2. add credential infomations in pull image process.
3. remove default proxy http://0.0.0.0/5678. if proxy server
not exist, image pull will get error.
1. credential directory include something about registry
username/password storage.
2. add credential infomations in pull image process.
3. remove default proxy http://0.0.0.0/5678. if proxy server
not exist, image pull will get error.

feature: support pull image with authentication

---

client/container.go

update client request.post params change fix

bugfix: client request.post params change fix

---

client/container.go

update client request.post params change fix

bugfix: update client request.post params change fix

---

hack/make.sh
hack/package/build.sh

In build.sh, replace opencontainers/runc to alibaba/runc to support rich container mode.

feature: replace opencontainers/runc to alibaba/runc

---

test/cli_alikernel_test.go
test/cli_network_test.go
test/cli_run_test.go
test/cli_volume_test.go
test/environment/env.go

1. add test for group disk quota
2. fix test error in cli_network/volume_test.go
3. add tests for network CLI to test #758

test: add aliKernel specified tests

---

hack/package/deb/Makefile

replace opencontainers/runc to alibaba/runc
NONE

fix: replace opencontainers/runc to alibaba/runc

---

cli/logout.go
cli/main.go
credential/credential.go
credential/file_store.go
credential/store.go

add a logout command, use for logout from a registry

feature: add logout command

---

test/cli_alikernel_test.go
test/cli_network_test.go
test/cli_run_test.go
test/cli_volume_test.go
test/environment/env.go

test: merge test fix to branch 0.2.x

---

daemon/mgr/system.go
version/version.go

change pouch version to 0.2.0
fixes #789

fix: change pouch version to 0.2.0

---

cli/update.go
daemon/mgr/container.go
test/cli_create_test.go
test/cli_exec_test.go
test/cli_help_test.go
test/cli_images_test.go
test/cli_network_test.go
test/cli_ps_test.go
test/cli_pull_test.go
test/cli_rmi_test.go
test/cli_start_test.go
test/cli_stop_test.go
test/cli_unpause_test.go
test/cli_update_test.go
test/cli_version_test.go
test/cli_volume_test.go

1. optimize update interface, add more test case
2. fix some words spelling mistakes

feature: optimize update interface

---

hack/build

Fix a bug in hack/build.
When run unit-test as following:
```
./hack/build pre
echo unit-test
./hack/build unit-test
```
As shown it calls ./hack/build unit-test to run unit-test. But it will run test for vendor/xxx, skip it.

test: fix unit-test error

---

INSTALLATION.md

Fix link typo
No
Just fixed it
Review markdown file
Nope

INSTALLATION.md: Fix runv link

---

test/cli_alikernel_test.go
test/cli_create_test.go
test/cli_images_test.go
test/cli_ps_test.go
test/cli_pull_test.go
test/cli_rmi_test.go
test/cli_run_test.go
test/cli_start_test.go
test/cli_stop_test.go
test/cli_unpause_test.go
test/cli_update_test.go
test/cli_version_test.go

Signed-off-by: HusterWan zirenwan@gmail.com
fix test case

test: fix ci test

---

CHANGELOG.md

This is a PR for 0.2.0 releasing. This added changelog of this new version
none
None
None
None

docs: add changelog for 0.2.0

---

INSTALLATION.md

modify apt repository url
NONE

doc: modify apt repository url

---

daemon/mgr/system.go
version/version.go

Add `Version` and `CommitID` in version.go
NONE

fix: add pouch version information

---

cli/exec.go
daemon/mgr/container.go
daemon/mgr/container_types.go
daemon/mgr/spec_process.go
pkg/user/user.go
pkg/user/user_test.go
test/cli_run_test.go
test/cli_start_test.go

add user implement like format uid[user]:gid[group]
support command pouch exec -u and pouch create -u
add user implement like format uid[user]:gid[group]
support command pouch exec -u and pouch create -u

feature: add user flag implement in pouch create and exec

---

daemon/config/config.go
main.go
pkg/utils/tls.go
pkg/utils/utils.go
pkg/utils/utils_test.go

Add daemon configuration file for pouch, so there is two ways for set config, command line and config file.
Notice that, a flag can not be set in two places simultaneously.

feature: add pouch daemon config file

---

test/cli_run_test.go

If we run a container with specified memory limit, such as 100m. Then the cgroup file `/sys/fs/cgroup/memory/default/958d21385c13811bbd4c604061edde942d98f13e4640fce2d4e101edc82a52a1/memory.limit_in_bytes` would have a value of `104857600`.
The this test tests this points. 
For every aspect of resource limitation, we need to test two aspects:
1. the value in `pouch inspect container_id`'s response body;
2. the value in cgroup filesystem files.
/cc @Letty5411 
None
None
```
root@ubuntu:~/go/src/github.com/alibaba/pouch/test# go test -check.f PouchRunSuite.TestRunWithLimitedMemory
OK: 0 passed
PASS
ok  	github.com/alibaba/pouch/test	0.055s
```
None

test: add container memory limitation validness checking

---

docs/architecture.md

Hi, this PR fixes some minor typos in architecture doc.
@allencloud PTAL, thanks!

docs: fix typos in architecture doc

---

cli/common_flags.go
cli/update.go
hack/build
hack/make.sh
test/cli_run_test.go

1. fix issue #820
2. add tests for resource
3. depress the output of make build
fixes #820

test: add resource check test and fix a typo error in cli

---

cli/update.go

Signed-off-by: Cindy <176425810@qq.com>
fix: update command args to be exact one
none
fix a line of code.

fix: update command args to be exact one

---

docs/features/pouch_with_rich_container.md
hack/make.sh
test/cli_rich_container_test.go
test/environment/env.go

test: add rich container test

---

hack/make.sh
hack/package/README.md
hack/package/deb/Makefile
hack/package/deb/build.sh
hack/package/deb/ubuntu-xenial/Dockerfile.x86_64
hack/package/package.sh
hack/package/rpm/build.sh
hack/package/rpm/centos-7/Dockerfile.x86_64

Optimize the way of packaging
NONE

fix: optimize the way of packaging

---

Makefile
hack/build

bug: fix Makefile bug and speed up unit test

---

test/cli_run_test.go

test: add blkio test

---

docs/features/pouch_with_dragonfly.md

add docs to describe how to run pouch with dragonfly
fixes #103

docs: integrate pouch with dragonfly

---

hack/cri-test/test-cri.sh

bugfix: skip the cri test for attach

---

hack/package/package.sh

Use host network when use docker, in case there is networking error.

bugfix: use host network when build package

---

test/cli_run_test.go

test: add test skeleton for alikernel flags

---

cli/exec.go

fix: close net connection in exec process

---

README.md

After discussing, we decided to define Pouch to be an efficient enterprise-class rich container engine.
And I make feature rich container to be ahead of isolation, since we think it is the most important feature to help enterprises to containerize huge legacy applications with a very fast speed. 
I also remove the stability and simplicity.

docs: update README.md to make title and feature clear

---

daemon/config/config.go
main.go
pkg/kernel/kernel.go
pkg/kernel/kernel_test.go
pkg/quota/grpquota.go
pkg/quota/prjquota.go
pkg/quota/quota.go
version/version.go
volume/modules/local/local.go

On version 0.2.1, it will fix the following issues：
1. issue #784 
2. issue #798

cherry-pick commits from master to 0.2.1

---

MAINTAINERS.md

Change my name, Huster is not so good :)

doc: change my name in MAINTAINERS

---

pkg/quota/grpquota.go
pkg/quota/prjquota.go

fix project quota can't be set on alikernel-4.9, and adding some debug
logs.

bugfix: fix project quota can't be set on kernel-4.9

---

CHANGELOG.md

doc: add changelog for version 0.2.1

---

.gitignore

add some git ignore type in .gitignore file

add some type in .gitignore

---

apis/server/router.go
client/client.go
client/request.go
test/api_version_parameter_test.go
test/request/request.go

pouch restful api url support version param
execute cli command
```
root@osboxes:pouch (zr/support-version *%) -> pouch ps
Name     ID       Status      Created      Image                                            Runtime
test-2   c84122   Up 3 days   3 days ago   registry.hub.docker.com/library/busybox:latest   runc
```
pouchd logs
```
DEBU[2018-03-12 01:59:18.674256594] Calling GET /v0.2.0/images/json, client @
```

feature: pouch restful api url support version param

---

apis/server/container_bridge.go
apis/server/router.go
apis/swagger.yml
cli/main.go
cli/restart.go
client/container.go
client/interface.go

feature: add restart skeleton

---

cli/top.go

docs: fix typo

---

INSTALLATION.md

`mirrors.cloud.aliyuncs.com` is an address used for aliyun vpc and inner network. Although we have test pouch installation in alibaba and alibaba ecs, but we still do not trigger the bug that outer internet address can not access this address.
So this PR changed this address to `mirrors.aliyun.com`.
none
change valid internet accessible address.
none

doc: fix the repository URL

---

test/api_system_test.go
test/cli_images_test.go
test/environment/env.go
test/util/util.go
test/utils.go

add cli/api test for login/logout command

test: add test for login/logout

---

apis/plugins/ContainerPlugin.go
apis/plugins/DaemonPlugin.go
apis/server/container_bridge.go
docs/features/pouch_with_plugin.md

fix some typo in comments and docs
@HusterWan PTAL

bugfix: fix some typo in doc and comments

---

daemon/containerio/cri_log_file.go
daemon/containerio/options.go
daemon/mgr/container.go
daemon/mgr/container_types.go
daemon/mgr/cri.go
hack/cri-test/test-cri.sh

feature: cri manager could get the log of container

---

daemon/mgr/container_types.go
daemon/mgr/container_utils.go
daemon/mgr/cri_utils.go
daemon/mgr/spec.go
daemon/mgr/spec_process.go
daemon/mgr/spec_root.go
hack/cri-test/test-cri.sh

feature: implement ReadOnlyRootfs and NoNewPrivs of cri manager

---

cli/version.go
daemon/mgr/system.go

add kernel value in 'pouch version' command

feature: add kernel value in 'pouch version' command

---

daemon/containerio/backend.go
daemon/containerio/container_io.go
daemon/containerio/cri_log_file.go
daemon/containerio/discard.go
daemon/containerio/hijack_conn.go
daemon/containerio/mem_buffer.go
daemon/containerio/raw_file.go
daemon/containerio/streams.go
daemon/mgr/cri.go
hack/cri-test/test-cri.sh

feature: seperate stdout & stderr of container io and support host network mode for sandbox

---

main.go

revert #917   because of #950 
fixes #950

bugfix: revert #917

---

main.go
pkg/exec/command.go
volume/types/volume.go

typo: unknow -> unknown

---

.circleci/config.yml
README.md

fix: logo image

---

client/container.go
client/system.go
daemon/mgr/container.go
daemon/mgr/cri.go
test/cli_network_test.go
test/util/util.go

This PR is to address the go misspell linting issues raised in the Go Report Card to partially address issue #964. See https://goreportcard.com/report/github.com/alibaba/pouch
This PR partially fixes issue #964.
Corrected misspell errors reported in Go Report Card. 
All misspell errors should be gone from Go Report Card.

[linting] Fix go misspell linting errors

---

cri/stream/remotecommand/httpstream.go
cri/stream/remotecommand/websocket.go
vendor/golang.org/x/net/websocket/client.go
vendor/golang.org/x/net/websocket/dial.go
vendor/golang.org/x/net/websocket/hybi.go
vendor/golang.org/x/net/websocket/server.go
vendor/golang.org/x/net/websocket/websocket.go
vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go
vendor/k8s.io/apiserver/pkg/util/wsstream/BUILD
vendor/k8s.io/apiserver/pkg/util/wsstream/conn.go
vendor/k8s.io/apiserver/pkg/util/wsstream/doc.go
vendor/k8s.io/apiserver/pkg/util/wsstream/stream.go
vendor/vendor.json

feature: websocket support for cri stream server

---

test/cli_top_test.go

debug for top ci test case
to debug: https://github.com/alibaba/pouch/issues/995

test: to debug top ci test case

---

apis/server/container_bridge.go
apis/server/router.go
apis/server/utils.go
apis/server/utils_test.go
client/container.go

add validation for container name

refactor: add validation for name in api server

---

INSTALLATION.md
hack/package/deb/systemd/pouch.service
hack/package/rpm/service/pouch.service

do not start lxcfs by default in pouchd deamon

rpm: do not start lxcfs by default in pouchd deamon

---

apis/server/router.go

make conflict from different merge consistent.
none
none
none
none

fix: make conflict from different merge consistent

---

cri/stream/docs.go
cri/stream/remotecommand/attach.go
cri/stream/remotecommand/errors.go
cri/stream/remotecommand/exec.go
cri/stream/remotecommand/httpstream.go
cri/stream/remotecommand/websocket.go
cri/stream/server.go
daemon/mgr/cri_stream.go

With this PR, we could get error if stream server handle exec or attach failed.

feature: error stream for cri stream server

---

CHANGELOG.md
version/version.go

Add CHANGELOG for 0.3.0

---

CHANGELOG.md

doc: improve 0.3.0 changelog

---

client/container.go
client/container_update.go
client/container_update_test.go

test:add container update test

---

cli/image_inspect.go
cli/inspect.go
cli/inspect/inspector.go
cli/network.go
cli/volume.go
pkg/utils/utils.go
pkg/utils/utils_test.go
test/cli_inspect_test.go

- add integration test for inspect command
- invoke MultiInspect in runInspect
This PR is related to pr #989 , and test cases for pouch volume inspect, pouch image inspect, pouch network inspect would be completed in the coming days.
Thanks for reviews and comments.

feature: enhance multiple inspection

---

README.md
docs/kubernetes/pouch_with_kubernetes_deploying.md

1. Make user be able find the documents relevant to Kubernetes easily.
2. Make the document of how to deploy Kubernetes with Pouch more complete and user-friendly.

doc: improve the doc of Kubernetes deployment

---

CHANGELOG.md
version/version.go

Merge 0.3.x to master branch

---

daemon/config/config.go
test/daemon/daemon.go
test/z_cli_daemon_test.go

test: add daemon test

---

client/container.go
client/container_list.go
client/container_list_test.go

test:add container list test

---

.travis.yml
Makefile
hack/make.sh

Now in on travisCI job, it runs both integration test and cri test. Separate them to speed up and to make it easy to find where is the problem.

test: seperate integration test and cri test in travisCI

---

daemon/config/config.go

config: support some flags in daemon config file

---

test/cli_rich_container_test.go

Skip test: TestRichContainerSystemdWorks, it fails these days frequently.

test: skip flaky test TestRichContainerSystemdWorks

---

daemon/mgr/spec_blkio.go

fix set disk quota failed without set quota id.
TestCase: TestRunWithDiskQuota failed.

bugfix: fix set diskquota failed without quota id

---

daemon/mgr/container.go

fix: fix code style

---

daemon/config/config.go
main.go
pkg/utils/utils.go
pkg/utils/utils_test.go
test/daemon/daemon.go
test/z_cli_daemon_test.go

add pidfile for daemon, avoid running serval daemon on host.

feature: add pidfile for daemon

---

CHANGELOG.md
version/version.go

doc: add changelog for 0.4.0

---

daemon/mgr/cri.go
daemon/mgr/cri_types.go
pkg/meta/backend.go
pkg/meta/boltdb.go
pkg/meta/local.go
pkg/meta/store.go

bugfix: persistent storage of sandbox metadata

---

cli/stop.go
test/cli_stop_test.go

stop cli support specify multi containers
fixes https://github.com/alibaba/pouch/issues/1080
```
root@osboxes:test (zr/stop-multi-items) -> pouch stop TestStopMultiContainer-1 TestStopMultiContainer-2
TestStopMultiContainer-1
TestStopMultiContainer-2
```

feature: stop cli support specify multi containers

---

test/z_cli_daemon_test.go

fix some typo
confilct -> conflict

typo: fix misspell in test code

---

docs/kubernetes/pouch_with_kubernetes_deploying.md
hack/kubernetes/allinone.sh

This pr update the cri-related docs and script, since pouch has changed its config when starting. Adding --enable-cri=true, it allows kubernetes to work with pouch.

docs: update cri-related docs to revise pouch config file

---

.circleci/config.yml
Dockerfile

Fix the golint download issue and make the ci happy.

bugfix: should use `go get -u golang.org/x/lint/golint`

---

test/cli_rich_container_test.go

The test always fail like #960, must fail in #1128, but can not reproduce in single test.

test: skip always fail test

---

daemon/mgr/container.go
test/cli_stop_test.go

make stop stopped container return no error.
This will be compatible with moby's API.
fxies #1207 
none
none
none

fix: make stop stopped container return no error

---

test/z_cli_daemon_test.go

As issue #1003 has been fixed, uncomment this.

test: uncomment daemon config test

---

storage/volume/types/meta/types.go

Signed-off-by: Chuanyun Li <lcy041536@gmail.com>
docs: fix misspell for ObjectMeta comments

docs: fix misspell for ObjectMeta comments

---

daemon/mgr/container.go
test/cli_update_test.go
vendor/github.com/magiconair/properties/CHANGELOG.md
vendor/github.com/magiconair/properties/LICENSE
vendor/github.com/magiconair/properties/README.md
vendor/github.com/magiconair/properties/decode.go
vendor/github.com/magiconair/properties/doc.go
vendor/github.com/magiconair/properties/integrate.go
vendor/github.com/magiconair/properties/lex.go
vendor/github.com/magiconair/properties/load.go
vendor/github.com/magiconair/properties/parser.go
vendor/github.com/magiconair/properties/properties.go
vendor/github.com/magiconair/properties/rangecheck.go
vendor/vendor.json

feature: update env when container is running

feature: support update env when container is running

---

cli/run.go
ctrd/container.go
daemon/containerio/cio.go

bugfix: handle container io properly when restart pouchd

---

daemon/config/config.go
main.go
storage/volume/config.go
storage/volume/core.go
storage/volume/driver/driver.go

Add volume driver alias, pouchd can config the exist volume driver's
alias.
NONE

feature: add volume driver alias

---

ctrd/README.md

fix wrong repo link in ctrd/README.md

fix pouch github address url 

---

daemon/mgr/network.go
main.go

Modify log format to
"time.RFC3339Nano=2006-01-02T15:04:05.999999999Z07:00"
NONE

bugfix: modify log format

---

daemon/mgr/spec.go

Signed-off-by: raoqi <1020216950@qq.com>

doc: fix word misspell

---

hack/build

This  pull request add `-race` flag to unit test which will definitely help a lot on detecting error.
It is added to the hack folder.
fix #https://github.com/alibaba/pouch/issues/1287
none
none
none

test: add -race to go test to detect race

---

docs/features/pouch_with_kata.md

support kata-container in pouch.

docs: add kata-container support docs

---

daemon/containerio/jsonfile.go
daemon/logger/jsonfile/jsonfile_read.go

Fix typo created by previous PR.
NONE
NONE
NONE

bugfix: fix the typo created by previous PR

---

cli/exec.go
cli/top.go

refactor: format topExamples code and add execExample.

refactor: format topExamples code and add execExample.

---

docs/test/test.md

Update test.md to make sure steps about how to run test are right.
Mainly add steps about setting GOPTAH to find libnetwork package.
fix #1320

doc: update test.md about how to run test

---

cli/common_flags.go
cli/container.go
daemon/mgr/spec_linux.go
test/cli_create_test.go
test/cli_run_test.go
test/cli_start_test.go

add pidslimit implement in create spec process,
and also support them in pouch run command.

feature: add pidslimit  implement

---

hack/make.sh
test/api_system_test.go
test/api_volume_create_test.go
test/api_volume_list_test.go
test/cli_volume_test.go
test/util_api.go

add some ci tests for volume plugin

test: add ci tests for volume plugin

---

docs/kubernetes/pouch_with_kubernetes_deploying.md
docs/kubernetes/pouch_with_kubernetes_deploying_aliyun.md

update doc of pouch with kubernetes deploying
None

doc: update doc of pouch with kubernetes deploying

---

hack/build
version/version.go

doc: change pouch version from 0.4.0 to 0.5.0-dev

---

hack/build
version/version.go

doc: change version to 0.5.0

---

apis/server/image_bridge.go
apis/server/router.go
apis/swagger.yml
cli/main.go
cli/tag.go
client/image_tag.go
client/image_tag_test.go
client/interface.go
ctrd/image.go
ctrd/interface.go
daemon/mgr/image.go
daemon/mgr/image_store.go
docs/kubernetes/pouch_with_kubernetes_deploying.md
docs/kubernetes/pouch_with_kubernetes_deploying_aliyun.md
hack/build
hack/cri-test/test-utils.sh
main.go
test/api_image_tag_test.go
test/cli_tag_test.go
test/utils.go
version/version.go

Merge 0.5.x to master

---

CHANGELOG.md

doc: add changelog for release 0.5.0

doc: add 0.5.0 ChangeLog

---

test/api_container_stop_test.go

fix a ineffectual assignment
NONE

test: fix a ineffectual assignment

---

vendor/README.md

s/prject/project in the vendor/README.md
none
none
none

fix typo in the vendor/README.md

---

cli/info.go
config/opt/runtime.go
config/opt/runtime_test.go
daemon/config/config.go
daemon/mgr/container.go
daemon/mgr/system.go
hack/make.sh
main.go
test/z_cli_daemon_test.go

1. support add-runtime in daemon
2. fix parse daemon flags twice
3. add runtime info in pouch info
1. support add-runtime in daemon
2. fix parse daemon flags twice, which make flags be set for twice
3. add runtime info in pouch info
4. fix slice-type flags merge not take effect, move merge flags
operation in runDaemon, since(*cobra.Command).Execute() will do flags
parse.

feature: add runtime config

---

docs/kubernetes/pouch_with_kubernetes_deploying.md
docs/kubernetes/pouch_with_kubernetes_deploying_aliyun.md
hack/kubernetes/allinone.sh
hack/kubernetes/allinone_aliyun.sh
vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2/api.pb.go
vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2/api.proto
vendor/vendor.json

Modify the document about `Deploy Kubernetes With Pouch` to make it friendly
None
Modify the document docs/kubernetes/pouch_with_kubernetes_deploying.md
Add script file hack/kubernetes/allinone_aliyun.sh
Update script file hack/kubernetes/allinone.sh
By the way , @idealhack 
```
govendor update github.com/alibaba/pouch/vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2
```
Execute the script file, and then choose the option that you want :
```
----------------------------------
Please choose the version of kubernetes
(1) kubernetes 1.9
(2) kubernetes 1.10
(0) exit
----------------------------------
1
KUBERNETES_VERSION: 1.9.4
----------------------------------
Whether to configure CNI config ?
(Y/y) Y
(N/n) N
(0) exit …
```

doc: Modify the document about Kubernetes&pouch to make it friendly

---

cri/criservice.go

Refactor: We should not lose the error in CRI service.

refactor: return CRI services error

---

.travis.yml

This pr changes ```echo "travis doesn't run for document-only changed"``` to ```echo travis doesn\'t run for document-only changed```, since ```"``` will cause the failure of json unmarsalling on the side of our friend pouchRobot.

enhance: revise configure file to make travis happy

---

apis/server/exec_bridge.go

Add container name in log for ``` container exec``` args.

enhance: specify container name for exec args

---

test/cli_run_memory_test.go

Make the CI happy.
NONE
gofmt -s -w test/cli_run_memory_test.go
NONE
NONE

bugfix: remove the blank line

---

cli/update_daemon.go

typo code comment, change `updateDescription` to
`daemonUpdateDescription`.

bugfix: typo code comments

---

test/z_cli_daemon_test.go

fix remove container error in daemon test.

bugfix: should remove the container in specified daemon

---

storage/volume/core_test.go
storage/volume/driver/driver.go
storage/volume/driver/fake_driver.go

add unit tests for CreateVolume
NONE
NONE
NONE

test: add unit-tests for core CreateVolume

---

apis/opts/cpu_test.go
apis/opts/oom_score_test.go
ctrd/image_proxy_util_test.go
daemon/config/config_test.go
storage/volume/core_test.go

remove the information about baiji

fix: remove the information about baiji

---

CONTRIBUTING.md

Updated the CONTRIBUTING.md doc and fixed some typing and formatting errors.
NONE
Added menu list item for "Test case contribution" in line 10.
Changed "lot of" to "a lot of" in line 25.
Changed "filing" to "filling" in line 38.
Moved the explaination of "rc" to the first place where it shows from line 99 to line 97 and added a space before "(".
Changed the "Test case contribution" from heading 3 to heading 2 in line 144.

docs: update docs about contributing

---

ctrd/image_proxy_util_test.go

Ⅰ. Describe what this PR did
#1641 add unit-test for proxy/has port
Ⅱ. Does this pull request fix one issue?
NONE
Ⅲ. Describe how you did it
NONE
Ⅳ. Describe how to verify it
NONE
Ⅴ. Special notes for reviews
NONE

test: add unit-test for proxy/has port

---

ctrd/image_proxy_util_test.go

Reverts alibaba/pouch#1668
ping @HusterWan @fuweid

Revert "test: add unit-test for proxy/has port"

---

ctrd/image_proxy_util_test.go

#1641:  add unit-test for hasPort method
NONE
NONE
NONE
NONE

test: add unit-test for hasPort method

---

pkg/term/term.go
vendor/github.com/pkg/term/LICENSE
vendor/github.com/pkg/term/termios/doc.go
vendor/github.com/pkg/term/termios/ioctl.go
vendor/github.com/pkg/term/termios/ioctl_darwin.go
vendor/github.com/pkg/term/termios/ioctl_solaris.go
vendor/github.com/pkg/term/termios/pty.go
vendor/github.com/pkg/term/termios/pty_bsd.go
vendor/github.com/pkg/term/termios/pty_darwin.go
vendor/github.com/pkg/term/termios/pty_linux.go
vendor/github.com/pkg/term/termios/pty_solaris.go
vendor/github.com/pkg/term/termios/termios.go
vendor/github.com/pkg/term/termios/termios_bsd.go
vendor/github.com/pkg/term/termios/termios_const.go
vendor/github.com/pkg/term/termios/termios_const_solaris.go
vendor/github.com/pkg/term/termios/termios_linux.go
vendor/github.com/pkg/term/termios/termios_solaris.go
vendor/github.com/pkg/term/termios/termios_windows.go
vendor/vendor.json

Make Pouch command line tool work on Darwin platform(MacOS).
fix missing syscall on MacOS and remove dependence between ctrd and cli.
compiled and run well.

enhance: Port Pouch Cli to Darwin(MacOS)

---

storage/volume/core_test.go

Ⅰ. Describe what this PR did
#1631  add unit-test for TestListVolumes
Ⅱ. Does this pull request fix one issue?
NONE
Ⅲ. Describe how you did it
NONE
Ⅳ. Describe how to verify it
NONE
Ⅴ. Special notes for reviews
NONE

test: TestListVolumes

---

hack/build
version/version.go

change version from 0.5.0 to 1.0.0-rc1
NONE
NONE
NONE

build: change version from 0.5.0 to 1.0.0-rc1

---

hack/build
version/version.go

build: change version from 0.5.0 to 1.0.0-rc1 (#1731)

---

daemon/mgr/container.go

if the volume is empty and image path is not empty, we will populate the volume with the image data
NONE

feature: populate empty volumes when creating container

---

CHANGELOG.md

Update CHANGELOG for 1.0.0-rc1
NONE
use third party tool to generate it.
eye ball....
NONE

docs: update CHANGELOG for 1.0.0-rc1

---

Makefile

Add missing document and unify upper and lower case letters.
Add missing document and unify upper and lower case letters.
Nothing
make help

bugfix: Add missing document in Makefile

---

CONTRIBUTING.md

Fix a typo in CONTRIBUTING.md
No
Change "you" to "your"
English grammar
Team 10

bugfix: a typo in CONTRIBUTTING.md

---

docs/features/pouch_with_runV.md

Signed-off-by: yuchuan <yuchuan.jyc@gmail.com>

BJ266-team10: fix spelling error

---

cri/v1alpha1/cri_utils_test.go

bugfix: cri Test_getSELinuxSecurityOpts

---

cri/stream/portforward/httpstream.go

There is an data race in pkg `cri/stream` when I build pouchd with flag `-race` and use cri-tools to test the stream server related api:
```
Read
cri/stream/portforward.(*httpStreamHandler).monitorStreamPair()
cri/stream/portforward/httpstream.go:135
Previous write
cri/stream/httpstream/spdy.(*connection).registerStream()
cri/stream/httpstream/spdy/connection.go:97
```
`%v` will read the underlying structure which is the source of the data race
we should use the `%p` to avoid it.

bugfix: data race in pkg cri/stream

---

cri/v1alpha1/cri_utils_test.go
cri/v1alpha2/cri_utils_test.go

test: add test cases about toCriContainer

---

cri/v1alpha1/cri_utils_test.go
cri/v1alpha2/cri_utils_test.go

test: add test cases about toCNIPortMappings

---

cri/v1alpha1/cri_utils_test.go
cri/v1alpha2/cri_utils_test.go

test: add test cases about modifyContainerConfig&containerNetns

---

.github/PULL_REQUEST_TEMPLATE.md

docs: update pull request template about test
After this, there is a question for everyone for test requesting.

docs: update pull request template about test

---

daemon/mgr/container.go

bugfix: do umount rootfs when failed to operate volumes

bugfix: do umount rootfs when failed to operate volumes

---

test/cli_run_volume_test.go

fix `TestRunWithDiskQuotaForLog` test case, remove add group and user.
NONE
It just fix test case bug.

bugfix: fix diskquota test case

---

Makefile
version/version.go

release 
just change the version
wait for CI

release: release 1.0.0-rc2 version

---

Makefile
version/version.go

We run PouchContainer for a while and service/functionality becomes more
and more stable. Thanks for all the contributors. It's time to release
the GA version.
Release
No need
CI

release: General availability

---

hack/build

update version for package deb
NONE
No need
CI

release: update version to 1.0.0

---

docs/features/pouch_with_criu.md

add doc for pouch checkpoint/restore function with criu.
add doc for pouch checkpoint/restore function with criu.
no need.

docs: add doc for pouch checkpoint/restore function with criu

---

daemon/mgr/container.go

When using PouchContainer to replace the old container engine in Alibaba Group, we must take over the old running containers. Maybe somebody has known that we use [d2p-migrator](https://github.com/pouchcontainer/d2p-migrator)  to convert those old containers to pouch containers
Since those old containers are not created by `pouchd`, but taking over by specified a rootfs for container, the remove action is different from normal containers. We no need to delete the snapshot of container because old containers have no snapshots, then we also should `umount` the rootfs when delete the container. 
None
It is difficult to imitate the situation of taking over containers, So i will add test case in `d2p` test. 
None
None

bugfix: umount rootfs when delete a container

---

Makefile
VAGRANT.md
Vagrantfile
hack/kubernetes/allinone_aliyun.sh

add quick experience pouch with kubernetes by vagrant
On MacOS or Linux
export POUCH_BUILD=true POUCH_KUBE=true
vagrant up
On Windows
set POUCH_BUILD=true
set POUCH_KUBE=true
vagrant up
vagrant ssh -c "sudo -i"
kubectl get po -o wide --all-namespaces

docs: add quick experience pouch with kubernetes by vagrant

---

apis/types/registry_service_config.go
hack/codegen/swagger.sh

Modify missing `omitempty` in json for api, genarate api by our swagger tool.
We use swagger-0.12.0, and cherry-pick commit: b6e18f
NONE
NONE

bugfix: fix error api json

---

hack/install/install_ci_related.sh

typo issue on hack/install/install_ci_related.sh
No
No
No
No

typo: fix typo on hack/install/install_ci_related.sh

---

contrib/completion/bash/pouch

add pouch events command completion.
add pouch events command completion.
No need.

bash_completion: add events command

---

Vagrantfile

Signed-off-by: Mark Liu <manlge168@gmail.com>
With vagrant, developers don't need to manually configure the PATH environment variable.
$ vagrant ssh -c "sudo -i"
$ go get -u github.com/derekparker/delve/cmd/dlv
$ dlv version
Delve Debugger
Version: 1.1.0
Build: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c

add $GOPATH/bin to PATH environment variable for root user.

---

daemon/mgr/image.go
daemon/mgr/image_store.go

when the containerd manages many big images, the pouchd ListImage will
consume a lot of CPU resources caused by containerd.Content.Read stream
grpc call.
In the k8s, the kubelet gc image manager will send the ListImage request
every 30s. If the containerd consumes too many CPU resources, it will
impact the container. Therefore, pouchd needs to cache the data.
NONE
no need 
CI

enhance: cache image size and oci image spec in pouchd

---

apis/swagger.yml
test/api_container_list_test.go
test/main_test.go

add test for container list api.
NONE
added
```bash
go test -check.f TestList.*
```

test: api_container_list_test: add filter test

---

apis/server/exec_bridge.go
apis/server/log_filter_writer.go
apis/server/server.go
daemon/mgr/container_utils.go

some minor change
- add timeout to server
- log exec info

refactor: several change

---

apis/opts/devicemappings_test.go
apis/opts/mountpoint_test.go

Add new checkpoints into devicemappings and mountpoint testing.
As summary.
go test

test: api_devicemappings_and_mountpoint_test: add new checkpoints

---

hack/install/install_critest.sh

as title described.
None.
None.
run the CI.
updated mainly for : https://github.com/alibaba/cri-tools/pull/3

[bugfix]: update the branch of cri-tools has been updated

---

test/cli_exec_test.go

As the title told.
None.
None.
`go test -gocheck.f PouchExecSuite`
None.

test: add testcase for cli exec -i opt

---

test/cli_stop_test.go
test/utils.go

1. add  inspect filter func 
2. use 1 to refactor the test case in cli stop test
3. add some clean up operation
None.
None.
`go test -gocheck.f PouchStopSuite`
None.

test: refactor the cli stop test

---

.travis.yml
INSTALLATION.md
Makefile
daemon/mgr/container_types.go
daemon/mgr/container_utils.go
daemon/mgr/container_validation.go
daemon/mgr/spec_apparmor_linux.go
daemon/mgr/spec_apparmor_linux_unsupported.go
daemon/mgr/spec_linux.go
daemon/mgr/spec_process.go
daemon/mgr/spec_seccomp_linux.go
daemon/mgr/spec_seccomp_unsupported.go
pkg/system/system.go
vendor/github.com/opencontainers/runc/libcontainer/apparmor/apparmor.go
vendor/github.com/opencontainers/runc/libcontainer/apparmor/apparmor_disabled.go
vendor/vendor.json

Split #2115   PR into 3 independent PR， here is the first, still need 2 more PRs in the TODO List.
1. add opencontainers/runc/libcontainer/apparmor vendor
2. security parameter include seccomp, apparmor and no-new-privileges
are not implement good, refactor these part when create new spec.
1. use pouchd default spec.
2. remove containerd default spec.
no.

 refactor: refactor security spec

---

Dockerfile

In pr https://github.com/alibaba/pouch/pull/2321 we have upgrade golang version into 1.10.4, while the goversion in Dockerfile is still 1.9.1.
This pr updates golang version in Dockerfile to correct 1.10.4
none
no need, only doc update.
none
none

docs: update golang version in Dockerfile to correct 1.10.4

---

Makefile
apis/metrics/metrics.go
apis/server/cri_bridge.go
apis/server/router.go
apis/server/server.go
apis/server/system_bridge.go
apis/server/types/handler.go
cri/metrics/metrics.go
daemon/daemon.go
docs/features/pouch_with_plugin.md
hookplugins/APIPlugin.go
hookplugins/apiplugin/apiplugin.go
pkg/utils/identify.go
pkg/utils/identify_test.go

Add http api plugin.
* update handler, enable to add, delete, modify the PouchContainer's HTTP API handler.
Defined as follow:
```
import "github.com/alibaba/pouch/apis/server/types"
// APIPlugin provide the ability to extend PouchContainer HTTP API and change how handler behave.
type APIPlugin interface {
// The default handler of each API would be passed in while starting HTTP server.
// UpdateHandler could register extra HTTP API to PouchContainer server,
// change the behavior of the default handler.
UpdateHandler([]*types.HandlerSpec) []*types.HandlerSpec
}
```
also refactor metrics, cri api to a unified format
related to #2406

feature: support api plugin

---

INSTALLATION.md
cli/version.go

Users might run into the issue caused by the kernel. I update the document about the requirement from pouchcontainer. Hope it can help.
NONE
no need
NONE
Next PR will check the plugin status for containerd. If it's not health, we should shutdown the pouchd.

doc: update requirement about golang and linux kernel

---

docs/features/pouch_with_gVisor.md

Add doc to describe how gVisor integrates into Pouch.
fix #1749

docs: pouch with gVisor

---

apis/opts/config/blkio_test.go

Add new checkpoints into blkio testing
As summary.

test: api_blkio_test: add new checkpoints

---

cri/stream/portforward/httpstream.go
ctrd/container.go

Drop by the gometalinter to check the code  :-)
N/A
N/A since it's just fix the code-style
gometalinter ./... to reduce some gofmt issue

enhance: add meaningful field in log/error msg

---

apis/filters/parse.go
apis/filters/parse_test.go
apis/server/volume_bridge.go
apis/swagger.yml
cli/volume.go
client/interface.go
client/volume_list.go
client/volume_list_test.go
daemon/mgr/volume.go
storage/volume/core.go
storage/volume/core_test.go
test/api_volume_list_test.go
test/cli_volume_test.go
test/environment/cleanup.go

Add `pouch volume ls` filter flag support.Support following filter type:
* driver, use driver name to do accurate match
* name, use volume name to do accurate match
* label, use label=key or label=key=value to do volume label filter
#2462 
Add both api test case and cli test case.
wait for CI.
None.

feature: add volume filter

---

daemon/config/config.go
daemon/config/config_test.go

test: add test cases for configuration of daemon

---

test/api_container_inspect_test.go
test/api_container_list_test.go
test/api_image_inspect_test.go
test/api_image_list_test.go
test/api_image_tag_test.go
test/api_network_create_test.go
test/api_network_inspect_test.go
test/api_network_list_test.go
test/cli_network_test.go
test/cli_pull_test.go
test/cli_rmi_test.go
test/cli_run_dns_test.go
test/cli_run_volume_test.go
test/cli_tag_test.go
test/environment/env.go
test/utils.go

refact test, merge some common image, and add image config for test.
NONE
Just refact test.

test: add image config for test.

---

docs/features/pouch_with_dragonfly.md

fix: dragonfly document is dead link

---

test/cli_run_device_test.go

I found that in the cli integration test of travis CI, `PouchRunDeviceSuite` test suite would cost lots of time. Then I try to aggregate some similar test cases into a single one to see if we could make to save time in test.
Four cases takes about 1min, and we need to check if the aggregation would reduce 3/4 of it.
```
PASS: /home/travis/gopath/src/github.com/alibaba/pouch/test/cli_run_device_test.go:59: PouchRunDeviceSuite.TestRunDevicePermissions	3.987s
PASS: /home/travis/gopath/src/github.com/alibaba/pouch/test/cli_run_device_test.go:140: PouchRunDeviceSuite.TestRunDeviceReadBps	14.241s
PASS: /home/travis/gopath/src/github.com/alibaba/pouch/test/cli_run_device_test.go:220: PouchRunDeviceSuite.TestRunDeviceReadIops	14.296s
PASS: …
```

test: aggregate deveice r/w bps/iops cases to reduce time

---

apis/opts/config/runtime_test.go

1. Add new checkpoint: TestRuntimeString;
2. Refactorying TestNewRuntime to make the code style consistent. Meanwhile, add a new test example in TestNewRuntime to make the coverage of NewRuntime is 100%.

test: add new checkpoint for apis/opts/config/runtime.go

---

hack/testing/run_daemon_cri_e2e.sh

The interface of pouch-cri has upgraded to kubernetes 1.12. we upgrade the e2e test together.

test: upgrade cri e2e test to v1.12

---

cli/main.go
cli/stats.go
cli/stats_helpers.go
daemon/mgr/container_stats.go
daemon/mgr/network.go
test/api_container_stats_test.go
test/cli_stats_test.go
vendor/github.com/docker/go-units/CONTRIBUTING.md
vendor/github.com/docker/go-units/MAINTAINERS
vendor/github.com/docker/go-units/circle.yml
vendor/github.com/docker/go-units/duration.go
vendor/github.com/docker/go-units/size.go
vendor/vendor.json

since we have stats api support both daemon and client side, so we can add this command.
fix #637 #2086
add cli test.
wait for CI
None.

feature: add stats cli command

---

ctrd/container.go
ctrd/container_types.go
daemon/config/config.go
daemon/config/config_test.go
daemon/mgr/container.go
daemon/mgr/spec.go
daemon/mgr/spec_linux.go
main.go
test/environment/env.go
test/z_cli_daemon_test.go

support systemd cgroup driver for pouch container.
support cgroup systemd driver
add a unit test and a ci test

feature: support cgroup systemd driver

---

.gitignore
.travis.yml
Makefile
hack/install/config.sh
hack/install/install_critest.sh
hack/install/install_criu.sh
hack/install/install_nsenter.sh
hack/install/install_runc.sh
hack/testing/run_daemon_cri_integration.sh
hack/testing/run_daemon_integration.sh
hack/testing/utils.sh
travis_ci.sh

refact travis-ci, make it run faster.
1. remove CRI v1alpha1 test
2. split the integration into multiple parts, let them run together,
because the limit of travis ci jobs, we only can split four parts.
3. update travis-ci os version to ubuntu-16.04 xenial,
because in this version, we can use apt-get to install criu, instead of
building it by ourself, it can reduce the setup time.
4. I have built `nsenter` and upload to aliyun oss storage server,
so only download it instead of building it every time.
NONE
refact test
ci pass

test: refact travis-ci

---

daemon/mgr/container_storage.go

when use volumes-from, need to check old volume mode.
with R/W mode, if hasn't set in new mode, we should inherit from
old mountpoint R/W mode.
with copy mode, if hasn't set `nocopy` in new mode, and also hasn't set
`nocopy` in old mountpoint mode, by default, we should set `CopyData` is
true.
NONE
may be test it manually
1. start container with `copydata` volume, and its image's directory has no data.
2. start new container with `volumes-from`, and the volume directory in new image has data
3. check new container's volume directory whether has image's data.

bugfix: check old volume mode

---

docs/features/pouch_with_log_driver.md

add doc to describe how to use `pouch run --log-driver`
[[help wanted][doc] add doc to describe how to use `pouch run --log-driver` ](https://github.com/alibaba/pouch/issues/1599)

docs: add doc to describe how to use `pouch run --log-driver`

---

cli/update_daemon.go
test/z_cli_daemon_test.go

Support to update daemon config with home dir and snapshotter.
No.
add test TestUpdateDaemonWithHomeDirAndSnapshotter.

support update daemon with home-dir and snapshotter

---

cri/annotations/annotations.go
cri/v1alpha2/cri_utils.go
cri/v1alpha2/cri_utils_test.go

Support to set memory swap by CRI interface. If set key resources.memory_swap in annotation, pouch will set it to container config.
Fix https://github.com/alibaba/pouch/issues/2698.
add testcase.
do it by testcase.

support memory swap by CRI

---

test/cli_network_test.go
test/cli_run_dns_test.go
test/cli_run_test.go

test `TestNetworkDefault`:
In host, it get the default route, so it should get default route in
container as same. Some server has mtu information in host, so we should
remove it.
test `TestRunWithBridgeNetwork`:
some server has configed the dns: 127.0.0.1, but it has been removed in
container by libnetwork, it causes the different from host dns config,
so we should remove dns: 127.0.0.1 when we compare them.
test `TestRunWithoutCapability`:
change `chown` command.
NONE
NA
ci pass

test: make test run happy

---

cli/common_flags.go
cli/container.go
test/cli_run_network_test.go

add set mac address for pouch cli.
NONE
added
ci pass

feature: add set mac address for pouch cli

---

ctrd/container.go

put different runtime to independent runtime root.
First, distinguish different runtime files. Secondly, it enables v1 containerd-shim to know which runtime to go (hack).

feature: independent runtime root

---

apis/types/container_config.go
apis/types/update_config.go

docs: add missing details generated by swagger
due to PR https://github.com/alibaba/pouch/pull/2745 has missed this part.
none
no need.
none
none

docs: add missing details generated by swagger

---

ctrd/container.go

Revert "feature: independent runtime root"

---

daemon/mgr/container_storage.go
daemon/mgr/container_storage_test.go
travis_ci.sh

when copy image content to volume, also do copy uid and gid from source. 
none.
no need.

feature: copy ownship when do copy image content

---

cri/annotations/annotations.go
cri/v1alpha2/cri_utils.go
cri/v1alpha2/cri_utils_test.go

CRI support to set pids limit by annotation in action of create and update .
none.
add unit test.

cri support to update pids limit by annotation

---

cli/common_flags.go

bugfix: remove comment line

---

cri/v1alpha2/cri_utils.go

ensure there is a non-empty runtime name in sandbox metadata
the criplugin's action depends on runtime name

fix: ensure there is a non-empty runtime name in sandbox metadata

---

ctrd/supervisord/config.go
ctrd/supervisord/option.go
daemon/daemon.go

support to get shim log into pouch log if the debug mode is open.
none
no need
CI

ctrd: support to show shim log

---

ctrd/client.go
ctrd/wrapper_client.go

In containerd 1.2.5 `WithLease` add a default expire time, so when pouchd starting, it will got a lease with expire time, so the pouchd will got errors calling containerd API when the lease expired.
So we create a named lease that is `pouchd.lease`.  when pouchd starting , we just fetch the named lease and make sure the lease do not have expire label.

bugfix: fix lease used by pouchd may be expired

---

cli/main.go
cli/push.go
ctrd/image.go

support push command cli
fixes #2099
no need

cli/ctrd: support push command cli

---

apis/opts/networks.go
cli/common_flags.go
cli/container.go
test/cli_run_network_test.go

support set ipv4 or ipv6 to container when create new container.
NONE
Added
ci pass

feature: support set ipv4 or ipv6 when create container

---

storage/quota/quota.go

remove useless break statement
fixes #2804 
NA
NA

remove useless break statement

---

daemon/mgr/container_stats.go

Some machine doesn't have cgroup controller, like pids. Therefore,
before we use it from metrics, we need to check the value.
none
using existing test case. 
wait for CI.
NOTE: the testing needs to disable cgroup function by `umount /sys/fs/cgroup/pids` something like that. It is kind of hacking. I did it in offline.

stats: check pointer before using metrics

---

test/cli_version_test.go

Add test information in cli_version_test.go.
NONE

Add test information in cli_version_test.go

---

daemon/mgr/container_copy.go
daemon/mgr/container_storage.go

for the copy command, we need to copy thing into container. But we can't
mount/umount the rootfs again, because it will impact /home and /tmp in
running container. Align with moby behaviour, we use the host rootfs
directly for running container without mount/unmount.
none 
no need

copy: should not mount rootfs again

---

docs/features/pouch_with_runV.md

fix small typo, use `ps -a` to see stopped and created container.
None.
no need.
no need.
No need.

fix: fix runv configure doc

---

docs/kubernetes/pouch_with_kubernetes_deploying.md

add a step to help people to setup k8s+pouch
No
No need
No need
None

fix docs: add taint step to enable schedule on master

---

apis/server/router.go
client/image_search.go
client/image_search_test.go
test/api_image_search_test.go

Signed-off-by: Junjun Li <junjunli666@gmail.com>
fix bug: search images api methods

fix: search images api methods

---

.travis.yml
Dockerfile
Vagrantfile
ctrd/utils.go
test/z_cli_daemon_test.go

upgrade go version to 1.12.6. ready for integration with kubernetes 1.14

upgrade: bump to Go 1.12.6

---

INSTALLATION.md

PouchContainer is officially supported in Alibaba Cloud Linux 2 (a.k.a.
Aliyun Linux 2), so add installation instructions to the documentation.
Signed-off-by: Caspar Zhang <caspar@linux.alibaba.com>
This Pull Request adds the documentation of installing PouchContainer inside Alibaba Cloud Linux 2 OS.
NONE.
Documentation work, tests are not required.
To verify the instructions, simply buy an ECS w/ `Aliyun Linux 2.1903` OS installed, then run the commands provided in the doc.
N/A

doc: add Aliyun Linux 2 support to INSTALLATION.md

---

vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go
vendor/vendor.json

related to https://github.com/alibaba/ocicni/pull/2

fix: dynamic reload cni default config

---

Makefile

Since kubernetes will use version in node list, v1.3.0 is too general
and we cannot tell no thing. Based on this, we can set the last commit
for the version.
none
no need

Makefile: add commit for the version

---

cri/v1alpha2/cri.go

1. for legacy dockershim style container, lifecycle of podNetwork is bound to container
using /proc/$pid/ns/net. When stopping sandbox, we first teardown the pod network, then stop
the sandbox container.
2. In newly implementation. We first create an empty netns and setup pod network inside it,
which is independent from container lifecycle. When stopping sandbox, we first stop container,
then teardown the pod network, which is a reverse operation of RunPodSandbox.
CRI test

fix: compatiable with legacy and newly pod when stop pod

---

daemon/mgr/container_utils.go

fix node e2e test

---

apis/server/router.go

add filter when graceful shutdown server

feature: add filter for flying request recorder

---

daemon/mgr/container_exec.go

mark execConfig as exited and used when start exec fails
exec gc will collect this config
exec config object would leak in memory after CRI ExecSync
1. crictl exec into a container
2. inspect container and execconfig will be empty after several minutes.

fix: exec config leak in cri exec

---

ctrd/snapshot.go
daemon/daemon.go
test/cli_restart_test.go

sync several improvement patches :
1. always take over the standard output of shim just in case that the shim is hang for log
2. try to unpack the image if the pulling action does not finish normally
no
added it

Sync to upstream

---

INSTALLATION.md

Signed-off-by: shinebayar-g <shinebayar.gansukh@gmail.com>
Fix simple typo in installation.md doc file.

docs: fix typo in installation

---

docs/kubernetes/pouch_cri_annotations_supported.md

update docs because the kubernetes v1.12 is EOF and RuntimeClass is beta feature
none
no need
CI

docs: update runtimeclass info

---

hack/testing/run_daemon_cri_e2e.sh

upgrade: bump critest and k8s e2e test to 1.16

---

INSTALLATION.md

Replace `http://mirrors.aliyun.com` in [INSTALLATION.md](https://github.com/alibaba/pouch/blob/master/INSTALLATION.md) with `https://mirrors.aliyun.com` to install PouchContainer from [mirrors.aliyun.com](https://mirrors.aliyun.com/opsx/) via HTTPS.
将 [INSTALLATION.md](https://github.com/alibaba/pouch/blob/master/INSTALLATION.md) 中的 `http://mirrors.aliyun.com` 替换为 `https://mirrors.aliyun.com`，以通过 HTTPS 从 [mirrors.aliyun.com](https://mirrors.aliyun.com/opsx/) 安装 PouchContainer。

Update Aliyun Mirror URL

---

CONTRIBUTING.md
docs/kubernetes/pouch_with_cri_introduction.md
docs/kubernetes/pouch_with_kubernetes_deploying_aliyun.md

much links in doc are outdated, update them and try to pass cricleci!
No
Yes

chore: update dead links in doc

---

client/container_top_test.go

Signed-off-by: Abirdcfly <fp544037857@gmail.com>
delete minor unreachable code caused by t.Fatal
NONE
Yes
No
No

delete minor unreachable code caused by t.Fatal

---

daemon/mgr/container_storage.go

fix CVE-2022-23648
fixes CVE-2022-23648
None
None

fix CVE-2022-23648

---

daemon/mgr/container_exec.go
daemon/mgr/spec_process.go
oci/spec_default.go

fix CVE-2022-24769

---

Makefile
version/version.go

version: bump to v1.3.1

---

vendor/github.com/containerd/containerd/images/archive/importer.go

fix containerd CVE-2023-25153
https://github.com/containerd/containerd/security/advisories/GHSA-259w-8hf6-59c2

fix containerd CVE-2023-25153

---

cli/stats_helpers.go
vendor/github.com/containerd/containerd/images/archive/importer.go

[Bugfix] fix nil pointer
